---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: A partir do ONTAP 9.7, o ONTAP Mediator pode auxiliar a configuração do MetroCluster IP na execução de uma comutação automática não planejada, fornecendo um repositório fisicamente separado para informações de status. 
---
= Requisitos de instalação do ONTAP Mediator para configurações IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seu ambiente precisa atender a certos requisitos.

Os requisitos a seguir se aplicam a um grupo de recuperação de desastres (grupo de DR). Saiba mais link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["Grupos DR"]sobre o .

* Se você planeja atualizar sua versão do Linux, faça isso antes de instalar a versão mais atual do ONTAP Mediator.
* Os softwares ONTAP Mediator e MetroCluster Tiebreaker não devem ser usados com a mesma configuração do MetroCluster.
* O ONTAP Mediator deve ser instalado em um host Linux em um local separado dos sites do MetroCluster.
+
A conetividade entre o Mediador ONTAP e cada site deve ser dois domínios de falha separados.

* O switchover não planejado automático é suportado no ONTAP 9.7 e posterior.
* A partir do ONTAP 9.18.1 e ONTAP Mediator 1.11, uma única instância do ONTAP Mediator pode gerenciar até dez MetroCluster configurações simultaneamente. Em versões anteriores, ONTAP Mediator pode suportar até cinco MetroCluster configurações simultaneamente.
* A partir do ONTAP 9.18.1, o IPv6 é suportado para o ONTAP Mediator 1.11 ou posterior em uma configuração IP MetroCluster .




== Requisitos de rede para usar o ONTAP Mediator em uma configuração MetroCluster

Para instalar o ONTAP Mediator em uma configuração MetroCluster, você deve garantir que a configuração atenda a vários requisitos de rede.

* Latência
+
Latência máxima inferior a 75ms ms (RTT).

+
O jitter não deve ser mais do que 5ms.

* MTU
+
O tamanho da MTU deve ser de pelo menos 1400.

* Perda de pacotes
+
Para o tráfego ICMP (Internet Control Message Protocol) e TCP, a perda de pacotes deve ser inferior a 0,01%.

* Largura de banda
+
O link entre o ONTAP Mediator e um grupo DR deve ter pelo menos 20 Mbps de largura de banda.

* Conetividade independente
+
É necessária conetividade independente entre cada local e o Mediador ONTAP. Uma falha em um local não deve interromper a conetividade IP entre os outros dois locais não afetados.





== Requisitos de host para o ONTAP Mediator em uma configuração MetroCluster

Você deve garantir que a configuração atenda a vários requisitos de host.

* O Mediador ONTAP deve ser instalado em um local externo fisicamente separado dos dois clusters do ONTAP.
* O ONTAP Mediator não requer mais do que os requisitos mínimos do sistema operacional host para CPU e memória (RAM).
* Além dos requisitos mínimos do sistema operacional host, pelo menos 30GBMB de espaço em disco utilizável adicional devem estar disponíveis.
+
** Cada grupo de DR requer até 200MB GB de espaço em disco.






== Requisitos de firewall para ONTAP Mediator

ONTAP Mediator utiliza diversas portas para se comunicar com serviços específicos.

Se você estiver usando um firewall de terceiro:

* O acesso HTTPS deve estar ativado.
* Deve ser configurado para permitir o acesso nas portas 31784 e 3260.
+
Ao usar o firewall padrão do Red Hat ou CentOS, o firewall é configurado automaticamente durante a instalação do Mediator.



A tabela a seguir lista as portas que você deve permitir no firewall:

[NOTE]
====
* A porta iSCSI só é necessária em uma configuração IP MetroCluster.
* A porta 22/tcp não é necessária para o funcionamento normal, mas você pode habilitá-la temporariamente para manutenção e desabilitá-la quando a sessão de manutenção terminar.


====
|===


| Porta/serviços | Fonte | Direção | Destino | Finalidade 


 a| 
22/tcp
 a| 
Host de gerenciamento
 a| 
Entrada
 a| 
ONTAP Mediator
 a| 
Gerenciamento do mediador SSH / ONTAP



 a| 
31784/tcp
 a| 
LIFs de cluster-mgmt e node-mgmt
 a| 
Entrada
 a| 
ONTAP Mediator servidor web
 a| 
API REST (HTTPS)



 a| 
3260/tcp
 a| 
LIFs de node-mgmt
 a| 
Entrada
 a| 
Alvos iSCSI do ONTAP Mediator
 a| 
Conexão de dados iSCSI para caixas de correio

|===


== Diretrizes para atualizar o ONTAP Mediator em uma configuração MetroCluster

Se você estiver atualizando o ONTAP Mediator, deverá atender aos requisitos de versão do Linux e seguir as diretrizes para a atualização.

* O ONTAP Mediator pode ser atualizado de uma versão imediatamente anterior para a versão atual.
* Todas as versões do Mediator são suportadas em configurações IP do MetroCluster executando o ONTAP 9.7 ou posterior.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Instalar ou atualizar o ONTAP Mediator"^]



== Após a atualização

Depois que a atualização do Mediator e do sistema operacional estiver concluída, você deverá emitir o `storage iscsi-initiator show` comando para confirmar se as conexões do Mediator estão ativas.
