---
permalink: install-ip/reference_where_to_find_additional_information_mccip_icg.html 
sidebar: sidebar 
keywords: metrocluster, ip, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: Você pode saber mais sobre a configuração e operação do MetroCluster IP na documentação do NetApp. 
---
= Onde encontrar informações adicionais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
Você pode saber mais sobre a configuração do MetroCluster.



== MetroCluster e informações diversas

|===


| Informações | Assunto 


 a| 
link:../install-fc/index.html["Instalação e configuração do MetroCluster conectado à malha"]
 a| 
* Arquitetura MetroCluster conectada à malha
* Fazer o cabeamento da configuração
* Configuração de pontes FC para SAS
* Configuração dos switches FC
* Configurando o MetroCluster no ONTAP




 a| 
link:../install-stretch/concept_considerations_differences.html["Instalação e configuração do Stretch MetroCluster"]
 a| 
* Arquitetura Stretch MetroCluster
* Fazer o cabeamento da configuração
* Configuração de pontes FC para SAS
* Configurando o MetroCluster no ONTAP




 a| 
link:../manage/index.html["Gerenciamento de MetroCluster"]
 a| 
* Compreender a configuração do MetroCluster
* Switchover, cura e switchback




 a| 
link:../disaster-recovery/concept_dr_workflow.html["Recuperação de desastres"]
 a| 
* Recuperação de desastres
* Comutação forçada
* Recuperação de uma falha de vários controladores ou armazenamento




 a| 
link:../maintain/index.html["Manutenção MetroCluster"]
 a| 
* Diretrizes para manutenção em uma configuração MetroCluster FC
* Procedimentos de substituição ou atualização de hardware e atualização de firmware para bridges FC para SAS e switches FC
* Adição automática de um compartimento de disco em uma configuração MetroCluster FC elástica ou conectada à malha
* Remoção automática de um compartimento de disco em uma configuração MetroCluster FC elástica ou conetada à malha
* Substituição de hardware em um local de desastre em uma configuração MetroCluster FC estendida ou conectada à malha
* Expansão de uma configuração Stretch MetroCluster FC ou conectada à malha de dois nós para uma configuração MetroCluster de quatro nós.
* Expansão de uma configuração de MetroCluster FC elástica ou conectada à malha de quatro nós para uma configuração de MetroCluster FC de oito nós.




 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Atualização e expansão do MetroCluster"]
 a| 
* Atualizando ou atualizando uma configuração do MetroCluster
* Expansão de uma configuração do MetroCluster com a adição de nós adicionais




 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["Transição do MetroCluster"]
 a| 
* Transição de uma configuração MetroCluster FC para uma configuração MetroCluster IP




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Atualização, transição e expansão do MetroCluster"]
 a| 
* Monitoramento da configuração do MetroCluster com o software tiebreaker da MetroCluster




 a| 
https://docs.netapp.com/us-en/ontap-systems/["Documentação dos sistemas de hardware da ONTAP"^]

*Nota:* os procedimentos de manutenção de prateleira de armazenamento padrão podem ser usados com configurações MetroCluster IP.
 a| 
* Adição automática de um compartimento de disco
* Remoção automática de um compartimento de disco




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transição baseada em cópia"^]
 a| 
* Transição de dados de sistemas de storage 7-Mode para sistemas de armazenamento em cluster




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["Conceitos de ONTAP"^]
 a| 
* Como os agregados espelhados funcionam


|===