---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Você pode remover o mediador ONTAP da configuração de IP do MetroCluster. 
---
= Desconfigurar o ONTAP Mediator da configuração de IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desconfigurar o ONTAP Mediator da configuração de IP do MetroCluster.

.Antes de começar
Você deve ter instalado e configurado com sucesso o ONTAP Mediator em um local de rede que possa ser acessado por ambos os sites do MetroCluster.

.Passos
. Desconfigure o ONTAP Mediator usando o seguinte comando:
+
`metrocluster configuration-settings mediator remove`

+
Você será solicitado a fornecer o nome de usuário e a senha para a conta de usuário do administrador do ONTAP Mediator.

+

NOTE: Se o Mediador ONTAP estiver inativo, o  `metrocluster configuration-settings mediator remove` O comando ainda solicita que você insira o nome de usuário e a senha da conta de usuário administrador do ONTAP Mediator e remove o ONTAP Mediator da configuração do MetroCluster.

+
.. Verifique se há discos quebrados usando o seguinte comando:
+
`disk show -broken`

+
*Exemplo*

+
....
There are no entries matching your query.
....


. Confirme se o ONTAP Mediator foi removido da configuração do MetroCluster executando os seguintes comandos em ambos os clusters:
+
.. `metrocluster configuration-settings mediator show`
+
*Exemplo*

+
[listing]
----
This table is currently empty.
----
.. `storage iscsi-initiator show -label mediator`
+
*Exemplo*

+
[listing]
----
There are no entries matching your query.
----



