---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: Você pode baixar e instalar em um terceiro site o software tiebreaker do MetroCluster ou, a partir do ONTAP 9.7, o Mediador do ONTAP. 
---
= Configurar o MetroCluster Tiebreaker ou o ONTAP Mediator para uma configuração de IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode baixar e instalar em um terceiro site o software tiebreaker do MetroCluster ou, a partir do ONTAP 9.7, o Mediador do ONTAP.

.Antes de começar
Você precisa ter um host Linux disponível que tenha conetividade de rede para ambos os clusters na configuração do MetroCluster. Os requisitos específicos estão na documentação do MetroCluster Tiebreaker ou do ONTAP Mediator.

Se você estiver se conectando a uma instância existente do Tiebreaker ou do ONTAP Mediator, precisará do nome de usuário, da senha e do endereço IP do Tiebreaker ou do Mediator.

Se for necessário instalar uma nova instância do Mediador ONTAP, siga as instruções para instalar e configurar o software.

link:concept_mediator_requirements.html["Configurar o ONTAP Mediator para comutação automática não planejada"]

Se for necessário instalar uma nova instância do software tiebreaker, siga o link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["instruções para instalar e configurar o software"].

.Sobre esta tarefa
Não é possível usar o software tiebreaker do MetroCluster e o Mediador do ONTAP com a mesma configuração do MetroCluster.

link:../install-ip/concept_considerations_mediator.html["Considerações sobre o uso do ONTAP Mediator ou do MetroCluster Tiebreaker"]

.Passo
. Configure o ONTAP Mediator ou o software Tiebreaker:
+
** Se você estiver usando uma instância existente do ONTAP Mediator, adicione o ONTAP Mediator ao ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host`

** Se você estiver usando o software tiebreaker, consulte o link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Documentação do desempate"].



