---
permalink: install-ip/task_sw_config_setup_ontap.html 
sidebar: sidebar 
keywords: metrocluster, ontap, setup 
summary: Depois de inicializar cada nó, você será solicitado a executar a configuração básica do nó e do cluster. Depois de configurar o cluster, você retorna à CLI do ONTAP para criar agregados e criar a configuração do MetroCluster. 
---
= Configurar nós ONTAP em uma configuração de IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de inicializar cada nó, você será solicitado a executar a configuração básica do nó e do cluster. Depois de configurar o cluster, você retorna à CLI do ONTAP para criar agregados e criar a configuração do MetroCluster.

.Antes de começar
* Você deve ter cabeado a configuração do MetroCluster.


Se for necessário inicializar via rede os novos controladores, link:../upgrade/upgrade-mcc-ip-prepare-system.html#netboot-the-new-controllers["Netboot os novos módulos do controlador"]consulte .

.Sobre esta tarefa
Essa tarefa deve ser executada em ambos os clusters na configuração do MetroCluster.

.Passos
. Ligue cada nó no site local se você ainda não o fez e deixe todos iniciarem completamente.
+
Se o sistema estiver no modo Manutenção, você precisará emitir o comando halt para sair do modo Manutenção e, em seguida, emitir o `boot_ontap` comando para inicializar o sistema e chegar à configuração do cluster.

. No primeiro nó em cada cluster, prossiga pelos prompts para configurar o cluster.
+
.. Ative a ferramenta AutoSupport seguindo as instruções fornecidas pelo sistema.
+
A saída deve ser semelhante ao seguinte:

+
[listing]
----
Welcome to the cluster setup wizard.

    You can enter the following commands at any time:
    "help" or "?" - if you want to have a question clarified,
    "back" - if you want to change previously answered questions, and
    "exit" or "quit" - if you want to quit the cluster setup wizard.
    Any changes you made before quitting will be saved.

    You can return to cluster setup at any time by typing "cluster setup".
    To accept a default or omit a question, do not enter a value.

    This system will send event messages and periodic reports to NetApp Technical
    Support. To disable this feature, enter
    autosupport modify -support disable
    within 24 hours.

    Enabling AutoSupport can significantly speed problem determination and
    resolution should a problem occur on your system.
    For further information on AutoSupport, see:
    http://support.netapp.com/autosupport/

    Type yes to confirm and continue {yes}: yes
.
.
.
----
.. Configure a interface de gerenciamento de nós respondendo aos prompts.
+
Os prompts são semelhantes aos seguintes:

+
[listing]
----
Enter the node management interface port [e0M]:
Enter the node management interface IP address: 172.17.8.229
Enter the node management interface netmask: 255.255.254.0
Enter the node management interface default gateway: 172.17.8.1
A node management interface on port e0M with IP address 172.17.8.229 has been created.
----
.. Crie o cluster respondendo aos prompts.
+
Os prompts são semelhantes aos seguintes:

+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
create


Do you intend for this node to be used as a single node cluster? {yes, no} [no]:
no

Existing cluster interface configuration found:

Port MTU IP Netmask
e0a 1500 169.254.18.124 255.255.0.0
e1a 1500 169.254.184.44 255.255.0.0

Do you want to use this configuration? {yes, no} [yes]: no

System Defaults:
Private cluster network ports [e0a,e1a].
Cluster port MTU values will be set to 9000.
Cluster interface IP addresses will be automatically generated.

Do you want to use these defaults? {yes, no} [yes]: no

Enter the cluster administrator's (username "admin") password:

Retype the password:


Step 1 of 5: Create a Cluster
You can type "back", "exit", or "help" at any question.

List the private cluster network ports [e0a,e1a]:
Enter the cluster ports' MTU size [9000]:
Enter the cluster network netmask [255.255.0.0]: 255.255.254.0
Enter the cluster interface IP address for port e0a: 172.17.10.228
Enter the cluster interface IP address for port e1a: 172.17.10.229
Enter the cluster name: cluster_A

Creating cluster cluster_A

Starting cluster support services ...

Cluster cluster_A has been created.
----
.. Adicione licenças, configure um SVM de Administração de clusters e insira informações de DNS respondendo aos prompts.
+
Os prompts são semelhantes aos seguintes:

+
[listing]
----
Step 2 of 5: Add Feature License Keys
You can type "back", "exit", or "help" at any question.

Enter an additional license key []:


Step 3 of 5: Set Up a Vserver for Cluster Administration
You can type "back", "exit", or "help" at any question.


Enter the cluster management interface port [e3a]:
Enter the cluster management interface IP address: 172.17.12.153
Enter the cluster management interface netmask: 255.255.252.0
Enter the cluster management interface default gateway: 172.17.12.1

A cluster management interface on port e3a with IP address 172.17.12.153 has been created. You can use this address to connect to and manage the cluster.

Enter the DNS domain names: lab.netapp.com
Enter the name server IP addresses: 172.19.2.30
DNS lookup for the admin Vserver will use the lab.netapp.com domain.

Step 4 of 5: Configure Storage Failover (SFO)
You can type "back", "exit", or "help" at any question.


SFO will be enabled when the partner joins the cluster.


Step 5 of 5: Set Up the Node
You can type "back", "exit", or "help" at any question.

Where is the controller located []: svl
----
.. Ative o failover de armazenamento e configure o nó respondendo aos prompts.
+
Os prompts são semelhantes aos seguintes:

+
[listing]
----
Step 4 of 5: Configure Storage Failover (SFO)
You can type "back", "exit", or "help" at any question.


SFO will be enabled when the partner joins the cluster.


Step 5 of 5: Set Up the Node
You can type "back", "exit", or "help" at any question.

Where is the controller located []: site_A
----
.. Conclua a configuração do nó, mas não crie agregados de dados.
+
Você pode usar o Gerenciador de sistema do ONTAP, apontando seu navegador da Web para o endereço IP de gerenciamento de cluster (\https://172.17.12.153).

+
https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/index.html["Gerenciamento de clusters usando o Gerenciador de sistemas (ONTAP 9.7 e anteriores)"^]

+
https://docs.netapp.com/us-en/ontap/index.html#about-ontap-system-manager["Gerenciador do sistema ONTAP (versão 9,7 e posterior)"]

.. Configure o processador de serviço (SP):
+
link:https://docs.netapp.com/us-en/ontap/system-admin/sp-bmc-network-config-concept.html["Configure a rede SP/BMC"^]

+
link:https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_service_processors.html["Use um processador de serviço com o Gerenciador do sistema - ONTAP 9.7 e anterior"^]



. Inicie o próximo controlador e junte-o ao cluster, seguindo as instruções.
. Confirme se os nós estão configurados no modo de alta disponibilidade:
+
`storage failover show -fields mode`

+
Caso contrário, você deve configurar o modo HA em cada nó e reinicializar os nós:

+
`storage failover modify -mode ha -node localhost`

+
[]
====

NOTE: O estado de configuração esperado de failover de HA e storage é o seguinte:

** O modo HA está configurado, mas o failover de armazenamento não está ativado.
** A funcionalidade de aquisição DE HA está desativada.
** As interfaces HA estão offline.
** O modo HA, o failover de storage e as interfaces são configurados posteriormente no processo.


====
. Confirme se você tem quatro portas configuradas como interconexões de cluster:
+
`network port show`

+
As interfaces IP MetroCluster não estão configuradas no momento e não aparecem na saída do comando.

+
O exemplo a seguir mostra duas portas de cluster no node_A_1:

+
[listing]
----
cluster_A::*> network port show -role cluster



Node: node_A_1

                                                                       Ignore

                                                  Speed(Mbps) Health   Health

Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status

--------- ------------ ---------------- ---- ---- ----------- -------- ------

e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false

e4e       Cluster      Cluster          up   9000  auto/40000 healthy  false


Node: node_A_2

                                                                       Ignore

                                                  Speed(Mbps) Health   Health

Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status

--------- ------------ ---------------- ---- ---- ----------- -------- ------

e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false

e4e       Cluster      Cluster          up   9000  auto/40000 healthy  false


4 entries were displayed.
----
. Repita estas etapas no cluster de parceiros.


.O que fazer a seguir
Retorne à interface da linha de comando ONTAP e conclua a configuração do MetroCluster executando as tarefas a seguir.
