---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: Se você não recebeu o equipamento já instalado em armários, você deve colocar os componentes em rack. 
---
= Componentes de hardware de configuração do MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você não recebeu o equipamento já instalado em armários, você deve colocar os componentes em rack.

.Sobre esta tarefa
Esta tarefa tem de ser executada em ambos os sites da MetroCluster.

.Passos
. Planeie o posicionamento dos componentes do MetroCluster.
+
O espaço em rack depende do modelo de plataforma dos módulos do controlador, dos tipos de switch e do número de pilhas de compartimento de disco na sua configuração.

. Aterre-se corretamente.
. Instale os módulos do controlador no rack ou gabinete.
+
Siga as etapas para _Instalar Hardware_ nas instruções de _Instalação e Configuração_ para o modelo da sua plataforma nolink:https://docs.netapp.com/us-en/ontap-systems/index.html["Documentação dos sistemas de hardware ONTAP"^] .

. Instale os switches IP no rack ou gabinete.
. Instale as gavetas de disco, ligue-as e, em seguida, defina as IDs das gaveta.
+
** É necessário desligar cada compartimento de disco.
** IDs de gaveta exclusivas são altamente recomendadas para cada gaveta de disco SAS em cada grupo de DR do MetroCluster para auxiliar na solução de problemas.


+

IMPORTANT: Não faça cabos com gavetas de disco destinadas a conter agregados sem espelhamento no momento. Você deve esperar para implantar gavetas destinadas a agregados sem espelhamento até que a configuração do MetroCluster esteja concluída e somente as implante depois de usar o `metrocluster modify -enable-unmirrored-aggr-deployment true` comando.


