---
permalink: install-ip/task_config_switch_health.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, snmp, health, monitoring 
summary: Você pode configurar os switches IP para usar o SNMPv3 para monitoramento de integridade. 
---
= Configurar switches IP MetroCluster para monitoramento de integridade
:allow-uri-read: 


[role="lead"]
Nas configurações IP do MetroCluster, você pode configurar o SNMPv3 para monitorar a integridade dos switches IP.



== Passo 1: Configure o usuário SNMPv3 em switches IP MetroCluster

Siga as etapas a seguir para configurar o usuário SNMPv3 nos switches IP do MetroCluster.


IMPORTANT: Você deve usar os protocolos de autenticação e privacidade nos comandos. O uso de autenticação sem privacidade não é suportado.

[role="tabbed-block"]
====
.Para switches IP Broadcom
--
.Passos
. Se o grupo de utilizadores 'network-admin' ainda não existir, crie-o:
+
`(IP_switch_1) (Config)# snmp-server group network-admin v3 auth read "Default"`

. Confirme se o grupo 'network-admin' foi criado:
+
`(IP_switch_1) (Config)# show snmp group`

. Configure o usuário SNMPv3 em switches IP Broadcom:
+
[listing]
----
(IP_switch_1)# config
(IP_switch_1) (Config)# snmp-server user <user_name> network-admin [auth-md5/auth-sha/noauth] "<auth_password>" [priv-aes128/priv-des] "<priv_password>"
----
+
Você deve usar aspas em torno das senhas de autenticação e privacidade, como mostrado no exemplo a seguir:

+
[listing]
----
snmp-server user admin1 network-admin auth-md5 "password" priv-des "password"
----


--
.Para switches IP Cisco
--
.Passos
. Execute os seguintes comandos para configurar o usuário SNMPv3 em um switch IP Cisco:
+
[listing]
----
IP_switch_A_1 # configure terminal
IP_switch_A_1 (config) # snmp-server user <user_name>  auth [md5/sha/sha-256] <auth_password> priv (aes-128) <priv_password>
----
. Verifique se o usuário SNMPv3 está configurado no switch:
+
`IP_switch_A_1(config) # show snmp user <user_name>`

+
A saída de exemplo a seguir mostra que o usuário `admin` está configurado para SNMPv3:

+
[listing]
----
IP_switch_A_1(config)# show snmp user admin
User                Auth      Priv(enforce) Groups              acl_filter

____                ____      _____________ ______              __________

admin               md5       aes-128(no)   network-admin
----


--
====


== Passo 2: Configure o usuário SNMPv3 no ONTAP

Siga as etapas a seguir para configurar o usuário SNMPv3 no ONTAP.

. Configure o usuário SNMPv3 no ONTAP:
+
`security login create -user-or-group-name <user_name> -application snmp -authentication-method usm -remote-switch-ipaddress <ip_address>`

. Configure a monitorização do estado do comutador para monitorizar o comutador utilizando o novo utilizador SNMPv3:
+
`system switch ethernet modify -device <device_id> -snmp-version SNMPv3 -community-or-username <user_name>`

. Verifique se o número de série do dispositivo que será monitorado com o usuário SNMPv3 recém-criado está correto:
+
.. Apresentar o período de tempo de polling da monitorização do estado do interrutor:
+
`system switch ethernet polling-interval show`

.. Execute o seguinte comando após o período de tempo de polling ter decorrido:
+
`system switch ethernet show-all -instance -device <device_serial_number>`




