---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: Você pode baixar e instalar em um terceiro site o software tiebreaker do MetroCluster ou, a partir do ONTAP 9.7, o Mediador do ONTAP. 
---
= Configurando o software tiebreaker do MetroCluster ou do ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode baixar e instalar em um terceiro site o software tiebreaker do MetroCluster ou, a partir do ONTAP 9.7, o Mediador do ONTAP.

.Antes de começar
Você precisa ter um host Linux disponível que tenha conetividade de rede para ambos os clusters na configuração do MetroCluster. Os requisitos específicos estão na documentação do MetroCluster Tiebreaker ou do ONTAP Mediator.

Se você estiver se conetando a uma instância existente do tiebreaker ou do ONTAP Mediator, precisará do nome de usuário, senha e endereço IP do serviço tiebreaker ou Mediator.

Se for necessário instalar uma nova instância do Mediador ONTAP, siga as instruções para instalar e configurar o software.

link:concept_mediator_requirements.html["Configuração do serviço ONTAP Mediator para switchover automático não planejado"]

Se for necessário instalar uma nova instância do software tiebreaker, siga o link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["instruções para instalar e configurar o software"].

.Sobre esta tarefa
Não é possível usar o software tiebreaker do MetroCluster e o Mediador do ONTAP com a mesma configuração do MetroCluster.

link:../install-ip/concept_considerations_mediator.html["Considerações sobre o uso do ONTAP Mediator ou do MetroCluster Tiebreaker"]

.Passo
. Configure o serviço do ONTAP Mediator ou o software tiebreaker:
+
** Se você estiver usando uma instância existente do Mediador ONTAP, adicione o serviço Mediador ONTAP ao ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host`

** Se você estiver usando o software tiebreaker, consulte o link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Documentação do desempate"].



