---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: Se você não recebeu o equipamento já instalado em armários, você deve colocar os componentes em rack. 
---
= Colocar em pilha os componentes de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você não recebeu o equipamento já instalado em armários, você deve colocar os componentes em rack.

.Sobre esta tarefa
Esta tarefa tem de ser executada em ambos os sites da MetroCluster.

.Passos
. Planeie o posicionamento dos componentes do MetroCluster.
+
O espaço em rack depende do modelo de plataforma dos módulos do controlador, dos tipos de switch e do número de pilhas de compartimento de disco na sua configuração.

. Aterre-se corretamente.
. Instale os módulos do controlador no rack ou gabinete.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["Instruções de instalação e configuração dos sistemas AFF A220/FAS2700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2870798["Instruções de instalação e configuração de sistemas AFF A250"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["Instruções de instalação e configuração de sistemas AFF A300"^]

+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["Sistemas AFF A320: Instalação e configuração"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2858854["Instruções de instalação e configuração de sistemas AFF A400"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2873445["Instruções de instalação e configuração de sistemas AFF A700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["Instruções de instalação e configuração de sistemas AFF A800"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2872833["Instruções de instalação e configuração de sistemas FAS500f"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["Instruções de instalação e configuração de sistemas FAS8200"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2858856["Instruções de instalação e configuração dos sistemas FAS8300 e FAS8700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874463["Instruções de instalação e configuração de sistemas FAS9000"^]



. Instale os switches IP no rack ou gabinete.
. Instale as gavetas de disco, ligue-as e, em seguida, defina as IDs das gaveta.
+
** É necessário desligar cada compartimento de disco.
** IDs de gaveta exclusivas são altamente recomendadas para cada gaveta de disco SAS em cada grupo de DR do MetroCluster para auxiliar na solução de problemas.


+

IMPORTANT: Não faça cabos com gavetas de disco destinadas a conter agregados sem espelhamento no momento. Você deve esperar para implantar gavetas destinadas a agregados sem espelhamento até que a configuração do MetroCluster esteja concluída e somente as implante depois de usar o `metrocluster modify -enable-unmirrored-aggr-deployment true` comando.


