---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Você pode remover o mediador ONTAP da configuração de IP do MetroCluster. 
---
= Remover o mediador ONTAP de uma configuração de IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desconfigurar o ONTAP Mediator da configuração de IP do MetroCluster.

.Antes de começar
Você deve ter instalado e configurado com sucesso o ONTAP Mediator em um local de rede que possa ser acessado por ambos os sites do MetroCluster.

.Passos
. Desconfigure o ONTAP Mediator usando o seguinte comando:
+
`metrocluster configuration-settings mediator remove`

+
Você será solicitado a fornecer o nome de usuário e a senha para a conta de usuário do administrador do ONTAP Mediator.

+

NOTE: Se o Mediador ONTAP estiver inativo, o  `metrocluster configuration-settings mediator remove` O comando ainda solicita que você insira o nome de usuário e a senha da conta de usuário administrador do ONTAP Mediator e remove o ONTAP Mediator da configuração do MetroCluster.

+
.. Verifique se há discos quebrados usando o seguinte comando:
+
`disk show -broken`

+
*Exemplo*

+
....
There are no entries matching your query.
....


. Se você estiver usando um ONTAP Mediator que utiliza HTTPS para comunicação, exclua os certificados da CA após remover o ONTAP Mediator:
+
.. Exibir os certificados CA instalados:
+
`security certificate show -common-name ONTAPMediatorCA`

.. Remova os certificados raiz e intermediários instalados:
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. Confirme se o ONTAP Mediator foi removido da configuração MetroCluster executando o seguinte comando em ambos os clusters:
+
.. `metrocluster configuration-settings mediator show`
+
*Exemplo*

+
[listing]
----
This table is currently empty.
----



