---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: O ONTAP Mediator deve ser configurado no nó ONTAP para uso em uma configuração de IP do MetroCluster. 
---
= Configurar o ONTAP Mediator para uma configuração de IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o ONTAP Mediator no nó ONTAP para usá-lo em uma configuração IP do MetroCluster .

.Antes de começar
* O ONTAP Mediator deve ter sido instalado com sucesso em um local de rede que possa ser acessado por ambos os sites do MetroCluster.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Instalar ou atualizar o ONTAP Mediator"^]

* Você deve ter o endereço IP do host executando o ONTAP Mediator.
* Você deve ter o nome de usuário e a senha do ONTAP Mediator.
* Todos os nós da configuração IP do MetroCluster devem estar online.



CAUTION: A partir do ONTAP 9.12,1, você pode ativar o recurso de comutação forçada automática MetroCluster em uma configuração IP MetroCluster. Este recurso é uma extensão da comutação não planejada assistida por Mediator. Antes de ativar esta funcionalidade, reveja o link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["Riscos e limitações do uso do switchover forçado automático do MetroCluster"].

.Sobre esta tarefa
* Esta tarefa permite o switchover não planejado automático por padrão.
* Você pode executar essa tarefa na interface ONTAP de qualquer nó na configuração IP MetroCluster.
* A partir do ONTAP 9.18.1 e ONTAP Mediator 1.11, uma única instância do ONTAP Mediator configurada com iSCSI pode gerenciar até dez MetroCluster configurações simultaneamente. No ONTAP 9.17.1 e ONTAP Mediator 1.10 e versões anteriores, um ONTAP Mediator configurado com iSCSI pode suportar até cinco MetroCluster configurações simultaneamente.
* A partir do ONTAP 9.19.1 e ONTAP Mediator 1.12, você pode instalar ONTAP Mediator com suporte para iSCSI e HTTPS, ou somente HTTPS. Se você instalou ONTAP Mediator para HTTPS apenas, não é possível configurar um Mediator com iSCSI.
* Se você não especificar o  `-type`parâmetro no  `metrocluster configuration-settings mediator add`comando, o protocolo iSCSI padrão será usado.
* Se você configurar ONTAP Mediator com HTTPS, uma única instância do ONTAP Mediator poderá monitorar apenas uma configuração de IP MetroCluster. O monitoramento simultâneo de várias configurações de IP MetroCluster não é compatível quando o ONTAP Mediator está configurado com HTTPS.
* Se você precisar do ONTAP Mediator configurado com HTTPS para monitorar várias configurações de IP do MetroCluster, deverá configurar instâncias separadas do ONTAP Mediator para cada configuração de IP do MetroCluster. Você deve avaliar cuidadosamente os requisitos do seu ambiente de IP do MetroCluster antes de optar por configurar o ONTAP Mediator com HTTPS para MetroCluster IP.
* Se você deseja usar uma única instância do ONTAP Mediator para monitorar mais de uma configuração de IP MetroCluster, deve configurar o ONTAP Mediator usando iSCSI em vez de HTTPS.


[role="tabbed-block"]
====
.Configurar um ONTAP Mediator com HTTPS
--
A partir do ONTAP 9.19.1 e ONTAP Mediator 1.12, é possível configurar um ONTAP Mediator que utiliza HTTPS para comunicação em uma configuração IP MetroCluster.

.Passos
. Localize os certificados da Autoridade Certificadora (CA) do ONTAP Mediator no local de instalação do software ONTAP Mediator Linux VM/host:
+
`[root@ontap-mediator ~] cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config`

+
Você deverá ver uma saída semelhante ao seguinte exemplo:

+
[listing]
----
1-ontap-mediator.rules  intermediate.crt   make_self_signed_certs.sh      ontap_mediator_server_chain.crt  ontap_mediator.user_config.yaml  root_ca.crt
config_migration        intermediate.key   netapp_sudoers                 ontap_mediator_server.crt        openssl_ca.cnf                   root_ca.key
config.pyc              intermediate.srl   ontap_mediator.config.yaml     ontap_mediator_server.csr        openssl_intermediate.cnf
__init__.pyc            logging.conf.yaml  ontap_mediator.constants.yaml  ontap_mediator_server.key        openssl_server.cnf
----
. Exibir o conteúdo do certificado da autoridade certificadora raiz:
+
`[root@ontap-mediator ~] cat root_ca.crt`

+
[listing]
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
----
. Exibir o conteúdo do certificado da CA intermediária:
+
`[root@ontap-mediator ~] cat intermediate.crt`

+
[listing]
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
----
. Instale os certificados raiz e intermediários da CA no local A:
+
.. Instale o certificado da CA raiz:
+
`security certificate install -type server-ca -vserver <vserver_name>`

+
Digite o  `root_ca.crt` quando solicitado, conforme mostrado no exemplo a seguir:

+
[listing]
----
cluster_A::*> security certificate install -type server-ca -vserver cluster_A

Enter certificate: Press <Enter> when done

-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----


. Instale o certificado CA intermediário:
+
`security certificate install -type server-ca -vserver <vserver_name>`

+
Digite o  `intermediate.crt` quando solicitado, conforme mostrado no exemplo a seguir:

+
[listing]
----
cluster_A::*> security certificate install -type server-ca -vserver cluster_A

Enter certificate: Press <Enter> when done

-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----
. Repita a etapa anterior para instalar os certificados CA raiz e intermediários no local B.
. Veja os certificados de CA autoassinados instalados usando o nome gerado dos certificados:
+
`security certificate show -common-name <common_name>`

+
Você deverá ver uma saída semelhante ao seguinte exemplo:

+
[listing]
----
security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number      Certificate Name                     Type
---------- ---------------    ------------------------------------ ------------
cluster_A  <serial_value>     ONTAPMediatorCA                      server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

cluster_A  <serial_value>    ONTAPMediatorCA                       server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

2 entries were displayed.
----
. Adicionar o ONTAP Mediator ao ONTAP.  Os passos dependem se você deseja usar um endereço IPv4 ou IPv6.
+
[NOTE]
====
** Para usar IPv6, você precisa estar executando o ONTAP 9.18.1 ou posterior e o ONTAP Mediator 1.11 ou posterior.
** Se você habilitar o IPv6 em um cluster, não poderá desabilitá-lo posteriormente.


====
+
.. Se você deseja usar o IPv6, conclua as seguintes etapas:
+
Para usar IPv4, pule para <<https_ipv4_step8b,a etapa IPv4>>.

+
... Execute o seguinte comando em ambos os clusters:
+
`network options ipv6 modify -enabled true`

... Configure o endereço IP de gerenciamento do nó com endereços IPv6 em todos os quatro nós.
... Adicionar o mediador ONTAP :
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type https-mediator`

+

NOTE: Insira o nome de usuário e a senha do administrador do Mediator quando solicitado.



.. [[https_ipv4_step8b]]Se você deseja usar IPv4, conclua a seguinte etapa:
+
... Adicionar o mediador ONTAP :
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type https-mediator`

+

NOTE: Insira o nome de usuário e a senha do administrador do Mediator quando solicitado.





. Verifique o status da conexão e o tipo de Mediator ONTAP:
+
`metrocluster configuration-settings mediator show`

+
Você deverá ver uma saída semelhante ao seguinte exemplo:

+
[listing]
----
cluster_A::*> metrocluster configuration-settings mediator show
        Mediator IP     Port    Type              Node                    Configuration Connection
                                                  Status                  Status
        --------------- ------- ----------------- ----------------------- ------------- -----------
        10.101.101.101
                        31784   https-mediator    cluster1_node_01        true          true
                                                  cluster1_node_02        true          true
                                                  cluster2_node_01        true          true
                                                  cluster2_node_02        true          true
----
+
.. Verifique se a funcionalidade de comutação automática está ativada:
+
`metrocluster show`

.. Verifique se o Mediador está em execução.
+
... Mostrar os discos virtuais do Mediator:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
... Verifique o estado do domínio de falha de switchover não planejado automático (AUSO):
+
`metrocluster show`

+

NOTE: A saída de exemplo a seguir se aplica ao ONTAP 9.13,1 e posterior. Para o ONTAP 9.12,1 e anteriores, o estado do domínio de falha do AUSO deve ser `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----






--
.Configurar um ONTAP Mediator com iSCSI
--
.Passos
. Adicionar o ONTAP Mediator ao ONTAP.  Os passos dependem se você deseja usar um endereço IPv4 ou IPv6.
+
[NOTE]
====
** Para usar IPv6, você precisa estar executando o ONTAP 9.18.1 ou posterior e o ONTAP Mediator 1.11 ou posterior.
** Se você habilitar o IPv6 em um cluster, não poderá desabilitá-lo posteriormente.


====
+
.. Se você deseja usar o IPv6, conclua as seguintes etapas:
+
Para usar IPv4, pule para <<iscsi_ipv4_step8b,a etapa IPv4>>.

+
... Execute o seguinte comando em ambos os clusters:
+
`network options ipv6 modify -enabled true`

... Configure o endereço IP de gerenciamento do nó com endereços IPv6 em todos os quatro nós.
... Adicionar o mediador ONTAP :
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type iscsi-mediator`

+

NOTE: Insira o nome de usuário e a senha do administrador do Mediator quando solicitado.



.. [[iscsi_ipv4_step8b]]Se você deseja usar IPv4, conclua a seguinte etapa:
+
... Adicionar o mediador ONTAP :
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type iscsi-mediator`

+

NOTE: Insira o nome de usuário e a senha do administrador do Mediator quando solicitado.



.. Verifique se a funcionalidade de comutação automática está ativada:
+
`metrocluster show`

.. Verifique se o Mediador está em execução.
+
... Mostrar os discos virtuais do Mediator:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
... Defina o modo de privilégio como avançado:
+
`set advanced`

+
....
 cluster_A::> set advanced
....
... Exiba os iniciadores rotulados como mediador:
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
... Verifique o estado do domínio de falha de switchover não planejado automático (AUSO):
+
`metrocluster show`

+

NOTE: A saída de exemplo a seguir se aplica ao ONTAP 9.13,1 e posterior. Para o ONTAP 9.12,1 e anteriores, o estado do domínio de falha do AUSO deve ser `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----






--
====