---
permalink: install-ip/task_sw_config_assign_pool0.html 
sidebar: sidebar 
keywords: metrocluster, controller, assign drives, pool 0, disk assign 
summary: Se você não recebeu os sistemas pré-configurados de fábrica, talvez seja necessário atribuir manualmente as unidades do pool 0. Dependendo do modelo da plataforma e se o sistema está usando ADP, você deve atribuir manualmente unidades ao pool 0 para cada nó na configuração IP do MetroCluster. O procedimento utilizado depende da versão do ONTAP que está a utilizar. 
---
= Atribuindo manualmente unidades ao pool 0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você não recebeu os sistemas pré-configurados de fábrica, talvez seja necessário atribuir manualmente as unidades do pool 0. Dependendo do modelo da plataforma e se o sistema está usando ADP, você deve atribuir manualmente unidades ao pool 0 para cada nó na configuração IP do MetroCluster. O procedimento utilizado depende da versão do ONTAP que está a utilizar.



== Atribuição manual de unidades para o pool 0 (ONTAP 9.4 e posterior)

Se o sistema não tiver sido pré-configurado de fábrica e não atender aos requisitos de atribuição automática de unidades, você deverá atribuir manualmente as unidades 0 do pool.

.Sobre esta tarefa
Este procedimento aplica-se às configurações que executam o ONTAP 9.4 ou posterior.

Para determinar se o sistema necessita de atribuição manual de disco, deve rever link:concept_considerations_drive_assignment.html["Considerações para atribuição automática de acionamento e sistemas ADP no ONTAP 9.4 e posterior"]o .

Execute estas etapas no modo Manutenção. O procedimento deve ser executado em cada nó na configuração.

Os exemplos nesta seção são baseados nas seguintes suposições:

* Unidades próprias Node_A_1 e node_A_2 em:
+
** Site_A-shelf_1 (local)
** Local_B-shelf_2 (remoto)


* Unidades próprias do nó_B_1 e do nó_B_2 em:
+
** Site_B-shelf_1 (local)
** Local_A-shelf_2 (remoto)




.Passos
. Apresentar o menu de arranque:
+
`boot_ontap menu`

. Selecione a opção 9a e responda `no` quando solicitado.
+
A tela a seguir mostra o prompt do menu de inicialização:

+
[listing]
----

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 9a

...

########## WARNING: AGGREGATES WILL BE DESTROYED ##########
This is a disruptive operation that applies to all the disks
that are attached and visible to this node.

Before proceeding further, make sure that:

The aggregates visible from this node do not contain
data that needs to be preserved.
This option (9a) has been executed or will be executed
on the HA partner node (and DR/DR-AUX partner nodes if
applicable), prior to reinitializing any system in the
HA-pair or MetroCluster configuration.
The HA partner node (and DR/DR-AUX partner nodes if
applicable) is currently waiting at the boot menu.
Do you want to abort this operation (yes/no)? no
----
. Quando o nó for reiniciado, pressione Ctrl-C quando solicitado a exibir o menu de inicialização e selecione a opção para *Inicialização do modo de manutenção*.
. No modo Manutenção, atribua manualmente unidades para os agregados locais no nó:
+
`disk assign _disk-id_ -p 0 -s _local-node-sysid_`

+
As unidades devem ser atribuídas simetricamente, de modo que cada nó tenha um número igual de unidades. As etapas a seguir referem-se a uma configuração com duas gavetas de storage em cada local.

+
.. Ao configurar node_A_1, atribua manualmente unidades do slot 0 a 11 a pool0 do nó A1 a partir do site_A-shelf_1.
.. Ao configurar node_A_2, atribua manualmente unidades do slot 12 a 23 a pool0 do nó A2 a partir do site_A-shelf_1.
.. Ao configurar node_B_1, atribua manualmente unidades do slot 0 a 11 a pool0 do nó B1 a partir do site_B-shelf_1.
.. Ao configurar node_B_2, atribua manualmente unidades do slot 12 a 23 a pool0 do nó B2 a partir do site_B-shelf_1.


. Sair do modo de manutenção:
+
`halt`

. Apresentar o menu de arranque:
+
`boot_ontap menu`

. Repita estas etapas nos outros nós na configuração IP do MetroCluster.
. Selecione a opção *4* no menu de inicialização em ambos os nós e deixe o sistema inicializar.
. Prossiga para link:task_sw_config_setup_ontap.html["Configurar o ONTAP"].




== Atribuição manual de unidades para o pool 0 (ONTAP 9.3)

Se você tiver pelo menos duas gavetas de disco para cada nó, use a funcionalidade de atribuição automática do ONTAP para atribuir automaticamente os discos locais (pool 0).

.Sobre esta tarefa
Enquanto o nó estiver no modo Manutenção, primeiro é necessário atribuir um único disco nas prateleiras apropriadas ao pool 0. Em seguida, o ONTAP atribui automaticamente o restante dos discos na gaveta ao mesmo pool. Esta tarefa não é necessária nos sistemas recebidos de fábrica, que têm o pool 0 para conter o agregado raiz pré-configurado.

Este procedimento aplica-se às configurações que executam o ONTAP 9.3.

Este procedimento não é necessário se tiver recebido a configuração do MetroCluster de fábrica. Os nós da fábrica são configurados com pool 0 discos e agregados de raiz.

Esse procedimento só pode ser usado se você tiver pelo menos duas gavetas de disco para cada nó, o que permite a atribuição automática de discos no nível de compartimento. Se não for possível usar a atribuição automática no nível de compartimento, você deverá atribuir manualmente os discos locais para que cada nó tenha um pool local de discos (pool 0).

Estes passos têm de ser executados no modo de manutenção.

Os exemplos nesta seção assumem os seguintes compartimentos de disco:

* Node_A_1 possui discos em:
+
** Site_A-shelf_1 (local)
** Local_B-shelf_2 (remoto)


* O nó_A_2 está ligado a:
+
** Site_A-shelf_3 (local)
** Local_B-shelf_4 (remoto)


* O nó_B_1 está ligado a:
+
** Site_B-shelf_1 (local)
** Local_A-shelf_2 (remoto)


* O nó_B_2 está ligado a:
+
** Site_B-shelf_3 (local)
** Local_A-shelf_4 (remoto)




.Passos
. Atribua manualmente um único disco para agregado de raiz em cada nó:
+
`disk assign _disk-id_ -p 0 -s _local-node-sysid_`

+
A atribuição manual desses discos permite que o recurso de atribuição automática do ONTAP atribua o restante dos discos em cada compartimento.

+
.. No node_A_1, atribua manualmente um disco do local site_A-shelf_1 ao pool 0.
.. No node_A_2, atribua manualmente um disco do local site_A-shelf_3 ao pool 0.
.. No node_B_1, atribua manualmente um disco do local site_B-shelf_1 ao pool 0.
.. No node_B_2, atribua manualmente um disco do local site_B-shelf_3 ao pool 0.


. Inicialize cada nó no local A, usando a opção 4 no menu de inicialização:
+
Você deve concluir esta etapa em um nó antes de prosseguir para o próximo nó.

+
.. Sair do modo de manutenção:
+
`halt`

.. Apresentar o menu de arranque:
+
`boot_ontap menu`

.. Selecione a opção 4 no menu de inicialização e prossiga.


. Inicialize cada nó no local B, usando a opção 4 no menu de inicialização:
+
Você deve concluir esta etapa em um nó antes de prosseguir para o próximo nó.

+
.. Sair do modo de manutenção:
+
`halt`

.. Apresentar o menu de arranque:
+
`boot_ontap menu`

.. Selecione a opção 4 no menu de inicialização e prossiga.



