---
permalink: disaster-recovery/task_reassign_pool1_disastersite_mcip.html 
sidebar: sidebar 
keywords: metrocluster, disaster, site, replacement, controller, module, reassign, ownership 
summary: Se os módulos da controladora ou as placas NVRAM tiverem sido substituídos no local de desastre, você deverá reatribuir os discos pertencentes aos agregados raiz aos módulos da controladora de substituição. 
---
= Reatribuir a propriedade do disco para discos do pool 1 no local de desastre (configurações IP do MetroCluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se um ou ambos os módulos da controladora ou placas NVRAM tiverem sido substituídos no local de desastre, o ID do sistema foi alterado e você deve reatribuir discos pertencentes aos agregados raiz aos módulos da controladora de substituição.

.Sobre esta tarefa
Como os nós estão no modo de switchover, apenas os discos que contêm os agregados raiz de pool1 do local de desastre serão reatribuídos nesta tarefa. Eles são os únicos discos ainda possuídos pelo ID do sistema antigo neste momento.

Essa tarefa é realizada nos nós de substituição no local de desastre.

Esta tarefa é executada no modo Manutenção.

Os exemplos fazem as seguintes suposições:

* O local A é o local do desastre.
* O nó_A_1 foi substituído.
* O nó_A_2 foi substituído.
* O local B é o local sobrevivente.
* Node_B_1 está em bom estado.
* Node_B_2 está em bom estado.


Os IDs de sistema antigo e novo foram identificados no link:../disaster-recovery/task_replace_hardware_and_boot_new_controllers.html["Substitua o hardware e inicialize novos controladores"].

Os exemplos neste procedimento usam controladores com as seguintes IDs de sistema:

|===


| Nó | ID do sistema original | Nova ID do sistema 


 a| 
node_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
node_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
node_B_1
 a| 
4068741254
 a| 
inalterado



 a| 
node_B_2
 a| 
4068741256
 a| 
inalterado

|===
.Passos
. Com o nó de substituição no modo Manutenção, reatribua os discos agregados raiz, usando o comando correto, dependendo se o sistema está configurado com ADP e a versão do ONTAP.
+
Você pode prosseguir com a reatribuição quando solicitado.

+
|===


| Se o sistema estiver usando ADP... | Use este comando para reatribuição de disco... 


 a| 
Sim (ONTAP 9.8)
 a| 
`disk reassign -s old-system-ID -d new-system-ID -r dr-partner-system-ID`



 a| 
Sim (ONTAP 9.7.x e anterior)
 a| 
`disk reassign -s old-system-ID -d new-system-ID -p old-partner-system-ID`



 a| 
Não
 a| 
`disk reassign -s old-system-ID -d new-system-ID`

|===
+
O exemplo a seguir mostra a reatribuição de unidades em um sistema que não seja ADP:

+
[listing]
----
*> disk reassign -s 4068741256 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537037643.
Do you want to continue (y/n)? y
disk reassign parameters: new_home_owner_id 537070473 , new_home_owner_name
Disk 0m.i0.3L14 will be reassigned.
Disk 0m.i0.1L6 will be reassigned.
Disk 0m.i0.1L8 will be reassigned.
Number of disks to be reassigned: 3
----
. Destruir o conteúdo dos discos da caixa de correio:
+
`mailbox destroy local`

+
Você pode prosseguir com a operação destruir quando solicitado.

+
O exemplo a seguir mostra a saída para o comando local destruir caixa de correio:

+
[listing]
----
*> mailbox destroy local
Destroying mailboxes forces a node to create new empty mailboxes,
which clears any takeover state, removes all knowledge
of out-of-date plexes of mirrored volumes, and will prevent
management services from going online in 2-node cluster
HA configurations.
Are you sure you want to destroy the local mailboxes? y
...............Mailboxes destroyed.
*>
----
. Se os discos tiverem sido substituídos, haverá falha nos plexes locais que devem ser excluídos.
+
.. Exibir o status agregado:
+
`aggr status`

+
No exemplo a seguir, o Plex node_A_1_aggr0/plex0 falhou.

+
[listing]
----
*> aggr status
Aug 18 15:00:07 [node_B_1:raid.vol.mirror.degraded:ALERT]: Aggregate node_A_1_aggr0 is
   mirrored and one plex has failed. It is no longer protected by mirroring.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex0
   clean(-1), online(0)
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex2
   clean(0), online(1)
Aug 18 15:00:07 [node_B_1:raid.mirror.vote.noRecord1Plex:error]: WARNING: Only one plex
   in aggregate node_A_1_aggr0 is available. Aggregate might contain stale data.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: volobj_mark_sb_recovery_aggrs: tree:
   node_A_1_aggr0 vol_state:1 mcc_dr_opstate: unknown
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (VOL):
   raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (MIRROR):
   raid state change UNINITD -> DEGRADED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex0
   (PLEX): raid state change UNINITD -> FAILED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2
   (PLEX): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2/rg0
   (GROUP): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Topology updated for aggregate node_A_1_aggr0
   to plex plex2
*>
----
.. Eliminar o Plex com falha:
+
`aggr destroy plex-id`

+
[listing]
----
*> aggr destroy node_A_1_aggr0/plex0
----


. Interrompa o nó para exibir o prompt DO Loader:
+
`halt`

. Repita essas etapas no outro nó no local do desastre.

