---
permalink: disaster-recovery/task_config_switches_mcip.html 
sidebar: sidebar 
keywords: metrocluster, ip, configuration, switchback, operation 
summary: Você deve configurar todos os switches IP que foram substituídos. 
---
= Configurar os switches IP (configurações IP do MetroCluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar todos os switches IP que foram substituídos.

.Sobre esta tarefa
Esta tarefa aplica-se apenas às configurações IP do MetroCluster.

Isso deve ser feito em ambos os interrutores. Depois de configurar o primeiro switch, verifique se o acesso ao armazenamento no site sobrevivente não é afetado.


NOTE: Você não deve prosseguir com o segundo switch se o acesso ao armazenamento no site sobrevivente for afetado.

.Passos
. link:../install-ip/concept_considerations_differences.html["Instalação e configuração IP do MetroCluster: : Diferenças entre as configurações do ONTAP MetroCluster"]Consulte para obter os procedimentos de cabeamento e configuração de um switch de substituição.
+
Você pode usar os procedimentos nas seções a seguir:

+
** Cabeamento dos switches IP
** Configurar os switches IP


. Se os ISLs foram desativados no site sobrevivente, ative os ISLs e verifique se os ISLs estão online.
+
.. Ative as interfaces ISL no primeiro interrutor:
+
`no shutdown`

+
Os exemplos a seguir mostram os comandos de um switch IP Broadcom ou de um switch IP Cisco.

+
|===


| Fornecedor de switch | Comandos 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_1)> enable
(IP_switch_A_1)# configure
(IP_switch_A_1)(Config)# interface 0/13-0/16
(IP_switch_A_1)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_1)(Interface 0/13-0/16 )# exit
(IP_switch_A_1)(Config)# exit
----


 a| 
Cisco
 a| 
[listing]
----
IP_switch_A_1# conf t
IP_switch_A_1(config)# int eth1/15-eth1/20
IP_switch_A_1(config)# no shutdown
IP_switch_A_1(config)# copy running startup
IP_switch_A_1(config)# show interface brief
----
|===
.. Ative as interfaces ISL no switch parceiro:
+
`no shutdown`

+
Os exemplos a seguir mostram os comandos de um switch IP Broadcom ou de um switch IP Cisco.

+
|===


| Fornecedor de switch | Comandos 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_2)> enable
(IP_switch_A_2)# configure
(IP_switch_A_2)(Config)# interface 0/13-0/16
(IP_switch_A_2)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_2)(Interface 0/13-0/16 )# exit
(IP_switch_A_2)(Config)# exit
----


 a| 
Cisco
 a| 
[listing]
----
IP_switch_A_2# conf t
IP_switch_A_2(config)# int eth1/15-eth1/20
IP_switch_A_2(config)# no shutdown
IP_switch_A_2(config)# copy running startup
IP_switch_A_2(config)# show interface brief
----
|===
.. Verifique se as interfaces estão ativadas:
+
`show interface brief`

+
O exemplo a seguir mostra a saída de um switch Cisco.

+
[listing]
----
IP_switch_A_2(config)# show interface brief

--------------------------------------------------------
Port VRF Status IP Address Speed MTU
--------------------------------------------------------
mt0 -- up 10.10.99.10 100 1500
--------------------------------------------------------
Ethernet    VLAN Type Mode    Status Reason Speed   Port
Interface                                           Ch
#
--------------------------------------------------------
.
.
.
Eth1/15    10   eth   access  up     none   40G(D)  --
Eth1/16    10   eth   access  up     none   40G(D)  --
Eth1/17    10   eth   access  down   none   auto(D) --
Eth1/18    10   eth   access  down   none   auto(D) --
Eth1/19    10   eth   access  down   none   auto(D) --
Eth1/20    10   eth   access  down   none   auto(D) --
.
.
.
IP_switch_A_2#
----



