---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: A partir do ONTAP 9.13,1, você faz uma transição sem interrupções de workloads e dados de uma configuração MetroCluster FC de oito nós existente para uma nova configuração MetroCluster IP. 
---
= Transição de uma configuração IP do MetroCluster FC para uma configuração IP do MetroCluster sem interrupções (ONTAP 9.8 e posterior)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer transições sem interrupções de workloads e dados de uma configuração MetroCluster FC existente para uma nova configuração MetroCluster IP.

A partir do ONTAP 9.13,1, esse procedimento é compatível com configurações IP do MetroCluster nas quais o MetroCluster e os compartimentos de unidades são conetados aos mesmos switches IP (uma configuração de switch de armazenamento compartilhado).

A partir do ONTAP 9.13.1, você pode realizar uma transição não disruptiva de cargas de trabalho e dados de uma configuração MetroCluster FC existente de oito nós para uma nova configuração MetroCluster IP de oito nós.  Você utiliza esse procedimento para migrar um grupo FC DR de quatro nós, remover o grupo FC DR vazio e, em seguida, repetir o procedimento para o segundo grupo FC DR. 

A partir do ONTAP 9.8, você pode realizar uma transição não disruptiva de cargas de trabalho e dados de uma configuração MetroCluster FC existente de quatro nós para uma nova configuração MetroCluster IP de quatro nós.  Após concluir a transição, você poderá expandir para uma configuração IP MetroCluster de oito nós, se necessário. Verlink:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["Expanda uma configuração IP do MetroCluster"] .

* Esse procedimento não causa interrupções.
+
A configuração do MetroCluster pode continuar fornecendo dados durante a operação.

* Esse procedimento se aplica apenas a configurações de FC MetroCluster de quatro nós e oito nós.
+
Se você tiver uma configuração MetroCluster FC de dois nós, link:concept_choosing_your_transition_procedure_mcc_transition.html["Escolhendo seu procedimento de transição"]consulte .

* Este procedimento descreve as etapas necessárias para fazer a transição de um grupo de RD FC de quatro nós. Se você tiver uma configuração de oito nós (dois grupos de DR FC), repita todo o procedimento para cada grupo de DR FC.
+

NOTE: Ao adicionar ou remover um grupo de recuperação de desastres (DR) como parte deste procedimento, você deve verificar se a remoção ou adição do grupo de DR foi bem-sucedida antes de adicionar ou remover outro grupo de DR.

* Você deve atender a todos os requisitos e seguir todas as etapas do procedimento.


.Informações importantes se você estiver adicionando um modelo de plataforma mais antigo
A orientação a seguir é para um cenário incomum em que você precisa adicionar um modelo de plataforma mais antigo (plataformas lançadas antes do ONTAP 9.15.1) a uma configuração existente do MetroCluster que contém um modelo de plataforma mais recente (plataformas lançadas no ONTAP 9.15.1 ou posterior).  Para uma transição de FC para IP de oito nós, esta orientação se aplica se você tiver feito a transição do seu primeiro grupo de DR de FC para um modelo de plataforma introduzido no ONTAP 9.15.1 ou posterior e planeja fazer a transição do segundo grupo de DR para uma plataforma introduzida antes do ONTAP 9.15.1.

Se a sua configuração existente do MetroCluster contiver uma plataforma que usa *portas de cluster/HA compartilhadas* (plataformas lançadas no ONTAP 9.15.1 ou posterior), você não poderá adicionar uma plataforma que usa *portas de MetroCluster/HA compartilhadas* (plataformas lançadas antes do ONTAP 9.15.1) sem atualizar todos os nós na configuração para o ONTAP 9.15.1P11 ou ONTAP 9.16.1P4 ou posterior.

[CAUTION]
====
Adicionar um modelo de plataforma mais antigo que usa *portas HA compartilhadas/ do MetroCluster * a um MetroCluster que contém um modelo de plataforma mais novo que usa *portas HA/do cluster compartilhadas* é um cenário incomum e a maioria das combinações não é afetada.

====
Use a tabela a seguir para verificar se sua combinação é afetada.  Se sua plataforma existente estiver listada na primeira coluna e a plataforma que você deseja adicionar à configuração estiver listada na segunda coluna, todos os nós na configuração deverão estar executando o ONTAP 9.15.1P11 ou ONTAP 9.16.1P4 ou posterior para adicionar o novo grupo de DR.

[cols="20,20,20,20,20"]
|===
2+| Se o seu MetroCluster existente contiver... 2+| E a plataforma que você está adicionando é... | Então... 


 a| 
Um sistema AFF usando *portas de cluster/HA compartilhadas*:

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Um sistema FAS usando *portas de cluster/HA compartilhadas*:

* FAS50
* FAS70
* FAS90

 a| 
Um sistema AFF usando *portas MetroCluster/HA compartilhadas*:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Um sistema FAS usando *portas MetroCluster/HA compartilhadas*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Antes de adicionar a nova plataforma à sua configuração existente do MetroCluster, atualize todos os nós na configuração existente e nova para ONTAP 9.15.1P11 ou ONTAP 9.16.1P4 ou posterior. 
|===