---
permalink: upgrade/task_install_and_cable_the_new_controller.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, install, cable, new, controller, module 
summary: Você deve instalar fisicamente o novo módulo do controlador no chassi e, em seguida, fazer o cabo. 
---
= Instalação e cabeamento do novo módulo de controladora
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar fisicamente o novo módulo do controlador no chassi e, em seguida, fazer o cabo.

.Passos
. Se você tiver um módulo de expansão de e/S (IOXM) em seu sistema e estiver criando um par de HA de chassi único, será necessário desvincular e remover o IOXM.
+
Em seguida, você pode usar o compartimento vazio para o novo módulo do controlador. No entanto, a nova configuração não terá a e/S extra fornecida pelo IOXM.

. Instale fisicamente o novo módulo do controlador e, se necessário, instale ventoinhas adicionais:
+
|===


| Se você estiver adicionando um módulo de controlador... | Em seguida, execute estas etapas... 


 a| 
Para um compartimento vazio para criar um par de HA de chassi único e o sistema pertence a uma das seguintes plataformas:
 a| 
.. Remova a placa vazia na parte traseira do chassi que cobre o compartimento vazio que conterá o novo módulo do controlador.
.. Empurre cuidadosamente o módulo do controlador até meio para dentro do chassis.
+
Para evitar que o módulo do controlador inicialize automaticamente, não o coloque totalmente no chassis até mais tarde neste procedimento.





 a| 
Em um chassi separado de seu parceiro de HA para criar um par de HA de chassi duplo quando a configuração existente estiver em uma configuração de módulo IOX-controlador.

** FAS8200
** 80xx

 a| 
Instale o novo sistema no rack ou no gabinete do sistema.

|===
. Faça o cabeamento das conexões de rede do cluster, conforme necessário:
+
.. Identifique as portas no módulo do controlador para as ligações do cluster.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["Sistemas AFF A320: Instalação e configuração"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["Instruções de instalação e configuração dos sistemas AFF A220/FAS2700"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["Instruções de instalação e configuração de sistemas AFF A800"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["Instruções de instalação e configuração de sistemas AFF A300"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["Instruções de instalação e configuração de sistemas FAS8200"^]

.. Se você estiver configurando um cluster comutado, identifique as portas que você usará nos switches de rede do cluster.
+
Consulte https://library.netapp.com/ecm/ecm_get_file/ECMP1115327["Guia de configuração de switch Data ONTAP em cluster para switches Cisco"^] https://library.netapp.com/ecm/ecm_download_file/ECMP1117824["Guia de instalação do interrutor de modo de cluster do NetApp 10G"^] , ou https://library.netapp.com/ecm/ecm_download_file/ECMP1117853["Guia de instalação do comutador de modo de cluster do NetApp 1G"^], dependendo dos interrutores que estiver a utilizar.

.. Conete os cabos às portas do cluster:


+
|===


| Se o cluster for... | Então... 


 a| 
Um cluster sem switch de dois nós
 a| 
Conete diretamente as portas do cluster no módulo do controlador existente às portas do cluster correspondentes no novo módulo do controlador.



 a| 
Um cluster comutado
 a| 
Conete as portas do cluster em cada controlador às portas nos switches de rede do cluster identificados na subetapa b.

|===

