---
permalink: upgrade/task-enable-console-logging-expand-fc.html 
sidebar: sidebar 
keywords: enable, console, logging, devices, maintenance, autosupport, cli, 
summary: Ative o registo da consola nos seus dispositivos. 
---
= Ativar o registo da consola
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ative o registo da consola nos seus dispositivos antes de executar esta tarefa.

O NetApp recomenda fortemente que você ative o log do console nos dispositivos que você está usando e execute as seguintes ações ao executar este procedimento:

* Deixe o AutoSupport ativado durante a manutenção.
* Acione uma mensagem de manutenção do AutoSupport antes e depois da manutenção para desativar a criação de casos durante a atividade de manutenção.
+
Consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Como suprimir a criação automática de casos durante as janelas de manutenção programada"^].

* Ative o registo de sessão para qualquer sessão CLI. Para obter instruções sobre como ativar o registo de sessão, consulte a secção "saída de sessão de registo" no artigo da base de dados de conhecimento link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para uma conetividade ideal aos sistemas ONTAP"^].

