---
permalink: upgrade/task_send_a_custom_autosupport_message_before_add_nodes_to_the_mcc_configuration_2_node_to_4_node.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, send, custom, autosupport, message, add, nodes, configuration 
summary: Você deve emitir uma mensagem AutoSupport para notificar o suporte técnico da NetApp de que a manutenção está em andamento. Informar o suporte técnico de que a manutenção está em andamento impede que ele abra um caso partindo do pressuposto de que ocorreu uma interrupção. 
---
= Enviando uma mensagem AutoSupport personalizada antes de adicionar nós à configuração do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve emitir uma mensagem AutoSupport para notificar o suporte técnico da NetApp de que a manutenção está em andamento. Informar o suporte técnico de que a manutenção está em andamento impede que ele abra um caso partindo do pressuposto de que ocorreu uma interrupção.

.Sobre esta tarefa
Esta tarefa deve ser executada em cada site do MetroCluster.

.Passos
. Faça login no cluster em Site_A.
. Chame uma mensagem AutoSupport indicando o início da manutenção:
+
`system node autosupport invoke -node * -type all -message MAINT=__maintenance-window-in-hours__`

+
O `maintenance-window-in-hours` parâmetro especifica o comprimento da janela de manutenção e pode ser um máximo de 72 horas. Se concluir a manutenção antes do tempo decorrido, pode emitir o seguinte comando para indicar que o período de manutenção terminou:

+
`system node autosupport invoke -node * -type all -message MAINT=end`

. Repita esta etapa no site do parceiro.

