---
permalink: upgrade/task-expand-four-to-eight-mcc-fc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, mirrored, data, aggregate, node 
summary: Você precisa criar um agregado de dados espelhados em cada nó no grupo de DR. 
---
= Crie um agregado de dados espelhado em cada nó FC do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa criar um agregado de dados espelhados em cada nó no grupo de DR.

.Sobre esta tarefa
* Você deve saber quais unidades serão usadas no novo agregado.
* Se o seu sistema tiver vários tipos de unidades (storage heterogêneo), você deve entender como garantir que o tipo de unidade correto seja selecionado.
* As unidades são de propriedade de um nó específico; quando você cria um agregado, todas as unidades nesse agregado precisam ser de propriedade do mesmo nó, que se torna o nó inicial desse agregado.
+
Em sistemas que usam ADP, agregados são criados usando partições nas quais cada unidade é particionada em partições P1, P2 e P3.

* Os nomes agregados devem estar em conformidade com o esquema de nomenclatura que você determinou quando você planejou sua configuração do MetroCluster.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gerenciamento de disco e agregado"]

* Os nomes dos agregados devem ser únicos em todos os sites MetroCluster. Isso significa que você não pode ter dois agregados diferentes com o mesmo nome no site A e no site B.



NOTE: Recomenda-se manter pelo menos 20% de espaço livre em agregados espelhados para desempenho e disponibilidade ideais do armazenamento. Embora a recomendação seja de 10% para agregados não espelhados, os 10% adicionais de espaço podem ser usados pelo sistema de arquivos para absorver alterações incrementais. Alterações incrementais aumentam a utilização de espaço em agregados espelhados devido à arquitetura baseada em copy-on-write de Snapshot do ONTAP. O não cumprimento dessas melhores práticas pode ter um impacto negativo no desempenho.

.Passos
. Apresentar uma lista de peças sobresselentes disponíveis:
+
`storage disk show -spare -owner <node_name>`

. Criar o agregado:
+
`storage aggregate create -mirror true`

+
Se você estiver conectado ao cluster na interface de gerenciamento do cluster, poderá criar um agregado em qualquer nó do cluster. Para verificar se o agregado foi criado em um nó específico, use o  `-node` parâmetro ou especifique as unidades que pertencem a esse nó.

+
Você pode especificar as seguintes opções:

+
** Nó inicial do agregado (ou seja, o nó que possui o agregado em operação normal)
** Lista de unidades específicas que devem ser adicionadas ao agregado
** Número de unidades a incluir
+

NOTE: Na configuração mínima suportada, na qual um número limitado de unidades está disponível, você deve usar a opção force-small-Aggregate para permitir a criação de um agregado RAID-DP de três discos.

** Estilo de checksum para usar para o agregado
** Tipo de unidades a utilizar
** Tamanho das unidades a utilizar
** Velocidade de condução a utilizar
** Tipo RAID para grupos RAID no agregado
** Número máximo de unidades que podem ser incluídas em um grupo RAID
** Se unidades com RPM diferentes são permitidas
+
Para obter mais informações sobre essas opções, consulte a `storage aggregate create` página de manual.

+
O comando a seguir cria um agregado espelhado com 10 discos:

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. Verifique o grupo RAID e as unidades do seu novo agregado:
+
`storage aggregate show-status -aggregate <aggregate-name>`


