---
permalink: upgrade/task_install_licenses_on_the_new_controller_module_cluster_mode.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, install, license, new, controller, module 
summary: Você deve adicionar licenças para o novo módulo de controlador para quaisquer serviços ONTAP que exijam licenças padrão. Para recursos com licenças padrão, cada nó no cluster deve ter sua própria chave para o recurso. 
---
= Instalar licenças para o novo módulo de controlador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É necessário adicionar licenças para o novo módulo de controladora para quaisquer serviços ONTAP que exijam licenças padrão (node-locked). Para recursos com licenças padrão, cada nó no cluster deve ter sua própria chave para o recurso.

Para obter informações detalhadas sobre licenciamento, consulte o artigo 3013749 da base de conhecimento: Visão geral e referências de licenciamento do Data ONTAP 8.2 no site de suporte da NetApp e na _Referência de administração do sistema_.

.Passos
. Se necessário, obtenha chaves de licença para o novo nó no site de suporte da NetApp na seção meu suporte em licenças de software.
+
Para obter mais informações sobre substituições de licenças, consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system["Pós-processo de substituição da placa-mãe para atualizar o licenciamento em um sistema AFF/FAS."^]

. Execute o seguinte comando para instalar cada chave de licença:
+
`system license add -license-code _license_key_`

+
O `_license_key_` tem 28 dígitos de comprimento.

. Repita este passo para cada licença padrão (node-locked) necessária.

