---
permalink: upgrade/task_verify_that_the_ha_state_of_components_is_mcc_dr_smok_crater_or_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, verify, ha, config, component, state 
summary: Em uma configuração MetroCluster, o estado ha-config do módulo do controlador e dos componentes do chassi deve ser definido como mcc para que eles iniciem corretamente. 
---
= Verificando o estado ha-config dos componentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em uma configuração MetroCluster, o estado ha-config do módulo do controlador e dos componentes do chassi deve ser definido como *mcc* para que eles iniciem corretamente.

.Sobre esta tarefa
* O sistema tem de estar no modo de manutenção.
* Esta tarefa deve ser executada em cada novo módulo do controlador.


.Passos
. No modo de manutenção, apresentar o estado HA do módulo do controlador e do chassis:
+
`ha-config show`

+
O estado de HA para todos os componentes deve ser "mcc".

. Se o estado do sistema apresentado do controlador não estiver correto, defina o estado HA para o módulo do controlador:
+
`ha-config modify controller mcc`

. Se o estado do sistema apresentado do chassis não estiver correto, defina o estado HA para o chassis:
+
`ha-config modify chassis mcc`

. Repita estas etapas no outro nó de substituição.

