---
permalink: upgrade/task-configure-intercluster-lifs-4node.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, dedicated, ports, shared 
summary: Você pode configurar LIFs entre clusters em portas dedicadas ou compartilhadas. 
---
= Configurar LIFs entre clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba como configurar LIFs entre clusters em portas dedicadas e compartilhadas.

[role="tabbed-block"]
====
.Configurar LIFs entre clusters em portas dedicadas
--
Você pode configurar LIFs entre clusters em portas dedicadas para aumentar a largura de banda disponível para tráfego de replicação.

.Passos
. Liste as portas no cluster:
+
`network port show`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra as portas de rede no cluster01:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. Determine quais portas estão disponíveis para se dedicar à comunicação entre clusters:
+
`network interface show -fields home-port,curr-port`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra que as portas "e0e" e "e0f" não foram atribuídas LIFs:

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01-01_clus1   e0a       e0a
Cluster cluster01-01_clus2   e0b       e0b
Cluster cluster01-02_clus1   e0a       e0a
Cluster cluster01-02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. Crie um grupo de failover para as portas dedicadas:
+
`network interface failover-groups create -vserver <system_SVM> -failover-group <failover_group> -targets <physical_or_logical_ports>`

+
O exemplo a seguir atribui as portas "e0e" e "e0f" ao grupo de failover "intercluster01" no SVM do sistema "cluster01":

+
[listing]
----
cluster01::> network interface failover-groups create -vserver cluster01 -failover-group
intercluster01 -targets
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. Verifique se o grupo de failover foi criado:
+
`network interface failover-groups show`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
[listing]
----
cluster01::> network interface failover-groups show
                                  Failover
Vserver          Group            Targets
---------------- ---------------- --------------------------------------------
Cluster
                 Cluster
                                  cluster01-01:e0a, cluster01-01:e0b,
                                  cluster01-02:e0a, cluster01-02:e0b
cluster01
                 Default
                                  cluster01-01:e0c, cluster01-01:e0d,
                                  cluster01-02:e0c, cluster01-02:e0d,
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
                 intercluster01
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
----
. Crie LIFs entre clusters no sistema e atribua-os ao grupo de failover.
+
[cols="1,3"]
|===


| Versão de ONTAP | Comando 


 a| 
9,6 e mais tarde
 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`



 a| 
9,5 e anteriores
 a| 
`network interface create -vserver system_SVM -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir cria LIFs entre clusters "cluster01_icl01" e "cluster01_icl02" no grupo de failover "intercluster01":

+
[listing]
----
cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0 -failover-group intercluster01

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0 -failover-group intercluster01
----
. Verifique se as LIFs entre clusters foram criadas:
+
|===


| *Em ONTAP 9.6 e posteriores:* 


 a| 
`network interface show -service-policy default-intercluster`



| *Em ONTAP 9.5 e anteriores:* 


 a| 
`network interface show -role intercluster`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. Verifique se as LIFs entre clusters são redundantes:
+
|===


| *Em ONTAP 9.6 e posteriores:* 


 a| 
`network interface show -service-policy default-intercluster -failover`



| *Em ONTAP 9.5 e anteriores:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra que os LIFs entre clusters "cluster01_icl01" e "cluster01_icl02" na porta SVM "e0e" falharão para a porta "e0f".

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----


--
.Configurar LIFs entre clusters em portas de dados compartilhados
--
Você pode configurar LIFs entre clusters em portas compartilhadas com a rede de dados para reduzir o número de portas necessárias para a rede entre clusters.

.Passos
. Liste as portas no cluster:
+
`network port show`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra as portas de rede no cluster01:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. Criar LIFs entre clusters no sistema:
+
|===


| *Em ONTAP 9.6 e posteriores:* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`



| *Em ONTAP 9.5 e anteriores:* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir cria LIFs entre clusters `cluster01_icl01` e `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. Verifique se as LIFs entre clusters foram criadas:
+
|===


| *Em ONTAP 9.6 e posteriores:* 


 a| 
`network interface show -service-policy default-intercluster`



| *Em ONTAP 9.5 e anteriores:* 


 a| 
`network interface show -role intercluster`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Verifique se as LIFs entre clusters são redundantes:
+
|===


| *Em ONTAP 9.6 e posteriores:* 


 a| 
`network interface show –service-policy default-intercluster -failover`



| *Em ONTAP 9.5 e anteriores:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra que os LIFs entre clusters "cluster01_icl01" e "cluster01_icl02" na porta "e0c" falharão para a porta "e0d".

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----


--
====