---
permalink: upgrade/upgrade-mcc-ip-manual-reassign-root-agg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Reatribua os discos agregados de raiz ao novo módulo de controladora, usando as IDs de sistema que você coletou anteriormente. 
---
= Reatribua os discos agregados raiz ao novo módulo de controladora IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reatribua os discos agregados de raiz ao novo módulo de controladora usando as IDs de sistema que você coletou anteriormente.

.Sobre esta tarefa
As IDs de sistema antigas foram identificadas no link:upgrade-mcc-ip-prepare-system.html#gather-information-before-the-upgrade["Reúna informações antes da atualização"].

Execute os passos no modo Manutenção.


NOTE: Os discos agregados de raiz são os únicos discos que devem ser reatribuídos durante o processo de atualização da controladora. A propriedade de disco de agregados de dados é tratada como parte da operação de comutação/switchback.

.Passos
. Inicialize o sistema no modo de manutenção:
+
`boot_ontap maint`

. Exiba os discos no node_B_1-novo no prompt do modo de manutenção:
+
`disk show -a`

+

CAUTION: Antes de prosseguir com a reatribuição de disco, verifique se os discos pool0 e pool1 que pertencem ao agregado raiz do nó são exibidos na `disk show` saída. No exemplo a seguir, a saída lista os discos pool0 e pool1 de propriedade do node_B_1-old.

+
A saída do comando mostra a ID do sistema do novo módulo do controlador (1574774970). No entanto, o ID do sistema antigo (537403322) ainda possui os discos agregados raiz. Este exemplo não mostra unidades de propriedade de outros nós na configuração do MetroCluster.

+
[listing]
----
*> disk show -a
Local System ID: 1574774970
DISK                  OWNER                 POOL   SERIAL NUMBER   HOME                  DR HOME
------------          ---------             -----  -------------   -------------         -------------
prod3-rk18:9.126L44   node_B_1-old(537403322)  Pool1  PZHYN0MD     node_B_1-old(537403322)  node_B_1-old(537403322)
prod4-rk18:9.126L49   node_B_1-old(537403322)  Pool1  PPG3J5HA     node_B_1-old(537403322)  node_B_1-old(537403322)
prod4-rk18:8.126L21   node_B_1-old(537403322)  Pool1  PZHTDSZD     node_B_1-old(537403322)  node_B_1-old(537403322)
prod2-rk18:8.126L2    node_B_1-old(537403322)  Pool0  S0M1J2CF     node_B_1-old(537403322)  node_B_1-old(537403322)
prod2-rk18:8.126L3    node_B_1-old(537403322)  Pool0  S0M0CQM5     node_B_1-old(537403322)  node_B_1-old(537403322)
prod1-rk18:9.126L27   node_B_1-old(537403322)  Pool0  S0M1PSDW     node_B_1-old(537403322)  node_B_1-old(537403322)
.
.
.
----
. Reatribua os discos agregados de raiz nos compartimentos de unidades às novas controladoras.
+
|===


| Se você estiver usando ADP... | Em seguida, use este comando... 


 a| 
Sim
 a| 
`disk reassign -s <old-sysid> -d <new-sysid> -r <dr-partner-sysid>`



 a| 
Não
 a| 
`disk reassign -s <old-sysid> -d <new-sysid>`

|===
. Reatribua os discos agregados de raiz nos compartimentos de unidades às novas controladoras:
+
`disk reassign -s <old-sysid> -d <new-sysid>`

+
O exemplo a seguir mostra a reatribuição de unidades em uma configuração não ADP:

+
[listing]
----
*> disk reassign -s 537403322 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537403322.
Do you want to continue (y/n)? y
----
. Verifique se os discos do agregado raiz estão corretamente reatribuídos:
+
`disk show`

+
`storage aggr status`

+
[listing]
----

*> disk show
Local System ID: 537097247

  DISK                    OWNER                    POOL   SERIAL NUMBER   HOME                     DR HOME
------------              -------------            -----  -------------   -------------            -------------
prod03-rk18:8.126L18 node_B_1-new(537097247)  Pool1  PZHYN0MD        node_B_1-new(537097247)   node_B_1-new(537097247)
prod04-rk18:9.126L49 node_B_1-new(537097247)  Pool1  PPG3J5HA        node_B_1-new(537097247)   node_B_1-new(537097247)
prod04-rk18:8.126L21 node_B_1-new(537097247)  Pool1  PZHTDSZD        node_B_1-new(537097247)   node_B_1-new(537097247)
prod02-rk18:8.126L2  node_B_1-new(537097247)  Pool0  S0M1J2CF        node_B_1-new(537097247)   node_B_1-new(537097247)
prod02-rk18:9.126L29 node_B_1-new(537097247)  Pool0  S0M0CQM5        node_B_1-new(537097247)   node_B_1-new(537097247)
prod01-rk18:8.126L1  node_B_1-new(537097247)  Pool0  S0M1PSDW        node_B_1-new(537097247)   node_B_1-new(537097247)
::>
::> aggr status
           Aggr          State           Status                Options
aggr0_node_B_1           online          raid_dp, aggr         root, nosnap=on,
                                         mirrored              mirror_resync_priority=high(fixed)
                                         fast zeroed
                                         64-bit
----


.O que se segue?
link:upgrade-mcc-ip-manual-boot-new-controllers.html["Inicialize os novos controladores e restaure a configuração de LIF"].
