---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: As atualizações para sistemas introduzidos no ONTAP 9.15.1 ou posterior exigem que você defina um bootarg antes que você possa prosseguir com a atualização. 
---
= Defina o bootarg necessário (para atualizações MetroCluster IP para sistemas introduzidos no ONTAP 9.15.1 ou posterior)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver atualizando para um sistema introduzido no ONTAP 9.15.1 ou posterior, normalmente será necessário definir um bootarg nos controladores antigos antes de iniciar a atualização.


NOTE: Se sua combinação de atualização for afetada, será necessário definir um bootarg em todos os controladores antigos para uma atualização bem-sucedida.  Revise as informações nesta seção cuidadosamente para verificar se sua combinação de atualização exige que você defina um bootarg e como definir o bootarg correto para sua combinação.



== Etapa 1: determine se você precisa definir um bootarg nos controladores antigos

Antes de iniciar a atualização, determine se você precisa definir um bootarg nos controladores antigos usando as seguintes informações:

* Você *deve* definir um bootarg nos controladores antigos para atualizações suportadas nos seguintes sistemas, a menos que seja indicado o contrário:
+
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60
** FAS50


* Você *não* precisa definir nenhum bootarg nos controladores antigos se sua atualização for uma das seguintes combinações:
+
** De um sistema AFF A70 para um sistema AFF A90
** De um sistema FAS70 para um sistema FAS90





CAUTION: Se a sua atualização não exigir que você defina nenhum bootarg, você pode ignorar esta tarefa e ir diretamente para link:upgrade-mcc-ip-system-controller-replace-prechecks.html["Prepare o sistema para a atualização"].



== Etapa 2: determine o bootarg que você precisa definir nos controladores antigos

As atualizações mais afetadas exigem que você defina o `hw.cxgbe.toe_keepalive_disable` bootarg nos controladores antigos.  No entanto, certos caminhos de atualização exigem que você defina o `bootarg.siw.interop_enabled` bootarg em vez disso.

Use a tabela a seguir para determinar qual bootarg você precisa definir para sua combinação de atualização específica.

[cols="2*"]
|===
| Para esta atualização... | Jogos de Bicicleta de monta... 


| De AFF A250 a AFF A30 | `bootarg.siw.interop_enabled` 


| De AFF C250 a AFF C30 | `bootarg.siw.interop_enabled` 


| De AFF A150 a AFF A20 | `bootarg.siw.interop_enabled` 


| De AFF A220 a AFF A20 | `bootarg.siw.interop_enabled` 


 a| 
Todas as outras atualizações para os sistemas AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A30, AFF C30, AFF C60 ou FAS50

*Observação:* você não precisa definir nenhum bootarg se sua atualização for de um sistema AFF A70 para um AFF A90 ou de um sistema FAS70 para um FAS90.
| `hw.cxgbe.toe_keepalive_disable` 
|===


== Etapa 3: defina o bootarg necessário nos controladores antigos

Depois de determinar o bootarg necessário para sua combinação de atualização, siga os passos para definir o bootarg nos controladores antigos.


NOTE: Você deve definir o bootarg em todos os nós antigos em ambos os sites antes de iniciar a atualização.

.Passos
. Parar um nó em ambos os locais e permitir que seu parceiro de HA faça um takeover do nó:
+
`halt  -node <node_name>`

. Defina o bootarg necessário para sua combinação de upgrade. Você já determinou o bootarg que precisa definir usando a tabela no <<upgrade_paths_bootarg_assisted,determine qual bootarg você precisa definir>>.
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
.. No `LOADER` prompt do nó interrompido, digite o seguinte:
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
`saveenv`

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. No `LOADER` prompt do nó interrompido, digite o seguinte:
+
`setenv bootarg.siw.interop_enabled 1`

+
`saveenv`

+
`printenv bootarg.siw.interop_enabled`



--
====
. Inicialize o nó:
+
`boot_ontap`

. Quando o nó for inicializado, execute um giveback para o nó no prompt:
+
`storage failover giveback -ofnode <node_name>`

. Repita as etapas em todos os quatro nós no grupo de DR que você está atualizando.


.O que vem a seguir
link:upgrade-mcc-ip-system-controller-replace-prechecks.html["Prepare o sistema para a atualização"].
