---
permalink: tiebreaker/concept-mcc-tiebreaker-event-logs.html 
sidebar: sidebar 
keywords: metrocluster, tiebreaker, actions, events, event, log files, files, logs, file 
summary: As atividades do MetroCluster Tiebreaker são registradas em arquivos de log de eventos. 
---
= Arquivos de log de eventos para MetroCluster tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O arquivo de log de eventos contém um log de todas as ações executadas pelo software tiebreaker do MetroCluster.

O software tiebreaker executa as seguintes ações:

* Detecta desastres no local
* Detecta alterações de configuração relacionadas ao banco de dados, a outros monitores tiebreaker ou ao software tiebreaker MetroCluster
* Detecta conexões SSH e desconexões
* Descobre configurações do MetroCluster


Essas ações são registradas no arquivo de log de eventos no seguinte formato:

<timestamp> (gravidade/nível de registo)> <thread-id> <module>

....
2022-09-07 06:14:30,797 INFO  [MCCTBCommandServer-16] [SslSupport] Successfully initiated SSL context. Protocol used is TLSv1.3.
2022-09-07 06:14:34,137 INFO  [MCCTBCommandServer-16] [DataBase] Successfully read MCCTB database.
2022-09-07 06:14:34,137 INFO  [MCCTBCommandServer-16] [ConfigurationMonitor] Debug mode disabled.
....