---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: Após a instalação do software tiebreaker, você pode adicionar ou modificar configurações do MetroCluster ou removê-las do software tiebreaker. 
---
= Configure o software MetroCluster Tiebreaker.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após a instalação do software tiebreaker, você pode adicionar ou modificar configurações do MetroCluster ou removê-las do software tiebreaker.



== Inicie a linha de comando do software Tiebreaker

Depois de instalar o software tiebreaker, você deve iniciar sua CLI para configurar o software.

. Inicie a CLI a partir do prompt do host no qual você instalou o software:
+
`netapp-metrocluster-tiebreaker-software-cli`

. Após a instalação e durante a primeira inicialização, digite a senha para o usuário tiebreaker acessar o banco de dados. Esta é a senha que você especificou para o usuário do banco de dados durante a instalação.




== Adicione configurações do MetroCluster

Depois de instalar o software tiebreaker do NetApp MetroCluster, você pode adicionar mais configurações do MetroCluster, uma de cada vez.

.Sobre esta tarefa
* Você deve ter instalado a configuração do MetroCluster em um ambiente ONTAP e ativado as configurações no software.
* Os passos e o resultado esperado do comando dependem da versão do Tiebreaker que você está executando.


[role="tabbed-block"]
====
.Tiebreaker 1.5 ou anterior
--
.Passos
. Use o comando add do monitor da interface de linha de comando (CLI) tiebreaker para adicionar configurações do MetroCluster.
+
Se você estiver usando o nome do host, ele deve ser o nome de domínio totalmente qualificado (FQDN).

+
O exemplo a seguir mostra a configuração de cluster_A:

+
.Exemplo
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. Confirme se a configuração do MetroCluster foi adicionada corretamente usando o comando tiebreaker CLI `monitor show -status`.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Desative o modo observador para que o software tiebreaker inicie automaticamente um switchover após detetar uma falha no local:
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.Tiebreaker 1,6 ou posterior
--
.Passos
. Use o comando add do monitor da interface de linha de comando (CLI) tiebreaker para adicionar configurações do MetroCluster.
+
Se você estiver usando o nome do host, ele deve ser o nome de domínio totalmente qualificado (FQDN).

+
O exemplo a seguir mostra a configuração de cluster_A:

+
.Exemplo
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. Confirme se a configuração do MetroCluster foi adicionada corretamente usando o comando tiebreaker CLI `monitor show -status`.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Importe os certificados ausentes seguindo os passos correspondentes à sua versão do Tiebreaker em<<import-certificates-tb17,Certificados de importação>> .


--
====
.Informações relacionadas
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["Riscos e limitações do uso do MetroCluster Tiebreaker no modo ativo"]



== Certificados de importação

Para habilitar o monitoramento contínuo no Tiebreaker 1.6 ou posterior, você precisa importar o certificado Secure Sockets Layer (SSL) do servidor, o certificado intermediário (se houver) e o certificado raiz do ONTAP para o armazenamento de chaves na Máquina Virtual Java (JVM).

.Sobre esta tarefa
* Esta tarefa é necessária no Tiebreaker 1.6 ou posterior.
* Você executa essa tarefa depois de adicionar com sucesso uma configuração do MetroCluster ao Tiebreaker ou se seus certificados expirarem.
* No Tiebreaker 1.7 ou posterior, você pode realizar uma simulação de transição para verificar se precisa importar um certificado.  Se a simulação de troca de servidor falhar, você precisará importar os certificados do ONTAP para o armazenamento de chaves na Máquina Virtual Java (JVM).


[role="tabbed-block"]
====
.Tiebreaker 1.7 ou posterior
--
.Passos
. Execute uma simulação de transição para verificar se é necessário importar certificados.
+
.. Verifique o status de monitoramento do Tiebreaker:
`monitor show -status`
+
.Exemplo
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Acione uma simulação de transição:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
O comando retorna a seguinte saída caso seja necessário importar certificados para a JVM:

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. Execute o seguinte comando para cada certificado que você precisa importar (servidor SSL, intermediário ou raiz).
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** O `<certificate_file_name>` O valor especifica o nome do arquivo do certificado que você deseja importar.
** O `-alias <certificate>` O valor especifica o nome que você deseja usar para armazenar o certificado depois que ele for importado para a JVM.
+
O exemplo a seguir mostra como importar um certificado raiz com o nome do arquivo. `root.crt` e um certificado de servidor SSL com o nome do arquivo `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Reinicie o software Tiebreaker:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. Execute novamente as verificações de simulação de comutação:
+
.. Verifique o status de monitoramento do Tiebreaker:
`monitor show -status`
+
.Exemplo
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Acione uma simulação de transição:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.Desempate 1.6 ou 1.6P1
--
.Passos
. Importe todos os certificados do ONTAP. Execute o seguinte comando para cada certificado que você precisa importar (servidor SSL, intermediário ou raiz).
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** O `<certificate_file_name>` O valor especifica o nome do arquivo do certificado que você deseja importar.
** O `-alias <certificate>` O valor especifica o nome que você deseja usar para armazenar o certificado depois que ele for importado para a JVM.
+
O exemplo a seguir mostra como importar um certificado raiz com o nome do arquivo. `root.crt` e um certificado de servidor SSL com o nome do arquivo `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Reinicie o software Tiebreaker:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== Comandos para modificar configurações do MetroCluster tiebreaker

Você pode modificar a configuração do MetroCluster sempre que precisar alterar as configurações.

O comando tiebreaker CLI monitor Modify pode ser usado com qualquer uma das seguintes opções. Você pode confirmar suas alterações com o comando monitor show -status.

[cols="30,70"]
|===


| Opção | Descrição 


 a| 
-monitor-name
 a| 
Nome da configuração do MetroCluster



 a| 
-enable-monitor
 a| 
Ativa e desativa a monitorização da configuração do MetroCluster



 a| 
-período silencioso
 a| 
Período em segundos pelo qual o software tiebreaker do MetroCluster aguarda para confirmar uma falha do local após a deteção



 a| 
-modo observador
 a| 
O modo observador (verdadeiro) fornece apenas monitoramento e não aciona um switchover se ocorrer um desastre no local. O modo online (false) aciona um switchover se ocorrer um desastre no local.

* link:concept_overview_of_the_tiebreaker_software.html["Como o software tiebreaker deteta falha no local"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["Riscos e limitações do uso do MetroCluster Tiebreaker no modo ativo"]


|===
O exemplo a seguir altera o período silencioso para a configuração.

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
O comando tiebreaker CLI `debug` pode ser usado para alterar o modo de Registro.

[cols="30,70"]
|===


| Comando | Descrição 


 a| 
status de depuração
 a| 
Exibe o status do modo de depuração



 a| 
ativar depuração
 a| 
Ativa o modo de depuração para o registo



 a| 
desativar depuração
 a| 
Desativa o modo de depuração para o registo

|===
Em sistemas que executam o tiebreaker 1,4 e anteriores, o comando tiebreaker CLI `update-mcctb-password` pode ser usado para atualizar a senha do usuário. Este comando está obsoleto no tiebreaker 1,5 e posterior.

[cols="30,70"]
|===


| Comando | Descrição 


 a| 
update-mcctb-password
 a| 
A palavra-passe do utilizador foi atualizada com êxito

|===


== Remover configurações do MetroCluster

Você pode remover a configuração do MetroCluster que está sendo monitorada pelo software tiebreaker quando não quiser mais monitorar uma configuração do MetroCluster.

. Use o comando tiebreaker CLI `monitor remove` para remover a configuração do MetroCluster.
+
No exemplo a seguir, "'cluster_A" é removido do software:

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. Confirme se a configuração do MetroCluster foi removida corretamente usando o comando tiebreaker CLI `monitor show -status`.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

