---
permalink: tiebreaker/install_dependencies.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: O software tiebreaker 1,5 fornece recursos de monitoramento para um ambiente de storage em cluster. Ele também envia notificações SNMP em caso de problemas de conetividade de nó e desastres de site. 
---
= Instale dependências do MetroCluster tiebreaker 1,5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dependendo do sistema operacional Linux host, você deve instalar um servidor MySQL ou MariaDB antes de instalar ou atualizar o software tiebreaker.

.Passos
. <<install-java-17,Instale o JDK>>
. <<install-vault,Instale e configure o Vault>>
. Instale o servidor MySQL ou MariaDB:
+
[cols="30,70"]
|===


| Se o host Linux for | Então... 


 a| 
Red Hat Enterprise Linux 7/CentOS 7
 a| 
<<install-mysql-redhat,Instale as versões do MySQL Server 5.5.30 ou posterior e 5,6.x no Red Hat Enterprise Linux 7 ou CentOS 7>>



 a| 
Red Hat Enterprise Linux 8
 a| 
<<install-mariadb,Instale o servidor MariaDB no Red Hat Enterprise Linux 8>>

|===




== Instale o JDK

Você deve instalar o JDK em seu sistema host antes de instalar ou atualizar o software tiebreaker. Tiebreaker 1,5 e posterior suporta OpenJDK 17, 18 ou 19.

.Passos
. Faça login como um usuário "root" ou um usuário sudo que pode mudar para o modo de privilégio avançado.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. Verifique as versões disponíveis do JDK:
+
`yum search openjdk`

. Instale o JDK 17,18 ou 19.
+
O seguinte comando instala o JDK 17:

+
`yum install java-17-openjdk`

. Verifique a instalação:
+
`java -version`

+
Uma instalação bem-sucedida exibe a seguinte saída:

+
[listing]
----

openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment 21.9 (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM 21.9 (build 17.0.2+8-LTS, mixed mode, sharing)
----




== Instale e configure o Vault

Se você não tiver ou quiser usar o servidor local do Vault, você deve instalar o Vault. Você pode consultar este procedimento padrão para instalar o Vault ou consultar as instruções de instalação do Hashicorp para obter diretrizes alternativas.


NOTE: Se você tiver um servidor do Vault na rede, poderá configurar o host do MetroCluster Tiebreaker para usar essa instalação do Vault. Se você fizer isso, não precisará instalar o Vault no host.

.Passos
. Navegue até o `/bin` diretório:
+
[listing]
----
[root@mcctb] cd /bin
----
. Baixe o arquivo zip do Vault.
+
[listing]
----
[root@mcctb /bin]#  curl -sO https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip
----
. Descompacte o arquivo Vault.
+
[listing]
----
[root@mcctb /bin]# unzip vault_1.12.2_linux_amd64.zip
Archive:  vault_1.12.2_linux_amd64.zip
  inflating: vault
----
. Verifique a instalação.
+
[listing]
----
[root@mcctb /bin]# vault -version
Vault v1.12.2 (415e1fe3118eebd5df6cb60d13defdc01aa17b03), built 2022-11-23T12:53:46Z
----
. Navegue até o `/root` diretório:
+
[listing]
----
[root@mcctb /bin] cd /root
----
. Crie um arquivo de configuração do Vault sob o `/root` diretório.
+
 `[root@mcctb ~]`No prompt, copie e execute o seguinte comando para criar o `config.hcl` arquivo:

+
[source, cli]
----
# cat > config.hcl << EOF
 storage "file" {
  address = "127.0.0.1:8500"
  path    = "/mcctb_vdata/data"
 }
 listener "tcp" {
   address     = "127.0.0.1:8200"
   tls_disable = 1
 }
EOF
----
. Inicie o servidor Vault:
+
[listing]
----
[root@mcctb ~] vault server -config config.hcl &
----
. Exporte o endereço do Vault.
+
[listing]
----
[root@mcctb ~]# export VAULT_ADDR="http://127.0.0.1:8200"
----
. Inicialize o Vault.
+
[listing]
----
[root@mcctb ~]# vault operator init
2022-12-15T14:57:22.113+0530 [INFO]  core: security barrier not initialized
2022-12-15T14:57:22.113+0530 [INFO]  core: seal configuration missing, not initialized
2022-12-15T14:57:22.114+0530 [INFO]  core: security barrier not initialized
2022-12-15T14:57:22.116+0530 [INFO]  core: security barrier initialized: stored=1 shares=5 threshold=3
2022-12-15T14:57:22.118+0530 [INFO]  core: post-unseal setup starting
2022-12-15T14:57:22.137+0530 [INFO]  core: loaded wrapping token key
2022-12-15T14:57:22.137+0530 [INFO]  core: Recorded vault version: vault version=1.12.2 upgrade time="2022-12-15 09:27:22.137200412 +0000 UTC" build date=2022-11-23T12:53:46Z
2022-12-15T14:57:22.137+0530 [INFO]  core: successfully setup plugin catalog: plugin-directory=""
2022-12-15T14:57:22.137+0530 [INFO]  core: no mounts; adding default mount table
2022-12-15T14:57:22.143+0530 [INFO]  core: successfully mounted backend: type=cubbyhole version="" path=cubbyhole/
2022-12-15T14:57:22.144+0530 [INFO]  core: successfully mounted backend: type=system version="" path=sys/
2022-12-15T14:57:22.144+0530 [INFO]  core: successfully mounted backend: type=identity version="" path=identity/
2022-12-15T14:57:22.148+0530 [INFO]  core: successfully enabled credential backend: type=token version="" path=token/ namespace="ID: root. Path: "
2022-12-15T14:57:22.149+0530 [INFO]  rollback: starting rollback manager
2022-12-15T14:57:22.149+0530 [INFO]  core: restoring leases
2022-12-15T14:57:22.150+0530 [INFO]  expiration: lease restore complete
2022-12-15T14:57:22.150+0530 [INFO]  identity: entities restored
2022-12-15T14:57:22.150+0530 [INFO]  identity: groups restored
2022-12-15T14:57:22.151+0530 [INFO]  core: usage gauge collection is disabled
2022-12-15T14:57:23.385+0530 [INFO]  core: post-unseal setup complete
2022-12-15T14:57:23.387+0530 [INFO]  core: root token generated
2022-12-15T14:57:23.387+0530 [INFO]  core: pre-seal teardown starting
2022-12-15T14:57:23.387+0530 [INFO]  rollback: stopping rollback manager
2022-12-15T14:57:23.387+0530 [INFO]  core: pre-seal teardown complete
Unseal Key 1: <unseal_key_1_id>
Unseal Key 2: <unseal_key_2_id>
Unseal Key 3: <unseal_key_3_id>
Unseal Key 4: <unseal_key_4_id>
Unseal Key 5: <unseal_key_5_id>

Initial Root Token: <initial_root_token_id>


Vault initialized with 5 key shares and a key threshold of 3. Please securely
distribute the key shares printed above. When the Vault is re-sealed,
restarted, or stopped, you must supply at least 3 of these keys to unseal it
before it can start servicing requests.

Vault does not store the generated root key. Without at least 3 keys to
reconstruct the root key, Vault will remain permanently sealed!

It is possible to generate new unseal keys, provided you have a quorum of
existing unseal keys shares. See "vault operator rekey" for more information.
----
+

IMPORTANT: Você deve gravar e armazenar os IDs de chave e o token de raiz inicial em um local seguro para uso posterior no procedimento.

. Exporte o token raiz do Vault.
+
[listing]
----
[root@mcctb ~]#  export VAULT_TOKEN="<initial_root_token_id>"
----
. Desprenda o Vault usando quaisquer três das cinco chaves que foram criadas.
+
Você deve executar o `vault operator unseal` comando para cada uma das três chaves:

+
.. Retire o Vault usando a primeira chave:
+
[listing]
----
[root@mcctb ~]# vault operator unseal
Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    1/3
Unseal Nonce       <unseal_key_1_id>
Version            1.12.2
Build Date         2022-11-23T12:53:46Z
Storage Type       file
HA Enabled         false
----
.. Retire o Vault usando a segunda chave:
+
[listing]
----
[root@mcctb ~]# vault operator unseal
Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    2/3
Unseal Nonce       <unseal_key_2_id>
Version            1.12.2
Build Date         2022-11-23T12:53:46Z
Storage Type       file
HA Enabled         false
----
.. Retire o Vault usando a terceira chave:
+
[listing]
----
[root@mcctb ~]# vault operator unseal
Unseal Key (will be hidden):
2022-12-15T15:15:00.980+0530 [INFO]  core.cluster-listener.tcp: starting listener: listener_address=127.0.0.1:8201
2022-12-15T15:15:00.980+0530 [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2022-12-15T15:15:00.981+0530 [INFO]  core: post-unseal setup starting
2022-12-15T15:15:00.981+0530 [INFO]  core: loaded wrapping token key
2022-12-15T15:15:00.982+0530 [INFO]  core: successfully setup plugin catalog: plugin-directory=""
2022-12-15T15:15:00.983+0530 [INFO]  core: successfully mounted backend: type=system version="" path=sys/
2022-12-15T15:15:00.984+0530 [INFO]  core: successfully mounted backend: type=identity version="" path=identity/
2022-12-15T15:15:00.984+0530 [INFO]  core: successfully mounted backend: type=cubbyhole version="" path=cubbyhole/
2022-12-15T15:15:00.986+0530 [INFO]  core: successfully enabled credential backend: type=token version="" path=token/ namespace="ID: root. Path: "
2022-12-15T15:15:00.986+0530 [INFO]  rollback: starting rollback manager
2022-12-15T15:15:00.987+0530 [INFO]  core: restoring leases
2022-12-15T15:15:00.987+0530 [INFO]  expiration: lease restore complete
2022-12-15T15:15:00.987+0530 [INFO]  identity: entities restored
2022-12-15T15:15:00.987+0530 [INFO]  identity: groups restored
2022-12-15T15:15:00.988+0530 [INFO]  core: usage gauge collection is disabled
2022-12-15T15:15:00.989+0530 [INFO]  core: post-unseal setup complete
2022-12-15T15:15:00.989+0530 [INFO]  core: vault is unsealed
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault-cluster
Cluster ID      <cluster_id>
HA Enabled      false
----


. Verifique se o status do Vault selado é falso.
+
[listing]
----
[root@mcctb ~]# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault-cluster
Cluster ID      <cluster_id>
HA Enabled      false
----
. Configure o serviço Vault para iniciar na inicialização.
+
.. Execute o seguinte comando: `cd /etc/systemd/system`
+
[listing]
----
[root@mcctb ~]#  cd /etc/systemd/system
----
..  `[root@mcctb system]`No prompt, copie e execute o seguinte comando para criar o arquivo de serviço do Vault.
+
[source, cli]
----
# cat > vault.service << EOF
[Unit]
Description=Vault Service
After=mariadb.service

[Service]
Type=forking
ExecStart=/usr/bin/vault server -config /root/config.hcl &
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
----
.. Execute o seguinte comando: `systemctl daemon-reload`
+
[listing]
----
[root@mcctb system]#  systemctl daemon-reload
----
.. Execute o seguinte comando: `systemctl enable vault.service`
+
[listing]
----
[root@mcctb system]#  systemctl enable vault.service
Created symlink /etc/systemd/system/multi-user.target.wants/vault.service → /etc/systemd/system/vault.service.
----
+

NOTE: Você será solicitado a usar esse recurso durante a instalação do MetroCluster Tiebreaker. Se você quiser alterar o método para desselar o Vault, então você precisa desinstalar e reinstalar o software tiebreaker do MetroCluster.







== Instale as versões do MySQL Server 5.5.30 ou posterior e 5,6.x no Red Hat Enterprise Linux 7 ou CentOS 7

Você deve instalar o MySQL Server 5.5.30 ou posterior e a versão 5,6.x no sistema host antes de instalar ou atualizar o software tiebreaker. Para Red Hat Enterprise Linux 8, <<install-mariadb,Instale o servidor MariaDB>>.

.Passos
. Faça login como um usuário raiz ou um usuário sudo que pode mudar para o modo de privilégio avançado.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2016 from host.domain.com
----
. Adicione o repositório MySQL ao seu sistema host:
+
`[root@mcctb ~]# yum localinstall \https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm`

+
[listing, subs="verbatim,quotes"]
----
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
Setting up Local Package Process
Examining /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm: mysql-community-release-el6-5.noarch
Marking /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package mysql-community-release.noarch 0:el6-5 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
Package               Arch   Version
                                    Repository                             Size
================================================================================
Installing:
mysql-community-release
                       noarch el6-5 /mysql-community-release-el6-5.noarch 4.3 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total size: 4.3 k
Installed size: 4.3 k
*Is this ok [y/N]: y*
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-release-el6-5.noarch                         1/1
  Verifying  : mysql-community-release-el6-5.noarch                         1/1
Installed:
  mysql-community-release.noarch 0:el6-5
Complete!
----
. Desative o repositório MySQL 57:
+
`[root@mcctb ~]# yum-config-manager --disable mysql57-community`

. Ative o repositório MySQL 56:
+
`[root@mcctb ~]# yum-config-manager --enable mysql56-community`

. Ativar o repositório:
+
`[root@mcctb ~]# yum repolist enabled | grep "mysql.*-community.*"`

+
[listing]
----

mysql-connectors-community           MySQL Connectors Community            21
mysql-tools-community                MySQL Tools Community                 35
mysql56-community                    MySQL 5.6 Community Server           231
----
. Instale o servidor da Comunidade MySQL:
+
`[root@mcctb ~]# yum install mysql-community-server`

+
[listing, subs="verbatim,quotes"]
----
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager
to register.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
 .....Output truncated.....
---> Package mysql-community-libs-compat.x86_64 0:5.6.29-2.el6 will be obsoleting
--> Finished Dependency Resolution
Dependencies Resolved
==============================================================================
Package                          Arch   Version       Repository          Size
==============================================================================
Installing:
 mysql-community-client         x86_64  5.6.29-2.el6  mysql56-community  18  M
     replacing  mysql.x86_64 5.1.71-1.el6
 mysql-community-libs           x86_64  5.6.29-2.el6  mysql56-community  1.9 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-libs-compat    x86_64  5.6.29-2.el6  mysql56-community  1.6 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-server         x86_64  5.6.29-2.el6  mysql56-community  53  M
     replacing  mysql-server.x86_64 5.1.71-1.el6
Installing for dependencies:
mysql-community-common          x86_64  5.6.29-2.el6  mysql56-community   308 k

Transaction Summary
===============================================================================
Install       5 Package(s)
Total download size: 74 M
*Is this ok [y/N]: y*
Downloading Packages:
(1/5): mysql-community-client-5.6.29-2.el6.x86_64.rpm       |  18 MB     00:28
(2/5): mysql-community-common-5.6.29-2.el6.x86_64.rpm       | 308 kB     00:01
(3/5): mysql-community-libs-5.6.29-2.el6.x86_64.rpm         | 1.9 MB     00:05
(4/5): mysql-community-libs-compat-5.6.29-2.el6.x86_64.rpm  | 1.6 MB     00:05
(5/5): mysql-community-server-5.6.29-2.el6.x86_64.rpm       |  53 MB     03:42
 -------------------------------------------------------------------------------
Total                                              289 kB/s |  74 MB     04:24
warning: rpmts_HdrFromFdno: Header V3 DSA/SHA1 Signature, key ID <key_id> NOKEY
Retrieving key from file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Importing GPG key 0x5072E1F5:
 Userid : MySQL Release Engineering <mysql-build@oss.oracle.com>
Package: mysql-community-release-el6-5.noarch
         (@/mysql-community-release-el6-5.noarch)
 From   : file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
*Is this ok [y/N]: y*
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-common-5.6.29-2.el6.x86_64
....Output truncated....
1.el6.x86_64                                                               7/8
  Verifying  : mysql-5.1.71-1.el6.x86_64                       	           8/8
Installed:
  mysql-community-client.x86_64 0:5.6.29-2.el6
  mysql-community-libs.x86_64 0:5.6.29-2.el6
  mysql-community-libs-compat.x86_64 0:5.6.29-2.el6
  mysql-community-server.x86_64 0:5.6.29-2.el6

Dependency Installed:
  mysql-community-common.x86_64 0:5.6.29-2.el6

Replaced:
  mysql.x86_64 0:5.1.71-1.el6 mysql-libs.x86_64 0:5.1.71-1.el6
  mysql-server.x86_64 0:5.1.71-1.el6
Complete!

----
. Inicie o servidor MySQL:
+
`[root@mcctb ~]# service mysqld start`

+
[listing]
----

Initializing MySQL database:  2016-04-05 19:44:38 0 [Warning] TIMESTAMP
with implicit DEFAULT value is deprecated. Please use
--explicit_defaults_for_timestamp server option (see documentation
for more details).
2016-04-05 19:44:38 0 [Note] /usr/sbin/mysqld (mysqld 5.6.29)
        starting as process 2487 ...
2016-04-05 19:44:38 2487 [Note] InnoDB: Using atomics to ref count
        buffer pool pages
2016-04-05 19:44:38 2487 [Note] InnoDB: The InnoDB memory heap is disabled
....Output truncated....
2016-04-05 19:44:42 2509 [Note] InnoDB: Shutdown completed; log sequence
       number 1625987

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER!
To do so, start the server, then issue the following commands:

  /usr/bin/mysqladmin -u root password 'new-password'
  /usr/bin/mysqladmin -u root -h mcctb password 'new-password'

Alternatively, you can run:
  /usr/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
.....Output truncated.....
WARNING: Default config file /etc/my.cnf exists on the system
This file will be read by default by the MySQL server
If you do not want to use this, either remove it, or use the
--defaults-file argument to mysqld_safe when starting the server

                                                           [  OK  ]
Starting mysqld:                                           [  OK  ]
----
. Confirme se o servidor MySQL está em execução:
+
`[root@mcctb ~]# service mysqld status`

+
[listing]
----

mysqld (pid  2739) is running...
----
. Configurar definições de segurança e palavra-passe:
+
`[root@mcctb ~]# mysql_secure_installation`

+
[listing, subs="verbatim,quotes"]
----
NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MySQL
       SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

 In order to log into MySQL to secure it, we'll need the current
 password for the root user.  If you've just installed MySQL, and
 you haven't set the root password yet, the password will be blank,
 so you should just press enter here.

 *Enter current password for root (enter for none):*   <== on default install
                                                         hit enter here
 OK, successfully used password, moving on...

 Setting the root password ensures that nobody can log into the MySQL
 root user without the proper authorization.

 *Set root password? [Y/n] y*
 *New password:*
 *Re-enter new password:*
 Password updated successfully!
 Reloading privilege tables..
  ... Success!

 By default, a MySQL installation has an anonymous user, allowing anyone
 to log into MySQL without having to have a user account created for
 them.  This is intended only for testing, and to make the installation
 go a bit smoother.  You should remove them before moving into a
 production environment.

 *Remove anonymous users? [Y/n] y*
  ... Success!

 Normally, root should only be allowed to connect from 'localhost'.  This
 ensures that someone cannot guess at the root password from the network.

 *Disallow root login remotely? [Y/n] y*
  ... Success!

 By default, MySQL comes with a database named 'test' that anyone can
 access.  This is also intended only for testing, and should be removed
 before moving into a production environment.

 *Remove test database and access to it? [Y/n] y*
  - Dropping test database...
 ERROR 1008 (HY000) at line 1: Can't drop database 'test';
 database doesn't exist
  ... Failed!  Not critical, keep moving...
  - Removing privileges on test database...
  ... Success!

 Reloading the privilege tables will ensure that all changes made so far
 will take effect immediately.

 *Reload privilege tables now? [Y/n] y*
  ... Success!

 All done!  If you've completed all of the above steps, your MySQL
 installation should now be secure.

 Thanks for using MySQL!

 Cleaning up...
----
. Verifique se o login do MySQL está funcionando:
+
`[root@mcctb ~]# mysql -u root –p`

+
[listing, subs="verbatim,quotes"]
----
*Enter password: <configured_password>*
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.6.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql>
----
+
Se o login do MySQL estiver funcionando, a saída terminará no `mysql>` prompt.





=== Ative a configuração de inicialização automática do MySQL

Você deve verificar se o recurso autostart está ativado para o daemon MySQL. Ativar o daemon MySQL reinicia automaticamente o MySQL se o sistema no qual o software tiebreaker do MetroCluster reside for reinicializado. Se o daemon MySQL não estiver em execução, o software tiebreaker continua em execução, mas não pode ser reiniciado e as alterações de configuração não podem ser feitas.

.Passo
. Verifique se o MySQL está habilitado para iniciar automaticamente quando inicializado:
+
`[root@mcctb ~]# systemctl list-unit-files mysqld.service`

+
[listing]
----
UNIT FILE          State
------------------ ----------
mysqld.service     enabled

----
+
Se o MySQL não estiver habilitado para iniciar automaticamente quando inicializado, consulte a documentação do MySQL para ativar o recurso de inicialização automática para sua instalação.





== Instale o servidor MariaDB no Red Hat Enterprise Linux 8

Você deve instalar o servidor MariaDB no sistema host antes de instalar ou atualizar o software tiebreaker. Para Red Hat Enterprise Linux 7 ou CentOS 7, <<install-mysql-redhat,Instale o MySQL Server>>.

.Antes de começar
Seu sistema host deve estar em execução no Red Hat Enterprise Linux (RHEL) 8.

.Passos
. Faça login como um `root` usuário ou um usuário que pode sudo para o modo de privilégio avançado.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. Instale o servidor MariaDB:
+
`[root@mcctb ~]# yum install mariadb-server.x86_64`

+
[listing, subs="verbatim,quotes"]
----

[root@mcctb ~]# yum install mariadb-server.x86_64
Loaded plugins: fastestmirror, langpacks
 ...
 ...

===========================================================================
 Package                      Arch   Version         Repository        Size
===========================================================================
Installing:
mariadb-server               x86_64   1:5.5.56-2.el7   base            11 M
Installing for dependencies:

Transaction Summary
===========================================================================
Install  1 Package  (+8 Dependent packages)
Upgrade             ( 1 Dependent package)

Total download size: 22 M
*Is this ok [y/d/N]: y*

Downloading packages:
No Presto metadata available for base warning:
/var/cache/yum/x86_64/7/base/packages/mariadb-libs-5.5.56-2.el7.x86_64.rpm:
Header V3 RSA/SHA256 Signature,
key ID f4a80eb5: NOKEY] 1.4 MB/s | 3.3 MB  00:00:13 ETA
Public key for mariadb-libs-5.5.56-2.el7.x86_64.rpm is not installed
(1/10): mariadb-libs-5.5.56-2.el7.x86_64.rpm  | 757 kB  00:00:01
..
..
(10/10): perl-Net-Daemon-0.48-5.el7.noarch.rpm|  51 kB  00:00:01
-----------------------------------------------------------------------------------------
Installed:
  mariadb-server.x86_64 1:5.5.56-2.el7

Dependency Installed:
mariadb.x86_64 1:5.5.56-2.el7
perl-Compress-Raw-Bzip2.x86_64 0:2.061-3.el7
perl-Compress-Raw-Zlib.x86_64 1:2.061-4.el7
perl-DBD-MySQL.x86_64 0:4.023-5.el7
perl-DBI.x86_64 0:1.627-4.el7
perl-IO-Compress.noarch 0:2.061-2.el7
perl-Net-Daemon.noarch 0:0.48-5.el7
perl-PlRPC.noarch 0:0.2020-14.el7

Dependency Updated:
  mariadb-libs.x86_64 1:5.5.56-2.el7
Complete!
----
. Inicie o servidor MariaDB:
+
`[root@mcctb ~]# systemctl start mariadb`

. Verifique se o servidor MariaDB foi iniciado:
+
`[root@mcctb ~]# systemctl status mariadb`

+
[listing]
----
[root@mcctb ~]# systemctl status mariadb
mariadb.service - MariaDB database server
...
Nov 08 21:28:59 mcctb systemd[1]: Starting MariaDB database server...
...
Nov 08 21:29:01 mcctb systemd[1]: Started MariaDB database server.
----
. Configure as definições de segurança e palavra-passe:
+

NOTE: Quando for solicitada a palavra-passe raiz, deixe-a vazia e prima ENTER para continuar a configurar as definições de segurança e palavra-passe.

+
`[root@mcctb ~]# mysql_secure_installation`

+
[listing, subs="quotes"]
----
root@localhost systemd]# mysql_secure_installation

 NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none):
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

*Set root password? [Y/n] y*
*New password:*
*Re-enter new password:*
Password updated successfully!
Reloading privilege tables..
 ... Success!


By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

*Remove anonymous users? [Y/n] y*
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

*Disallow root login remotely? [Y/n] y*
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

*Remove test database and access to it? [Y/n] y*
 - Dropping test database...
  ... Success!
 - Removing privileges on test database...
   ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

*Reload privilege tables now? [Y/n]*

 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!

----




=== Ative a configuração de início automático para o servidor MariaDB

Você deve verificar se o recurso de inicialização automática está ativado para o servidor MariaDB. Se você não ativar o recurso de inicialização automática e o sistema no qual o software tiebreaker do MetroCluster reside precisar reinicializar, o software tiebreaker continuará em execução, mas o serviço MariaDB não poderá ser reiniciado e as alterações de configuração não poderão ser feitas.

.Passos
. Ative o serviço de arranque automático:
+
`[root@mcctb ~]# systemctl enable mariadb.service`

. Verifique se o MariaDB está habilitado para iniciar automaticamente quando inicializado:
+
`[root@mcctb ~]# systemctl list-unit-files mariadb.service`

+
[listing]
----
UNIT FILE          State
------------------ ----------
mariadb.service    enabled
----

