---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html 
sidebar: sidebar 
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster 
summary: Você precisa verificar se está usando as atribuições de portas especificadas quando você faz o cabeamento dos switches FC ao usar o ONTAP 9.1 e posterior. 
---
= Atribuições de portas para switches FC ao usar sistemas AFF A900 ou FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa verificar se está usando as atribuições de portas especificadas quando você faz o cabeamento dos switches FC ao usar o ONTAP 9.10,1 e posterior.

As portas que não são usadas para anexar portas do iniciador, portas FC-VI ou ISLs podem ser reconfiguradas para agir como portas de storage. No entanto, se os RCFs suportados estiverem sendo usados, o zoneamento deve ser alterado em conformidade.

Se os RCFs suportados forem usados, as portas ISL podem não se conetar às mesmas portas mostradas e podem precisar ser reconfiguradas manualmente.

Se você configurou seus switches usando as atribuições de portas do ONTAP 9, poderá continuar a usar as atribuições mais antigas. No entanto, novas configurações que executam o ONTAP 9.1 ou versões posteriores devem usar as atribuições de portas mostradas aqui.



== Diretrizes gerais de cabeamento

Você deve estar ciente das seguintes diretrizes ao usar as tabelas de cabeamento:

* Os sistemas de storage AFF A900 ou FAS9500 exigem oito portas FC-VI. Se você estiver usando um AFF A900 ou FAS9500, será necessário usar a configuração de oito portas. Se a configuração incluir outros modelos de sistema de storage, use o cabeamento mostrado nas tabelas, mas ignore o cabeamento para portas FC-VI desnecessárias.
* Se você tiver duas configurações do MetroCluster compartilhando ISLs, use as mesmas atribuições de porta que aquela para um cabeamento MetroCluster de oito nós.
* O número de ISLs que você faz a cabo pode variar dependendo dos requisitos do local.
* Consulte a secção sobre considerações ISL.
+
link:concept_considerations_isls_mcfc.html["Considerações para ISLs"]


