---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: Os sistemas ONTAP, os storage arrays e os switches FC usados nas configurações do MetroCluster precisam atender aos requisitos desses tipos de configurações. Além disso, você também deve considerar os requisitos do SyncMirror para configurações do MetroCluster com LUNs de array. 
---
= Requisitos para uma configuração MetroCluster com LUNs de array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas ONTAP, os storage arrays e os switches FC usados nas configurações do MetroCluster precisam atender aos requisitos desses tipos de configurações. Além disso, você também deve considerar os requisitos do SyncMirror para configurações do MetroCluster com LUNs de array.



== Requisitos para sistemas ONTAP

* Os sistemas ONTAP devem ser identificados como compatíveis com configurações MetroCluster.
+
No https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"], você pode usar o campo solução de armazenamento para selecionar sua solução MetroCluster. Use o *Explorador de componentes* para selecionar os componentes e a versão do ONTAP para refinar sua pesquisa. Você pode clicar em *Mostrar resultados* para exibir a lista de configurações compatíveis que correspondem aos critérios.

+

NOTE: Você deve consultar os detalhes de alerta associados a qualquer configuração selecionada na Matriz de interoperabilidade.

* Todos os sistemas ONTAP em uma configuração MetroCluster devem ter o mesmo modelo.
* Os adaptadores FC-VI devem ser instalados nos slots apropriados para cada sistema ONTAP, dependendo do modelo.
+
https://hwu.netapp.com["NetApp Hardware Universe"]





== Requisitos para matrizes de armazenamento

* Os storage arrays devem ser identificados como compatíveis com as configurações do MetroCluster.
+
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]

* Os storage arrays na configuração do MetroCluster devem ser simétricos:
+
** Os dois storage arrays devem ser da mesma família de fornecedores com suporte e ter a mesma versão de firmware instalada.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["Implementação de virtualização FlexArray para storage NetApp e-Series"]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["Implementação de virtualização de FlexArray para storage de terceiros"]

** Os tipos de disco (por exemplo, SATA, SSD ou SAS) usados para armazenamento espelhado devem ser os mesmos em ambas as matrizes de armazenamento.
** Os parâmetros para configurar matrizes de armazenamento, como o tipo RAID e a disposição em camadas, devem ser os mesmos em ambos os locais.






== Requisitos para switches FC

* Os switches e o firmware do switch devem ser identificados como compatíveis com configurações MetroCluster.
+
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]

* Cada malha precisa ter dois switches FC.
* Cada sistema ONTAP deve ser conetado ao storage usando componentes redundantes para que haja redundância em caso de falhas de dispositivo e caminho.
* Os sistemas de storage AFF A700, FAS9000, AFF A900 e FAS9500 são compatíveis com até oito ISLs por malha. Outros modelos de sistemas de storage suportam até quatro ISLs por malha.
* Os switches devem usar a configuração básica do switch MetroCluster, as configurações ISL e FC-VI.
+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configure os switches Cisco FC manualmente"]

+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurar manualmente os switches Brocade FC"]





== Requisitos da SyncMirror

* O SyncMirror é necessário para uma configuração do MetroCluster.
* Dois storage arrays separados, um em cada local, são necessários para o storage espelhado.
* São necessários dois conjuntos de LUNs de array.
+
Um conjunto é necessário para o agregado no storage de armazenamento local (pool0) e outro conjunto é necessário no storage de armazenamento remoto para o espelho do agregado (o outro Plex do agregado, pool1).

+
Os LUNs do array devem ter o mesmo tamanho para espelhar o agregado.

* Agregados não espelhados também são suportados na configuração MetroCluster.
+
Eles não são protegidos em caso de desastre no local.




NOTE: É recomendável manter pelo menos 20% de espaço livre para agregados espelhados para performance e disponibilidade ideais de storage. Embora a recomendação seja de 10% para agregados não espelhados, os 10% adicionais de espaço podem ser usados pelo sistema de arquivos para absorver alterações incrementais. Mudanças incrementais aumentam a utilização de espaço para agregados espelhados devido à arquitetura baseada em Snapshot copy-on-write da ONTAP. O não cumprimento destas práticas recomendadas pode ter um impactos negativo no desempenho.
