---
permalink: install-fc/reference_supported_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, supported, array, luns 
summary: Você pode configurar uma configuração MetroCluster com LUNs de array. Tanto as configurações elásticas quanto as de tecido são suportadas. Os sistemas AFF não são compatíveis com LUNs de array. 
---
= Configuração de MetroCluster compatível com LUNs de array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar uma configuração MetroCluster com LUNs de array. Tanto as configurações elásticas quanto as de tecido são suportadas. Os sistemas AFF não são compatíveis com LUNs de array.

Os recursos suportados nas configurações do MetroCluster variam de acordo com os tipos de configuração. A tabela a seguir lista os recursos suportados nos diferentes tipos de configurações do MetroCluster com LUNs de array:

|===


.2+| Recurso 3+| Configurações com conexão de malha | Configurações elásticas 


| Oito nós | Quatro nós | Dois nós | Dois nós 


 a| 
Número de controladores
 a| 
Oito
 a| 
Quatro
 a| 
Dois
 a| 
Dois



| Usa uma malha de storage de switch FC | Sim | Sim | Sim | Sim 


| Usa pontes FC para SAS | Sim | Sim | Sim | Sim 


| Suporta HA local | Sim | Sim | Não | Não 


| Suporta switchover automático | Sim | Sim | Sim | Sim 
|===
.Informações relacionadas
link:concept_considerations_differences.html["Diferenças entre as configurações do ONTAP MetroCluster"]
