---
permalink: install-fc/task_fmc_mcc_transition_configure_zone_and_qos.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, delete, ti, zoning, tod, settings 
summary: 'Você deve excluir o zoneamento de TI existente e reconfigurar as configurações de entrega de pedidos (IOD) na malha do switch.' 
---
= Eliminar o zoneamento do TI e configurar as definições do IOD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve excluir o zoneamento de TI existente e reconfigurar as configurações de entrega de pedidos (IOD) na malha do switch.

.Passos
. Identifique as zonas de TI configuradas na malha:
+
`zone --show`

+
O exemplo a seguir mostra a zona FCVI_TI_FAB_2.

+
[listing]
----
Brocade-6510:admin> zone --show
   Defined TI zone configuration:
   TI Zone Name:   FCVI_TI_FAB_2
   Port List:      1,0; 1,3; 2,0; 2,3
   configured Status: Activated / Failover-Disabled
   Enabled Status: Activated / Failover-Disabled
----
. Eliminar as zonas TI:
+
`zone --delete _zone-name_`

+
O exemplo a seguir mostra a exclusão da zona FCVI_TI_FAB_2.

+
[listing]
----
Brocade-6510:admin> zone --delete FCVI_TI_FAB_2
----
. Confirme se as zonas foram eliminadas:
+
`zone --show`

+
A saída deve ser semelhante ao seguinte:

+
[listing]
----
Brocade-6510:admin> zone -–show

    Defined TI zone configuration:
    no TI zone configuration defined
----
. Guardar a configuração:
+
`cfgsave`

. Ativar entrega na encomenda:
+
`iodset`

. Selecione a política Advanced Performance Tuning (APT) 1, a Política de Roteamento baseado em portas:
+
`aptpolicy 1`

. Desativar a partilha de carga dinâmica (DLS):
+
`dlsreset`

. Verifique as configurações IOD:
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
A saída deve ser semelhante ao seguinte:

+
[listing]
----
Brocade-6510:admin> iodshow

IOD is set

Brocade-6510:admin> aptpolicy
 Current Policy: 1

 3 : Default Policy
 1: Port Based Routing Policy
 2: Device Based Routing Policy (FICON support only)
 3: Exchange Based Routing Policy
Brocade-6510:admin> dlsshow

DLS is not set
----

