---
permalink: install-fc/task_rack_the_hardware_components_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, rack, hardware, components, array, luns 
summary: Você deve garantir que os componentes de hardware necessários para configurar uma configuração MetroCluster com LUNs de array sejam corretamente montados em rack. 
---
= Empilhando os componentes de hardware em uma configuração MetroCluster com LUNs de matriz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve garantir que os componentes de hardware necessários para configurar uma configuração MetroCluster com LUNs de array sejam corretamente montados em rack.

.Sobre esta tarefa
Você deve executar esta tarefa em ambos os sites do MetroCluster.

.Passos
. Planeie o posicionamento dos componentes do MetroCluster.
+
O espaço em rack depende do modelo de plataforma dos controladores de storage, dos tipos de switch e do número de stacks de compartimento de disco na configuração.

. Aterre-se corretamente.
. Instale os controladores de armazenamento no rack ou gabinete.
+

NOTE: Os sistemas AFF não são compatíveis com LUNs de array.

+
https://docs.netapp.com/us-en/ontap-systems/["Procedimentos de instalação para o seu sistema AFF ou FAS"]

. Instale os switches FC no rack ou gabinete.

