---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, brocade, fc, switch, rcf, file 
summary: Você deve baixar o arquivo de configuração de referência para cada switch na configuração da estrutura do MetroCluster. 
---
= Transferir o ficheiro RCF do switch Brocade FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve baixar o arquivo de configuração (RCF) para cada switch na configuração de MetroCluster fabric.

.Sobre esta tarefa
Para usar esses RCFs, o sistema deve estar executando o ONTAP 9.1 ou posterior e você deve usar o layout de porta para o ONTAP 9.1 ou posterior.

Se você estiver planejando usar apenas uma das portas FC nas pontes FibreBridge, configure os switches Fibre Channel de back-end manualmente usando as instruções encontradas na seção, link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Atribuições de portas para switches FC"] .

.Passos
. Consulte a tabela RCF na página de download do Brocade RCF e identifique o RCF correto para cada switch em sua configuração.
+
Os RCFs devem ser aplicados aos switches corretos.

. Faça o download dos arquivos RCF para os switches na  https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["Baixar MetroCluster RCF"] página.
+
Os arquivos devem ser colocados em um local onde possam ser transferidos para o switch. Há um arquivo separado para cada um dos quatro switches que compõem a malha de dois switches.

. Repita estas etapas em cada switch na configuração.

