---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, cisco, fc, switch, nx, software 
summary: É necessário fazer download do arquivo do sistema operacional do switch e do arquivo RCF para cada switch na configuração do MetroCluster Fabric. 
---
= Transferir e instalar o software Cisco FC switch NX-os
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É necessário fazer download do arquivo do sistema operacional do switch e do arquivo RCF para cada switch na configuração do MetroCluster Fabric.

.Antes de começar
Esta tarefa requer software de transferência de arquivos, como FTP, TFTP, SFTP ou SCP, para copiar os arquivos para os switches.

.Sobre esta tarefa
Essas etapas devem ser repetidas em cada um dos switches FC na configuração da malha do MetroCluster.

Tem de utilizar a versão do software de comutação suportada.

https://hwu.netapp.com["NetApp Hardware Universe"^]


NOTE: As saídas mostradas são para switches IP Cisco; no entanto, estas etapas também são aplicáveis para switches FC Cisco.

.Passos
. Transfira o ficheiro de software NX-os suportado.
+
link:https://software.cisco.com/download/home["Página de download do Cisco"^]

. Copie o software do interrutor para o interrutor:
+
`copy sftp://root@server-ip-address/tftpboot/NX-OS-file-name bootflash: vrf management`

+
Neste exemplo, o `nxos.7.0.3.I4.6.bin` arquivo é copiado do servidor SFTP 10.10.99.99 para o flash de inicialização local:

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. Verifique em cada switch se os arquivos NX-os estão presentes no diretório bootflash de cada switch:
+
`dir bootflash`

+
O exemplo a seguir mostra que os arquivos estão presentes `IP_switch_A_1` no :

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Instale o software do interrutor:
+
`install all system bootflash:nxos.version-number.bin kickstart bootflash:nxos.version-kickstart-number.bin`

+
[listing]
----
IP_switch_A_1#  install all system bootflash:nxos.7.0.3.I4.6.bin kickstart bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "kickstart".
[####################] 100% -- SUCCESS

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "system".
[####################] 100% -- SUCCESS

Performing module support checks.                                                                                                            [####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Extracting "system" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Extracting "kickstart" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS
...
----
+
O interrutor reinicia automaticamente após a instalação do software do interrutor.

. Aguarde até que o interrutor seja recarregado e, em seguida, inicie sessão no interrutor.
+
Depois que o switch reiniciar, o prompt de login é exibido:

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. Verifique se o software do switch foi instalado:
+
`show version`

+
O exemplo a seguir mostra a saída:

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. Repita essas etapas nos três switches FC restantes na configuração da malha do MetroCluster.

