---
permalink: install-fc/task_fmc_mcc_transition_cable_the_new_mcc_controllers_to_the_exist_fc_fabrics.html 
sidebar: sidebar 
keywords: cabling, metrocluster, fabric, installation, fc, controllers 
summary: Em cada controladora na configuração de cluster ONTAP MetroCluster, o adaptador FC-VI e HBAs devem ser cabeados para portas específicas nos switches FC existentes. 
---
= Fazer o cabeamento das novas controladoras MetroCluster às malhas FC existentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em cada controladora na configuração de cluster ONTAP MetroCluster, o adaptador FC-VI e HBAs devem ser cabeados para portas específicas nos switches FC existentes.

.Passos
. Faça o cabeamento das portas FC-VI e HBA de acordo com a seguinte tabela:
+
|===


2+| Local A 2+| Local B 


| Conetar este Site Um componente e uma porta... | Porta FC_switch_A_1... | Ligar este componente do local B e porta... | Porta FC_switch_B_1... 


 a| 
Controller_A_1 FC-VI porta 1
 a| 
32
 a| 
Controller_B_1 FC-VI porta 1
 a| 
32



 a| 
Controller_A_1 HBA porta 1
 a| 
33
 a| 
Controlador_B_1 porta HBA 1
 a| 
33



 a| 
Controller_A_1 HBA porta 2
 a| 
34
 a| 
Controlador_B_1 porta HBA 2
 a| 
34



 a| 
Controller_A_2 FC-VI porta 1
 a| 
35
 a| 
Controller_B_2 FC-VI porta 1
 a| 
35



 a| 
controller_A_2 HBA 1
 a| 
36
 a| 
controller_B_2 HBA 1
 a| 
36



 a| 
controller_A_2 HBA 2
 a| 
37
 a| 
controller_B_2 HBA 2
 a| 
37

|===
. Cable cada ponte FC-SAS na primeira malha de switch aos switches FC.
+
O número de bridges varia dependendo do número de stacks de armazenamento SAS.

+
|===


2+| Local A 2+| Local B 


| Este local É Uma ponte... | Porta FC_switch_A_1... | Cable this Site B bridge... | Porta FC_switch_B_1... 


 a| 
bridge_A_1_38
 a| 
38
 a| 
bridge_B_1_38
 a| 
38



 a| 
bridge_A_1_39
 a| 
39
 a| 
bridge_B_1_39
 a| 
39

|===
. Conete cada ponte na segunda malha de switch aos switches FC.
+
O número de bridges varia dependendo do número de stacks de armazenamento SAS.

+
|===


2+| Local A 2+| Local B 


| Este local É Uma ponte... | Porta FC_switch_A_2... | Cable this Site B bridge... | Porta FC_switch_B_2... 


 a| 
bridge_A_2_38
 a| 
38
 a| 
bridge_B_2_38
 a| 
38



 a| 
bridge_A_2_39
 a| 
39
 a| 
bridge_B_2_39
 a| 
39

|===

