---
permalink: install-fc/task_fmc_mcc_transition_disable_one_of_the_switch_fabrics.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, disable, switch, fabrics 
summary: Você deve desativar uma das malhas do switch para que possa modificar sua configuração. Depois de concluir a configuração e reativar a malha do switch, você repetirá o processo na outra malha. 
---
= Desativação de uma das malhas de comutação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve desativar uma das malhas do switch para que possa modificar sua configuração. Depois de concluir a configuração e reativar a malha do switch, você repetirá o processo na outra malha.

.Antes de começar
Você deve ter executado o utilitário fmc_dc na configuração existente do 7-Mode Fabric MetroCluster e resolvido quaisquer problemas antes de iniciar o processo de configuração.

.Sobre esta tarefa
Para garantir a operação contínua da configuração do MetroCluster, não é necessário desativar a segunda malha enquanto a primeira malha estiver desativada.

.Passos
. Desative cada um dos switches na estrutura:
+
`switchCfgPersistentDisable`

+
Se este comando não estiver disponível, use o `switchDisable` comando.

+
** O exemplo a seguir mostra o comando emitido em FC_switch_A_1:
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
** O exemplo a seguir mostra o comando emitido em FC_switch_B_1:
+
[listing]
----
FC_switch_B_1:admin> switchCfgPersistentDisable
----


. Certifique-se de que a configuração do MetroCluster de 7 modos esteja funcionando corretamente usando a estrutura redundante:
+
.. Confirme se o failover de controladora está em bom estado
`cf status`
+
[listing]
----
node_A> cf status
Controller Failover enabled, node_A is up.
VIA Interconnect is up (link 0 down, link 1 up).
----
.. Confirme se os discos estão visíveis
`storage show disk –p`
+
[listing]
----
node_A> storage show disk –p

PRIMARY                     PORT  SECONDARY          PORT SHELF BAY
--------------------------- ----  ------------------ ---- ---------
Brocade-6510-2K0GG:5.126L27  B                              1    0
Brocade-6510-2K0GG:5.126L28  B                              1    1
Brocade-6510-2K0GG:5.126L29  B                              1    2
Brocade-6510-2K0GG:5.126L30  B                              1    3
Brocade-6510-2K0GG:5.126L31  B                              1    4

.
.
.
----
.. Confirme que os agregados estão saudáveis
`aggr status`
+
[listing]
----
node_A> aggr status
           Aggr State           Status              Options
          aggr0 online          raid_dp, aggr       root, nosnap=on
                                mirrored
                                64-bit
----



