---
permalink: install-fc/task_prepare_a_storage_array_for_use_with_ontap_systems.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, prepare, storage, array, systems 
summary: Antes de começar a configurar sistemas ONTAP em uma configuração MetroCluster com LUNs de array, o administrador do storage deve preparar o armazenamento para uso com o ONTAP. 
---
= Preparação de um storage array para uso com sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de começar a configurar sistemas ONTAP em uma configuração MetroCluster com LUNs de array, o administrador do storage deve preparar o armazenamento para uso com o ONTAP.

.Antes de começar
As matrizes de armazenamento, firmware e comutadores que pretende utilizar na configuração têm de ser suportadas pela versão específica do ONTAP.

* https://imt.netapp.com/matrix/["Interoperabilidade NetApp (IMT)"^]
+
No IMT, você pode usar o campo solução de armazenamento para selecionar sua solução MetroCluster. Use o *Explorador de componentes* para selecionar os componentes e a versão do ONTAP para refinar sua pesquisa. Você pode clicar em *Mostrar resultados* para exibir a lista de configurações compatíveis que correspondem aos critérios.

* https://hwu.netapp.com["NetApp Hardware Universe"]


.Sobre esta tarefa
Você deve coordenar com o administrador do storage array para executar essa tarefa no storage array.

.Passos
. Crie LUNs no storage array, dependendo do número de nós na configuração do MetroCluster.
+
Cada nó na configuração do MetroCluster requer LUNs de array para agregado de raiz, agregado de dados e peças sobressalentes.

. Configure parâmetros no storage array que são necessários para trabalhar com o ONTAP.
+
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["Implementação de virtualização de FlexArray para storage de terceiros"]
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["Implementação de virtualização FlexArray para storage NetApp e-Series"]



