---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 'Você deve certificar-se de que os links inter-switch (ISLs) estão no mesmo grupo de portas e configurar o zoneamento para as configurações do MetroCluster para compartilhar com êxito as malhas do switch.' 
---
= Garantir que os ISLs estejam no mesmo grupo de portas e configurando o zoneamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve se certificar de que os ISLs (Inter-Switch Links) estão no mesmo grupo de portas e configurar o zoneamento para as configurações do MetroCluster para compartilhar com êxito as malhas do switch.

.Passos
. Se os ISLs não estiverem no mesmo grupo de portas, mova uma das portas ISL para o mesmo grupo de portas do outro.
+
Você pode usar qualquer porta disponível, exceto 32 até 45, que são usadas pela nova configuração do MetroCluster. As portas ISL recomendadas são 46 e 47.

. Siga as etapas na link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuração de zoneamento em switches Brocade FC"] seção para ativar o entroncamento e a zona de QoS.
+
Os números de porta ao compartilhar tecidos são diferentes dos mostrados na seção. Ao compartilhar, use as portas 46 e 47 para as portas ISL. Se você moveu suas portas ISL, você precisará usar o procedimento na link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurando as portas e (portas ISL) em um switch Brocade FC"] seção para configurar as portas.

. [[step3_Zones]] siga as etapas na link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurando as portas não-e no switch Brocade"] seção para configurar as portas não E.
. Não exclua as zonas ou conjuntos de zonas que já existem nos switches backend (para o MetroCluster de malha de 7 modos), exceto as zonas de isolamento de tráfego (TI) em <<step3_zones,Passo 3>>.
. Siga as etapas na link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurando as portas e (portas ISL) em um switch Brocade FC"] seção para adicionar as zonas exigidas pelo novo MetroCluster aos conjuntos de zonas existentes.
+
O exemplo a seguir mostra os comandos e a saída do sistema para criar as zonas:

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

