---
permalink: install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html 
sidebar: sidebar 
keywords: MetroCluster configurations 
summary: Você deve configurar cada uma das malhas de switch Brocade na configuração do MetroCluster. 
---
= Configuração manual dos switches Brocade FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar cada uma das malhas de switch Brocade na configuração do MetroCluster.

.Antes de começar
* Você deve ter uma estação de trabalho PC ou UNIX com acesso Telnet ou SSH (Secure Shell) aos switches FC.
* Você precisa estar usando quatro switches Brocade compatíveis do mesmo modelo com a mesma versão e licenciamento do sistema operacional (FOS) da Brocade Fabric.
+
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]

+
No IMT, você pode usar o campo solução de armazenamento para selecionar sua solução MetroCluster. Use o *Explorador de componentes* para selecionar os componentes e a versão do ONTAP para refinar sua pesquisa. Você pode clicar em *Mostrar resultados* para exibir a lista de configurações compatíveis que correspondem aos critérios.

* Os quatro switches Brocade compatíveis devem ser conectados a duas malhas de dois switches cada, com cada malha abrangendo ambos os locais.
* Cada controlador de storage deve ter quatro portas do iniciador disponíveis para conexão às malhas do switch. Duas portas de iniciador devem ser conectadas de cada controlador de storage a cada malha.
+

NOTE: Você pode configurar sistemas FAS8020, AFF8020, FAS8200 e AFF A300 com duas portas de iniciadores por controladora (uma única porta de iniciador para cada malha) se todos os critérios a seguir forem atendidos:

+
** Há menos de quatro portas do iniciador FC disponíveis para conetar o armazenamento de disco e nenhuma porta adicional pode ser configurada como iniciadores FC.
** Todos os slots estão em uso e nenhuma placa de iniciador FC pode ser adicionada.




.Sobre esta tarefa
* Você deve ativar o entroncamento de enlace Inter-Switch (ISL) quando ele for suportado pelos links.
+
link:concept_tdm_wdm.html["Considerações sobre o uso de equipamentos TDM/WDM com configurações MetroCluster conetadas à malha"]

* Se você usar uma configuração xWDM, poderá exigir configurações adicionais nos ISLs. Consulte a documentação do fornecedor xWDM para obter mais informações.
* Todos os ISLs devem ter o mesmo comprimento e a mesma velocidade em um tecido.
+
Diferentes comprimentos podem ser usados nos diferentes tecidos. A mesma velocidade deve ser usada em todos os tecidos.

* Metro-e e TDM (SONET/SDH) não são suportados, e qualquer enquadramento ou sinalização nativa não FC não é suportado.
+
Metro-e significa que o enquadramento ou sinalização Ethernet ocorre nativamente ao longo de uma distância Metro ou através de alguma multiplexação por divisão de tempo (TDM), comutação de etiquetas multiprotocolo (MPLS) ou multiplexação por divisão de comprimento de onda (WDM).

* As extensões TDMs, FCR (roteamento FC nativo) ou FCIP não são compatíveis com a malha de switch MetroCluster FC.
* Os seguintes switches Brocade FC são compatíveis com criptografia e compactação ISL WAN para malhas back-end MetroCluster FC:
+
** Brocade G720
** Brocade G630
** Brocade G620
** Brocade 6520




* O recurso de malha virtual (VF) do Brocade não é suportado.
* O zoneamento FC baseado na porta de domínio é suportado, mas o zoneamento baseado no nome mundial (WWN) não é suportado.




== Revisão dos requisitos de licença do Brocade

Você precisa de certas licenças para os switches em uma configuração do MetroCluster. Você deve instalar essas licenças em todos os quatro switches.

.Sobre esta tarefa
A configuração do MetroCluster tem os seguintes requisitos de licença do Brocade:

* Licença de entroncamento para sistemas que utilizam mais de um ISL, conforme recomendado.
* Licença alargada de tecido (para distâncias ISL superiores a 6 km)
* Licença Enterprise para locais com mais de um ISL e uma distância ISL superior a 6 km
+
A licença Enterprise inclui o consultor de rede Brocade e todas as licenças, exceto para licenças de porta adicionais.



.Passo
. Verifique se as licenças estão instaladas:
+
[role="tabbed-block"]
====
.Para o Fabric os 8,2.x e anteriores
--
Executar o comando `licenseshow`.

--
.Para o Fabric os 9,0 e posterior
--
Executar o comando `license --show`.

--
====
+
Se você não tiver essas licenças, entre em Contato com seu representante de vendas antes de prosseguir.





== Definir os valores do switch Brocade FC para os padrões de fábrica

Você deve definir o switch para seus padrões de fábrica para garantir uma configuração bem-sucedida. Você também deve atribuir a cada switch um nome exclusivo.

.Sobre esta tarefa
Nos exemplos deste procedimento, o tecido consiste em BrocadeSwitchA e BrocadeSwitchB.

.Passos
. Faça uma conexão de console e faça login em ambos os switches em uma malha.
. Desative o interrutor persistentemente:
+
`switchcfgpersistentdisable`

+
Isso garante que o switch permanecerá desativado após uma reinicialização ou fastboot. Se este comando não estiver disponível, use o `switchdisable` comando.

+
O exemplo a seguir mostra o comando no BrocadeSwitchA:

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
O exemplo a seguir mostra o comando no BrocadeSwitchB:

+
[listing]
----
BrocadeSwitchB:admin> switchcfgpersistentdisable
----
. Defina o nome do interrutor:
+
`switchname switch_name`

+
Cada um dos switches deve ter um nome exclusivo. Depois de definir o nome, o prompt muda de acordo.

+
O exemplo a seguir mostra o comando no BrocadeSwitchA:

+
[listing]
----
BrocadeSwitchA:admin> switchname "FC_switch_A_1"
FC_switch_A_1:admin>
----
+
O exemplo a seguir mostra o comando no BrocadeSwitchB:

+
[listing]
----
BrocadeSwitchB:admin> switchname "FC_Switch_B_1"
FC_switch_B_1:admin>
----
. Defina todas as portas para seus valores padrão:
+
`portcfgdefault`

+
Isso deve ser feito para todas as portas do switch.

+
O exemplo a seguir mostra os comandos em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault 0
FC_switch_A_1:admin> portcfgdefault 1
...
FC_switch_A_1:admin> portcfgdefault 39
----
+
O exemplo a seguir mostra os comandos em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> portcfgdefault 0
FC_switch_B_1:admin> portcfgdefault 1
...
FC_switch_B_1:admin> portcfgdefault 39
----
. Limpe as informações de zoneamento:
+
`cfgdisable`

+
`cfgclear`

+
`cfgsave`

+
O exemplo a seguir mostra os comandos em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> cfgdisable
FC_switch_A_1:admin> cfgclear
FC_switch_A_1:admin> cfgsave
----
+
O exemplo a seguir mostra os comandos em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> cfgdisable
FC_switch_B_1:admin> cfgclear
FC_switch_B_1:admin> cfgsave
----
. Defina as definições gerais do interrutor como predefinição:
+
`configdefault`

+
O exemplo a seguir mostra o comando em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> configdefault
----
+
O exemplo a seguir mostra o comando em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> configdefault
----
. Defina todas as portas para o modo não entroncamento:
+
`switchcfgtrunk 0`

+
O exemplo a seguir mostra o comando em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> switchcfgtrunk 0
----
+
O exemplo a seguir mostra o comando em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> switchcfgtrunk 0
----
. Nos switches Brocade 6510, desative o recurso Brocade Virtual Fabrics (VF):
+
`fosconfig options`

+
O exemplo a seguir mostra o comando em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
----
+
O exemplo a seguir mostra o comando em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> fosconfig --disable vf
----
. Limpe a configuração do domínio administrativo (AD):
+
O exemplo a seguir mostra os comandos em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
----
+
O exemplo a seguir mostra os comandos em FC_switch_B_1:

+
[listing]
----
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
----
. Reinicie o switch:
+
`reboot`

+
O exemplo a seguir mostra o comando em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
O exemplo a seguir mostra o comando em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> reboot
----




== Configurar definições básicas do interrutor

Você deve configurar configurações globais básicas, incluindo o ID do domínio, para switches Brocade.

.Sobre esta tarefa
Esta tarefa contém etapas que devem ser executadas em cada switch em ambos os sites do MetroCluster.

Neste procedimento, você define o ID de domínio exclusivo para cada switch, como mostrado no exemplo a seguir. No exemplo, as IDs de domínio 5 e 7 formam Fabric_1 e as IDs de domínio 6 e 8 formam Fabric_2.

* FC_switch_A_1 está atribuído à ID de domínio 5
* FC_switch_A_2 está atribuído à ID de domínio 6
* FC_switch_B_1 está atribuído à ID de domínio 7
* FC_switch_B_2 está atribuído à ID de domínio 8


.Passos
. Entre no modo de configuração:
+
`configure`

. Prossiga através dos prompts:
+
.. Defina o ID do domínio para o switch.
.. Pressione *Enter* em resposta aos prompts até chegar ao "ciclo de polling RDP" e, em seguida, defina esse valor para `0` desativar a polling.
.. Pressione *Enter* até retornar ao prompt do switch.
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = 5
.
.

RSCN Transmission Mode [yes, y, no, no: [no] y

End-device RSCN Transmission Mode
 (0 = RSCN with single PID, 1 = RSCN with multiple PIDs, 2 = Fabric RSCN): (0..2) [1]
Domain RSCN To End-device for switch IP address or name change
 (0 = disabled, 1 = enabled): (0..1) [0] 1

.
.
RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
----


. Se você estiver usando dois ou mais ISLs por malha, poderá configurar a entrega em ordem (IOD) de quadros ou a entrega fora de ordem (OOD) de quadros.
+

NOTE: As configurações padrão de IOD são recomendadas. Você deve configurar ODE somente se necessário.

+
link:concept_prepare_for_the_mcc_installation.html["Considerações sobre o uso de equipamentos TDM/WDM com configurações MetroCluster conetadas à malha"]

+
.. As etapas a seguir devem ser executadas em cada malha de switch para configurar IOD de quadros:
+
... Ativar IOD:
+
`iodset`

... Defina a política Advanced Performance Tuning (APT) como 1:
+
`aptpolicy 1`

... Desativar a partilha de carga dinâmica (DLS):
+
`dlsreset`

... Verifique as configurações IOD usando os `iodshow` comandos , `aptpolicy` e `dlsshow` .
+
Por exemplo, emita os seguintes comandos no FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 1 0(ap)

    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
         0: AP Shared Link Policy
         1: AP Dedicated Link Policy
    command aptpolicy completed

    FC_switch_A_1:admin> dlsshow
    DLS is not set
----
... Repita estas etapas na segunda tela do interrutor.


.. As etapas a seguir devem ser executadas em cada malha de switch para configurar OID de quadros:
+
... Ativar OOD:
+
`iodreset`

... Defina a política Advanced Performance Tuning (APT) como 3:
+
`aptpolicy 3`

... Desativar a partilha de carga dinâmica (DLS):
+
`dlsreset`

... Verifique as configurações do AID:
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
Por exemplo, emita os seguintes comandos no FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is not set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 3 0(ap)
    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
    0: AP Shared Link Policy
    1: AP Dedicated Link Policy
    command aptpolicy completed


    FC_switch_A_1:admin> dlsshow
    DLS is set by default with current routing policy
----
... Repita estas etapas na segunda tela do interrutor.
+

NOTE: Ao configurar o ONTAP nos módulos do controlador, O AID deve ser explicitamente configurado em cada módulo do controlador na configuração do MetroCluster.

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["Configuração da entrega em ordem ou entrega fora de ordem de quadros no software ONTAP"]





. Verifique se o switch está usando o método de licenciamento de porta dinâmica.
+
.. Execute o comando license:
+
[role="tabbed-block"]
====
.Para o Fabric os 8,2.x e anteriores
--
Executar o comando `licenseport --show`.

--
.Para o Fabric os 9,0 e posterior
--
Executar o comando `license --show -port`.

--
====
+
[listing]
----
FC_switch_A_1:admin> license --show -port
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
+

NOTE: As versões do Brocade FabricOS antes de 8,0 executam os seguintes comandos como admin e as versões 8,0 e posteriores os executam como root.

.. Ative o utilizador raiz.
+
Se o usuário raiz já estiver desativado pelo Brocade, ative o usuário raiz como mostrado no exemplo a seguir:

+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. Execute o comando license:
+
`license --show -port`

+
[listing]
----
FC_switch_A_1:root> license --show -port
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Se você estiver executando o Fabric os 8,2.x e anteriores, você deve alterar o método de licença para dinâmico:
+
`licenseport --method dynamic`

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----
+

NOTE: No Fabric os 9,0 e posterior, o método de licença é dinâmico por padrão. O método de licença estática não é suportado.



. Habilite o trap para MIB T11-FC-ZONE-SERVER para fornecer monitoramento de integridade bem-sucedido dos switches no ONTAP:
+
.. Ative o MIB-SERVER-T11-FC:
+
`snmpconfig --set mibCapability -mib_name T11-FC-ZONE-SERVER-MIB -bitmask 0x3f`

.. Ative o trap T11-FC-ZONE-SERVER-MIB:
+
`snmpconfig --enable mibcapability -mib_name SW-MIB -trap_name swZoneConfigChangeTrap`

.. Repita os passos anteriores no segundo tecido do interrutor.


. *Opcional*: Se você definir a cadeia de carateres da comunidade para um valor diferente de "público", você deverá configurar os monitores de Saúde do ONTAP usando a cadeia de carateres da comunidade especificada:
+
.. Altere a cadeia de carateres existente da comunidade:
+
`snmpconfig --set snmpv1`

.. Pressione *Enter* até que você veja o texto "Comunidade (ro): [Público]".
.. Insira a string de comunidade desejada.
+
Em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm     <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]    in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_A_1:admin>
----
+
Em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm      <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]     in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_B_1:admin>
----


. Reinicie o switch:
+
`reboot`

+
Em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
Em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> reboot
----
. Ativar persistentemente o interrutor:
+
`switchcfgpersistentenable`

+
Em FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentenable
----
+
Em FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> switchcfgpersistentenable
----




== Configurar as definições básicas do interrutor num interrutor Brocade DCX 8510-8

Você deve configurar configurações globais básicas, incluindo o ID do domínio, para switches Brocade.

.Sobre esta tarefa
Você deve executar as etapas em cada switch em ambos os sites do MetroCluster. Neste procedimento, você define o ID do domínio para cada switch, conforme mostrado nos exemplos a seguir:

* FC_switch_A_1 está atribuído à ID de domínio 5
* FC_switch_A_2 está atribuído à ID de domínio 6
* FC_switch_B_1 está atribuído à ID de domínio 7
* FC_switch_B_2 está atribuído à ID de domínio 8


No exemplo anterior, as IDs de domínio 5 e 7 formam Fabric_1 e as IDs de domínio 6 e 8 formam Fabric_2.


NOTE: Você também pode usar este procedimento para configurar os switches quando você estiver usando apenas um switch DCX 8510-8 por site.

Usando este procedimento, você deve criar dois switches lógicos em cada switch Brocade DCX 8510-8. Os dois switches lógicos criados em ambos os switches Brocade DCX8510-8 formarão duas malhas lógicas, como mostrado nos exemplos a seguir:

* ESTRUTURA lógica 1: Switch1/Blade1 e lâmina Switch 2 1
* ESTRUTURA lógica 2: Switch1/Blade2 e lâmina Switch 2 2


.Passos
. Entrar no modo de comando:
+
`configure`

. Prossiga através dos prompts:
+
.. Defina o ID do domínio para o switch.
.. Continue selecionando *Enter* até chegar ao "ciclo de polling RDP" e, em seguida, defina o valor como `0` para desativar a polling.
.. Selecione *Enter* até retornar ao prompt da central.
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = `5


RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
`
----


. Repita estas etapas em todos os switches em Fabric_1 e Fabric_2.
. Configure as malhas virtuais.
+
.. Ative as malhas virtuais no switch:
+
`fosconfig --enablevf`

.. Configure o sistema para usar a mesma configuração base em todos os switches lógicos:
+
`configurechassis`

+
O exemplo a seguir mostra a saída para o `configurechassis` comando:

+
[listing]
----
System (yes, y, no, n): [no] n
cfgload attributes (yes, y, no, n): [no] n
Custom attributes (yes, y, no, n): [no] y
Config Index (0 to ignore): (0..1000) [3]:
----


. Crie e configure o switch lógico:
+
`scfg --create fabricID`

. Adicione todas as portas de um blade à malha virtual:
+
`lscfg --config fabricID -slot slot -port lowest-port - highest-port`

+

NOTE: As lâminas que formam uma malha lógica (por exemplo, Switch 1 Blade 1 e Switch 3 Blade 1) precisam ter o mesmo ID de tecido.

+
[listing]
----
setcontext fabricid
switchdisable
configure
<configure the switch per the above settings>
switchname unique switch name
switchenable
----


.Informações relacionadas
link:concept_prepare_for_the_mcc_installation.html["Requisitos para usar um switch Brocade DCX 8510-8"]



== Configuração de e-ports em switches Brocade FC usando portas FC

Para os switches Brocade nos quais os links interswitches (ISL) são configurados usando portas FC, você deve configurar as portas do switch em cada malha de switch que conetam o ISL. Essas portas ISL também são conhecidas como e-ports.

.Antes de começar
* Todos os ISLs de uma malha de switch FC devem ser configurados com a mesma velocidade e distância.
* A combinação da porta do switch e do Small Form-factor Pluggable (SFP) deve suportar a velocidade.
* A distância ISL suportada depende do modelo do switch FC.
+
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]

+
No IMT, você pode usar o campo solução de armazenamento para selecionar sua solução MetroCluster. Use o *Explorador de componentes* para selecionar os componentes e a versão do ONTAP para refinar sua pesquisa. Você pode clicar em *Mostrar resultados* para exibir a lista de configurações compatíveis que correspondem aos critérios.

* O link ISL deve ter um lambda dedicado, e o link deve ser suportado pelo Brocade para a distância, tipo de switch e sistema operacional de malha (FOS).


.Sobre esta tarefa
Você não deve usar a configuração L0 ao emitir o `portCfgLongDistance` comando. Em vez disso, você deve usar a configuração LE ou LS para configurar a distância nos switches Brocade com um mínimo de nível DE DISTÂNCIA LE.

Você não deve usar a configuração LD ao emitir o `portCfgLongDistance` comando ao trabalhar com o equipamento xWDM/TDM. Em vez disso, você deve usar a configuração LE ou LS para configurar a distância nos switches Brocade.

É necessário executar esta tarefa para cada malha de switch FC.

As tabelas a seguir mostram as portas ISL para diferentes switches e número diferente de ISLs em uma configuração executando o ONTAP 9.1 ou 9,2. Os exemplos mostrados nesta seção são para um switch Brocade 6505. Você deve modificar os exemplos para usar portas que se aplicam ao seu tipo de switch.

Você deve usar o número necessário de ISLs para sua configuração.

|===


| Modelo do interrutor | Porta de ISL | Porta do switch 


.4+| Brocade 6520 | Porta ISL 1 | 23 


| Porta ISL 2 | 47 


| Porta ISL 3 | 71 


| Porta ISL 4 | 95 


.4+| Brocade 6505 | Porta ISL 1 | 20 


| Porta ISL 2 | 21 


| Porta ISL 3 | 22 


| Porta ISL 4 | 23 


.8+| Brocade 6510 e Brocade DCX 8510-8 | Porta ISL 1 | 40 


| Porta ISL 2 | 41 


| Porta ISL 3 | 42 


| Porta ISL 4 | 43 


| Porta ISL 5 | 44 


| Porta ISL 6 | 45 


| Porta ISL 7 | 46 


| Porta ISL 8 | 47 


.6+| Brocade 7810  a| 
Porta ISL 1
 a| 
GE2 Gbps (10 Gbps)



 a| 
Porta ISL 2
 a| 
ge3 Gbps (10 Gbps)



 a| 
Porta ISL 3
 a| 
ge4 Gbps (10 Gbps)



 a| 
Porta ISL 4
 a| 
ge5 Gbps (10 Gbps)



 a| 
Porta ISL 5
 a| 
GE6 Gbps (10 Gbps)



 a| 
Porta ISL 6
 a| 
ge7 Gbps (10 Gbps)



.4+| Brocade 7840 *Nota:* o switch Brocade 7840 suporta duas portas VE de 40 Gbps ou até quatro portas VE de 10 Gbps por switch para a criação de ISLs FCIP.  a| 
Porta ISL 1
 a| 
ge0 Gbps (40 Gbps) ou GE2 Gbps (10 Gbps)



 a| 
Porta ISL 2
 a| 
ge1 Gbps (40 Gbps) ou ge3 Gbps (10 Gbps)



 a| 
Porta ISL 3
 a| 
ge10 Gbps (10 Gbps)



 a| 
Porta ISL 4
 a| 
ge11 Gbps (10 Gbps)



.4+| Brocade G610  a| 
Porta ISL 1
 a| 
20



 a| 
Porta ISL 2
 a| 
21



 a| 
Porta ISL 3
 a| 
22



 a| 
Porta ISL 4
 a| 
23



.7+| Brocade G620, G620-1, G630, G630-1, G720  a| 
Porta ISL 1
 a| 
40



 a| 
Porta ISL 2
 a| 
41



 a| 
Porta ISL 3
 a| 
42



 a| 
Porta ISL 4
 a| 
43



 a| 
Porta ISL 5
 a| 
44



 a| 
Porta ISL 6
 a| 
45



 a| 
Porta ISL 7
 a| 
46

|===
.Passos
. [[step1_Brocade_config]] Configure a velocidade da porta:
+
`portcfgspeed port-numberspeed`

+
Você deve usar a velocidade comum mais alta que é suportada pelos componentes no caminho.

+
No exemplo a seguir, existem dois ISLs para cada tecido:

+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 20 16
FC_switch_A_1:admin> portcfgspeed 21 16

FC_switch_B_1:admin> portcfgspeed 20 16
FC_switch_B_1:admin> portcfgspeed 21 16
----
. Configure o modo de entroncamento para cada ISL:
+
`portcfgtrunkport port-number`

+
** Se você estiver configurando os ISLs para entroncamento (IOD), defina o número de porta-numberport do portcfgtrunk como 1 como mostrado no exemplo a seguir:
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
----
** Se você não quiser configurar o ISL para entroncamento (OOD), defina o número portcfgtrunkport como 0 como mostrado no exemplo a seguir:
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
----


. Ative o tráfego de QoS para cada uma das portas ISL:
+
`portcfgqos --enable port-number`

+
No exemplo a seguir, há dois ISLs por malha de switch:

+
[listing]
----
FC_switch_A_1:admin> portcfgqos --enable 20
FC_switch_A_1:admin> portcfgqos --enable 21

FC_switch_B_1:admin> portcfgqos --enable 20
FC_switch_B_1:admin> portcfgqos --enable 21
----
. Verifique as configurações:
+
`portCfgShow command`

+
O exemplo a seguir mostra a saída para uma configuração que usa dois ISLs cabeados para a porta 20 e a porta 21. A configuração da porta de tronco deve estar LIGADA para IOD e desligada para OOD:

+
[listing]
----

Ports of Slot 0   12  13   14 15    16  17  18  19   20  21 22  23    24  25  26  27
----------------+---+---+---+---+-----+---+---+---+----+---+---+---+-----+---+---+---
Speed             AN  AN  AN  AN    AN  AN  8G  AN   AN  AN  16G  16G    AN  AN  AN  AN
Fill Word         0   0   0   0     0   0   3   0    0   0   3   3     3   0   0   0
AL_PA Offset 13   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Trunk Port        ..  ..  ..  ..    ..  ..  ..  ..   ON  ON  ..  ..    ..  ..  ..  ..
Long Distance     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
VC Link Init      ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked L_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked G_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Disabled E_Port   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked E_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
ISL R_RDY Mode    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
RSCN Suppressed   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Persistent Disable..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
LOS TOV enable    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
NPIV capability   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
NPIV PP Limit    126 126 126 126   126 126 126 126  126 126 126 126   126 126 126 126
QOS E_Port        AE  AE  AE  AE    AE  AE  AE  AE   AE  AE  AE  AE    AE  AE  AE  AE
Mirror Port       ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Rate Limit        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Credit Recovery   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
Fport Buffers     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Port Auto Disable ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
CSCTL mode        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..

Fault Delay       0  0  0  0    0  0  0  0   0  0  0  0    0  0  0  0
----
. Calcule a distância ISL.
+
Devido ao comportamento do FC-VI, a distância deve ser definida para 1,5 vezes a distância real com uma distância mínima de 10 km (usando o nível de distância LE).

+
A distância para o ISL é calculada da seguinte forma, arredondada para o próximo quilômetro completo:

+
1,5 x real_distance: distância

+
Se a distância for de 3 4,5 km, então 1,5 x 3 km é inferior a 10 km, portanto, o ISL deve ser definido para o nível de distância LE.

+
Se a distância for de 20 km, então 1,5 x 20 km é de 30 km. O ISL deve ser definido para 30 km e deve usar o nível de distância LS.

. Defina a distância em cada porta ISL:
+
`portcfglongdistance _portdistance-level_ vc_link_init _distance_`

+
Um `vc_link_init` valor de `1` usa a palavra de preenchimento ARB (padrão). Um valor de `0` usos OCIOSOS. O valor necessário pode depender do link que está sendo usado. Os comandos devem ser repetidos para cada porta ISL.

+
Para uma distância ISL de 3 km, conforme indicado no exemplo no passo anterior, a definição é de 4,5 km com o valor predefinido `vc_link_init` de `1`. Uma vez que uma definição de 4,5 km é inferior a 10 km, o porto tem de ser definido para o nível DE distância LE:

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LE 1

FC_switch_B_1:admin> portcfglongdistance 20 LE 1
----
+
Para uma distância ISL de 20 km, como indicado no exemplo no passo anterior, a definição é de 30 km com o valor vc_link_init predefinido de `1`:

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LS 1 -distance 30

FC_switch_B_1:admin> portcfglongdistance 20 LS 1 -distance 30
----
. Verifique a definição de distância:
+
`portbuffershow`

+
Um nível DE distância DE LE aparece como 10 km.

+
O exemplo a seguir mostra a saída para uma configuração que usa ISLs na porta 20 e na porta 21:

+
[listing]
----
FC_switch_A_1:admin> portbuffershow

User  Port     Lx      Max/Resv    Buffer Needed    Link      Remaining
Port  Type    Mode     Buffers     Usage  Buffers   Distance  Buffers
----  ----    ----     -------     ------ -------   --------- ---------
...
 20     E      -          8         67      67       30km
 21     E      -          8         67      67       30km
...
 23            -          8          0      -        -        466
----
. Verifique se ambos os switches formam uma única malha:
+
`switchshow`

+
O exemplo a seguir mostra a saída para uma configuração que usa ISLs na porta 20 e na porta 21:

+
[listing]
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Subordinate
switchDomain:       5
switchId:   fffc01
switchWwn:  10:00:00:05:33:86:89:cb
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
===========================================
...
20   20  010C00   id    16G  Online FC  LE E-Port  10:00:00:05:33:8c:2e:9a "FC_switch_B_1" (downstream)(trunk master)
21   21  010D00   id    16G  Online FC  LE E-Port  (Trunk port, master is Port 20)
...

FC_switch_B_1:admin> switchshow
switchName: FC_switch_B_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       7
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State Proto
==============================================
...
20   20  030C00   id    16G  Online  FC  LE E-Port  10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)(Trunk master)
21   21  030D00   id    16G  Online  FC  LE E-Port  (Trunk port, master is Port 20)
...
----
. Confirme a configuração dos tecidos:
+
`fabricshow`

+
[listing]
----
FC_switch_A_1:admin> fabricshow
   Switch ID   Worldwide Name      Enet IP Addr FC IP Addr Name
-----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0    "FC_switch_A_1"
3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0   >"FC_switch_B_1"
----
+
[listing]
----
FC_switch_B_1:admin> fabricshow
   Switch ID   Worldwide Name     Enet IP Addr FC IP Addr   Name
----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0     "FC_switch_A_1"

3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0    >"FC_switch_B_1
----
. [[step10_Brocade_config]]Confirme o entroncamento dos ISLs:
+
`trunkshow`

+
** Se você estiver configurando os ISLs para entroncamento (IOD), verá uma saída semelhante à seguinte:
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16
 FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16
----
** Se você não estiver configurando os ISLs para entroncamento (OOD), você verá uma saída semelhante à seguinte:
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16 MASTER
FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16 MASTER
----


. Repita <<step1_brocade_config,Passo 1>> a <<step10_brocade_config,Passo 10>> para a segunda malha de switch FC.


.Informações relacionadas
link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Atribuições de portas para switches FC ao usar o ONTAP 9.1 e posterior"]



== Configurando portas VE de 10 Gbps em switches Brocade FC 7840

Ao usar as portas VE de 10 Gbps (que usam FCIP) para ISLs, você deve criar interfaces IP em cada porta e configurar túneis e circuitos FCIP em cada túnel.

.Sobre esta tarefa
Esse procedimento deve ser executado em cada malha de switch na configuração do MetroCluster.

Os exemplos deste procedimento pressupõem que os dois switches Brocade 7840 têm os seguintes endereços IP:

* FC_switch_A_1 é local.
* FC_switch_B_1 é remoto.


.Passos
. Crie endereços de interface IP (ipif) para as portas de 10 Gbps em ambos os switches na malha:
+
`portcfg ipif FC_switch1_namefirst_port_name create FC_switch1_IP_address netmask netmask_number vlan 2 mtu auto`

+
O comando a seguir cria endereços ipif nas portas GE2.DP0 e ge3.DP0 de FC_switch_A_1:

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.71 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.71 netmask 255.255.0.0 vlan 2 mtu auto
----
+
O comando a seguir cria endereços ipif nas portas GE2.DP0 e ge3.DP0 de FC_switch_B_1:

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.72 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.72 netmask 255.255.0.0 vlan 2 mtu auto
----
. Verifique se os endereços ipif foram criados com sucesso em ambos os switches:
+
`portshow ipif all`

+
O comando a seguir mostra os endereços ipif no switch FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.71                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.71                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
O comando a seguir mostra os endereços ipif no switch FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.72                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.72                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. Crie o primeiro dos dois túneis FCIP usando as portas no DP0:
+
`portcfg fciptunnel`

+
Este comando cria um túnel com um único circuito.

+
O comando a seguir cria o túnel no switch FC_switch_A_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.71  -D 10.10.20.72 -b 10000000 -B 10000000
----
+
O comando a seguir cria o túnel no switch FC_switch_B_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.72  -D 10.10.20.71 -b 10000000 -B 10000000
----
. Verifique se os túneis FCIP foram criados com sucesso:
+
`portshow fciptunnel all`

+
O exemplo a seguir mostra que os túneis foram criados e os circuitos estão ativos:

+
[listing]
----
FC_switch_B_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
--------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. Criar um circuito adicional para DP0.
+
O seguinte comando cria um circuito no interrutor FC_switch_A_1 para DP0:

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.71 -D 10.10.21.72  --min-comm-rate 5000000 --max-comm-rate 5000000
----
+
O seguinte comando cria um circuito no interrutor FC_switch_B_1 para DP0:

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.72 -D 10.10.21.71  --min-comm-rate 5000000 --max-comm-rate 5000000
----
. Verifique se todos os circuitos foram criados com sucesso:
+
`portshow fcipcircuit all`

+
O seguinte comando mostra os circuitos e o respetivo estado:

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge2     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge3     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
--------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Configuração de portas VE de 40 Gbps em switches FC Brocade 7810 e 7840

Ao usar as duas portas VE de 40 GbE (que usam FCIP) para ISLs, você deve criar interfaces IP em cada porta e configurar túneis e circuitos FCIP em cada túnel.

.Sobre esta tarefa
Esse procedimento deve ser executado em cada malha de switch na configuração do MetroCluster.

Os exemplos deste procedimento utilizam dois interrutores:

* FC_switch_A_1 é local.
* FC_switch_B_1 é remoto.


.Passos
. Crie endereços de interface IP (ipif) para as portas de 40 Gbps em ambos os switches na malha:
+
`portcfg ipif FC_switch_namefirst_port_name create FC_switch_IP_address netmask netmask_number vlan 2 mtu auto`

+
O comando a seguir cria endereços ipif nas portas ge0.DP0 e ge1.DP0 de FC_switch_A_1:

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.82.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.82.11 netmask 255.255.0.0 vlan 2 mtu auto
----
+
O comando a seguir cria endereços ipif nas portas ge0.DP0 e ge1.DP0 de FC_switch_B_1:

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.83.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.83.11 netmask 255.255.0.0 vlan 2 mtu auto
----
. Verifique se os endereços ipif foram criados com sucesso em ambos os switches:
+
`portshow ipif all`

+
O exemplo a seguir mostra as interfaces IP em FC_switch_A_1:

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
---------------------------------------------------------------------------
-----
 ge0.dp0      10.10.82.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.82.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
O exemplo a seguir mostra as interfaces IP em FC_switch_B_1:

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge0.dp0      10.10.83.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.83.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. Crie o túnel FCIP em ambos os switches:
+
`portcfig fciptunnel`

+
O seguinte comando cria o túnel em FC_switch_A_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.82.10  -D 10.10.83.10 -b 10000000 -B 10000000
----
+
O seguinte comando cria o túnel em FC_switch_B_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.83.10  -D 10.10.82.10 -b 10000000 -B 10000000
----
. Verifique se o túnel FCIP foi criado com sucesso:
+
`portshow fciptunnel all`

+
O exemplo a seguir mostra que o túnel foi criado e os circuitos estão ativos:

+
[listing]
----
FC_switch_A_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
 --------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. Crie um circuito adicional em cada interrutor:
+
`portcfg fcipcircuit 24 create 1 -S source-IP-address -D destination-IP-address --min-comm-rate 10000000 --max-comm-rate 10000000`

+
O seguinte comando cria um circuito no interrutor FC_switch_A_1 para DP0:

+
[listing]
----
portcfg fcipcircuit 24  create 1 -S 10.10.82.11 -D 10.10.83.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
+
O seguinte comando cria um circuito no interrutor FC_switch_B_1 para dp1:

+
[listing]
----
portcfg fcipcircuit 24 create 1  -S 10.10.83.11 -D 10.10.82.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
. Verifique se todos os circuitos foram criados com sucesso:
+
`portshow fcipcircuit all`

+
O exemplo a seguir lista os circuitos e mostra que seu OpStatus está ativado:

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge0     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge1     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
 --------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Configurando as portas não-e no switch Brocade

Você deve configurar as portas não-e no switch FC. Em uma configuração MetroCluster, essas são as portas que conetam o switch aos iniciadores HBA, interconexões FC-VI e pontes FC-para-SAS. Estas etapas devem ser feitas para cada porta.

.Sobre esta tarefa
No exemplo a seguir, as portas conetam uma ponte FC-para-SAS:

--
* Porta 6 no FC_FC_switch_A_1 no local_A
* Porta 6 no FC_FC_switch_B_1 no local_B


--
.Passos
. Configure a velocidade da porta para cada porta não-e:
+
`portcfgspeed portspeed`

+
Você deve usar a velocidade comum mais alta, que é a velocidade mais alta suportada por todos os componentes no caminho de dados: O SFP, a porta do switch na qual o SFP está instalado e o dispositivo conetado (HBA, bridge, etc.).

+
Por exemplo, os componentes podem ter as seguintes velocidades suportadas:

+
** O SFP é capaz de 4, 8 ou 16 GB.
** A porta do switch é capaz de 4, 8 ou 16 GB.
** A velocidade máxima do HBA ligado é de 16 GB. A velocidade comum mais alta neste caso é de 16 GB, portanto, a porta deve ser configurada para uma velocidade de 16 GB.
+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 6 16

FC_switch_B_1:admin> portcfgspeed 6 16
----


. Verifique as configurações:
+
`portcfgshow`

+
[listing]
----
FC_switch_A_1:admin> portcfgshow

FC_switch_B_1:admin> portcfgshow
----
+
Na saída de exemplo, a porta 6 tem as seguintes configurações; a velocidade é definida como 16G:

+
[listing]
----
Ports of Slot 0                     0   1   2   3   4   5   6   7   8
-------------------------------------+---+---+---+--+---+---+---+---+--
Speed                               16G 16G 16G 16G 16G 16G 16G 16G 16G
AL_PA Offset 13                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Trunk Port                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Long Distance                       ..  ..  ..  ..  ..  ..  ..  ..  ..
VC Link Init                        ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked L_Port                       -   -   -   -   -  -   -   -   -
Locked G_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Disabled E_Port                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked E_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
ISL R_RDY Mode                      ..  ..  ..  ..  ..  ..  ..  .. ..
RSCN Suppressed                     ..  ..  ..  ..  ..  ..  ..  .. ..
Persistent Disable                  ..  ..  ..  ..  ..  ..  ..  .. ..
LOS TOV enable                      ..  ..  ..  ..  ..  ..  ..  .. ..
NPIV capability                     ON  ON  ON  ON  ON  ON  ON  ON  ON
NPIV PP Limit                       126 126 126 126 126 126 126 126 126
QOS Port                            AE  AE  AE  AE  AE  AE  AE  AE  ON
EX Port                             ..  ..  ..  ..  ..  ..  ..  ..  ..
Mirror Port                         ..  ..  ..  ..  ..  ..  ..  ..  ..
Rate Limit                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Credit Recovery                     ON  ON  ON  ON  ON  ON  ON  ON  ON
Fport Buffers                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Eport Credits                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Port Auto Disable                   ..  ..  ..  ..  ..  ..  ..  ..  ..
CSCTL mode                          ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port mode                         ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port over DWDM                    ..  ..  ..  ..  ..  ..  ..  ..  ..
FEC                                 ON  ON  ON  ON  ON  ON  ON  ON  ON
Fault Delay                         0   0   0   0   0   0   0   0   0
Non-DFE                             ..  ..  ..  ..  ..  ..  ..  ..  ..
----




== Configurando a compressão em portas ISL em um switch Brocade G620

Se você estiver usando switches Brocade G620 e habilitando a compactação nos ISLs, você deverá configurá-lo em cada e-port nos switches.

.Sobre esta tarefa
Esta tarefa tem de ser executada nas portas ISL em ambos os interrutores utilizando o ISL.

.Passos
. Desative a porta na qual você deseja configurar a compactação:
+
`portdisable port-id`

. Ativar a compressão na porta:
+
`portCfgCompress --enable port-id`

. Ative a porta para ativar a configuração com compactação:
+
`portenable port-id`

. Confirme se a definição foi alterada:
+
`portcfgshow port-id`



O exemplo a seguir habilita a compactação na porta 0.

[listing]
----
FC_switch_A_1:admin> portdisable 0
FC_switch_A_1:admin> portcfgcompress --enable 0
FC_switch_A_1:admin> portenable 0
FC_switch_A_1:admin> portcfgshow 0
Area Number: 0
Octet Speed Combo: 3(16G,10G)
(output truncated)
D-Port mode: OFF
D-Port over DWDM ..
Compression: ON
Encryption: ON
----
Você pode usar o comando islShow para verificar se o e_port está on-line com criptografia ou compactação configurada e ativa.

[listing]
----
FC_switch_A_1:admin> islshow
  1: 0-> 0 10:00:c4:f5:7c:8b:29:86   5 FC_switch_B_1
sp: 16.000G bw: 16.000G TRUNK QOS CR_RECOV ENCRYPTION COMPRESSION
----
Você pode usar o comando portEncCompShow para ver quais portas estão ativas. Neste exemplo, você pode ver que a criptografia e a compactação estão configuradas e ativas na porta 0.

[listing]
----
FC_switch_A_1:admin> portenccompshow
User	  Encryption		           Compression	         Config
Port   Configured    Active   Configured   Active  Speed
----   ----------    -------  ----------   ------  -----
  0	   Yes	          Yes	     Yes	         Yes	    16G
----


== Configuração de zoneamento em switches Brocade FC

É necessário atribuir as portas do switch a zonas separadas para separar o tráfego de armazenamento e controlador.



=== Zoneamento para portas FC-VI

Para cada grupo de DR no MetroCluster, é necessário configurar duas zonas para as conexões FC-VI que permitem tráfego de controlador para controlador. Essas zonas contêm as portas do switch FC que se conetam às portas FC-VI do módulo do controlador. Essas zonas são zonas de qualidade de Serviço (QoS).

Um nome de zona QoS começa com o prefixo QOSHid_, seguido por uma cadeia de carateres definida pelo usuário para diferenciá-la de uma zona regular. Essas zonas de QoS são as mesmas, independentemente do modelo de ponte FibreBridge que está sendo usado.

Cada zona contém todas as portas FC-VI, uma para cada cabo FC-VI de cada controlador. Essas zonas são configuradas para alta prioridade.

As tabelas a seguir mostram as zonas FC-VI para dois grupos de DR.

*Grupo DR 1 : zona FC-VI QOSH1 para porta FC-VI a / c*

|===
| Switch FC | Local | Mudar de domínio | porta 6505 / 6510 | porta 6520 | Porta G620 | Liga a... 


| FC_switch_A_1 | A | 5 | 0 | 0 | 0 | Controller_A_1 porta FC-VI a 


| FC_switch_A_1 | A | 5 | 1 | 1 | 1 | Controlador_A_1 porta FC-VI c 


| FC_switch_A_1 | A | 5 | 4 | 4 | 4 | Controller_A_2 porta FC-VI a 


| FC_switch_A_1 | A | 5 | 5 | 5 | 5 | Controlador_A_2 porta FC-VI c 


| FC_switch_B_1 | B | 7 | 0 | 0 | 0 | Controlador_B_1 porta FC-VI a 


| FC_switch_B_1 | B | 7 | 1 | 1 | 1 | Controlador_B_1 porta FC-VI c 


| FC_switch_B_1 | B | 7 | 4 | 4 | 4 | Controlador_B_2 porta FC-VI a 


| FC_switch_B_1 | B | 7 | 5 | 5 | 5 | Controlador_B_2 porta FC-VI c 
|===
|===


| Zona em tecido_1 | Portos membros 


| QOSH1_MC1_FAB_1_FCVI | 5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5 
|===
*Grupo DR 1 : zona FC-VI QOSH1 para porta FC-VI b / d*

|===
| Switch FC | Local | Mudar de domínio | porta 6505 / 6510 | porta 6520 | Porta G620 | Liga a... 


| FC_switch_A_2 | A | 6 | 0 | 0 | 0 | Controlador_A_1 porta FC-VI b 


|  |  |  | 1 | 1 | 1 | Controller_A_1 porta FC-VI d 


|  |  |  | 4 | 4 | 4 | Controlador_A_2 porta FC-VI b 


|  |  |  | 5 | 5 | 5 | Controller_A_2 porta FC-VI d 


| FC_switch_B_2 | B | 8 | 0 | 0 | 0 | Controlador_B_1 porta FC-VI b 


|  |  |  | 1 | 1 | 1 | Controlador_B_1 porta FC-VI d 


|  |  |  | 4 | 4 | 4 | Controlador_B_2 porta FC-VI b 


|  |  |  | 5 | 5 | 5 | Controlador_B_2 porta FC-VI d 
|===
|===


| Zona em tecido_1 | Portos membros 


| QOSH1_MC1_FAB_2_FCVI | 6,0;6,1;6,4;6,5;8,0;8,1;8,4;8,5 
|===
*Grupo DR 2 : zona FC-VI QOSH2 para porta FC-VI a / c*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch |  |  | Liga a... 


|  |  |  | 6510 | 6520 | G620 |  


| FC_switch_A_1 | A | 5 | 24 | 48 | 18 | Controller_A_3 porta FC-VI a 


|  |  |  | 25 | 49 | 19 | Controlador_A_3 porta FC-VI c 


|  |  |  | 28 | 52 | 22 | Controller_A_4 porta FC-VI a 


|  |  |  | 29 | 53 | 23 | Controlador_A_4 porta FC-VI c 


| FC_switch_B_1 | B | 7 | 24 | 48 | 18 | Controlador_B_3 porta FC-VI a 


|  |  |  | 25 | 49 | 19 | Controlador_B_3 porta FC-VI c 


|  |  |  | 28 | 52 | 22 | Controlador_B_4 porta FC-VI a 


|  |  |  | 29 | 53 | 23 | Controlador_B_4 porta FC-VI c 
|===
|===


| Zona em tecido_1 | Portos membros 


| QOSH2_MC2_FAB_1_FCVI (6510) | 5,24;5,25;5,28;5,29;7,24;7,25;7,28;7,29 


| QOSH2_MC2_FAB_1_FCVI (6520) | 5,48;5,49;5,52;5,53;7,48;7,49;7,52;7,53 
|===
*Grupo DR 2 : zona FC-VI QOSH2 para porta FC-VI b / d*

|===
| Switch FC | Local | Mudar de domínio | porta 6510 | porta 6520 | Porta G620 | Liga a... 


| FC_switch_A_2 | A | 6 | 24 | 48 | 18 | Controlador_A_3 porta FC-VI b 


| FC_switch_A_2 | A | 6 | 25 | 49 | 19 | Controller_A_3 porta FC-VI d 


| FC_switch_A_2 | A | 6 | 28 | 52 | 22 | Controlador_A_4 porta FC-VI b 


| FC_switch_A_2 | A | 6 | 29 | 53 | 23 | Controller_A_4 porta FC-VI d 


| FC_switch_B_2 | B | 8 | 24 | 48 | 18 | Controlador_B_3 porta FC-VI b 


| FC_switch_B_2 | B | 8 | 25 | 49 | 19 | Controlador_B_3 porta FC-VI d 


| FC_switch_B_2 | B | 8 | 28 | 52 | 22 | Controlador_B_4 porta FC-VI b 


| FC_switch_B_2 | B | 8 | 29 | 53 | 23 | Controlador_B_4 porta FC-VI d 
|===
|===


| Zona em tecido_2 | Portos membros 


| QOSH2_MC2_FAB_2_FCVI (6510) | 6,24;6,25;6,28;6,29;8,24;8,25;8,28;8,29 


| QOSH2_MC2_FAB_2_FCVI (6520) | 6,48;6,49;6,52;6,53;8,48;8,49;8,52;8,53 
|===
A tabela a seguir mostra um resumo das zonas FC-VI:

|===


| Malha | Nome da zona | Portos membros 


.3+| FC_switch_A_1 e FC_switch_B_1  a| 
QOSH1_MC1_FAB_1_FCVI
 a| 
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5



 a| 
QOSH2_MC1_FAB_1_FCVI ( 6510)
 a| 
5,24;5,25;5,28;5,29;7,24;7,25;7,28;7,29



 a| 
QOSH2_MC1_FAB_1_FCVI (6520)
 a| 
5,48;5,49;5,52;5,53;7,48;7,49;7,52;7,53



.3+| FC_switch_A_2 e FC_switch_B_2  a| 
QOSH1_MC1_FAB_2_FCVI
 a| 
6,0;6,1;6,4;6,5;8,0;8,1;8,4;8,5



 a| 
QOSH2_MC1_FAB_2_FCVI (6510)
 a| 
6,24;6,25;6,28;6,29;8,24;8,25;8,28;8,29



 a| 
QOSH2_MC1_FAB_2_FCVI (6520)
 a| 
6,48;6,49;6,52;6,53;8,48;8,49;8,52;8,53

|===


=== Zoneamento para pontes FibreBridge 7500N ou 7600N usando uma porta FC

Se você estiver usando bridges do FibreBridge 7500N ou 7600N usando apenas uma das duas portas FC, será necessário criar zonas de armazenamento para as portas de ponte. Você deve entender as zonas e as portas associadas antes de configurar as zonas.

Os exemplos mostram zoneamento apenas para o grupo DR 1. Se sua configuração incluir um segundo grupo de DR, configure o zoneamento para o segundo grupo de DR da mesma maneira, usando as portas correspondentes dos controladores e bridges.



==== Zonas necessárias

É necessário configurar uma zona para cada uma das portas FC de ponte FC para SAS que permita tráfego entre iniciadores em cada módulo de controladora e essa ponte FC para SAS.

Cada zona de armazenamento contém nove portas:

* Oito portas do iniciador HBA (duas conexões para cada controlador)
* Uma porta que se conecta a uma porta FC em ponte FC FC de FC para SAS


As zonas de armazenamento usam zoneamento padrão.

Os exemplos mostram dois pares de pontes conetando dois grupos de pilha em cada local. Como cada ponte usa uma porta FC, há um total de quatro zonas de storage por malha (oito no total).



==== Nomenclatura da ponte

As bridges usam o seguinte exemplo de nomeação: bridge_site_stack grouplocation em par

|===


| Esta parte do nome... | Identifica o... | Valores possíveis... 


 a| 
local
 a| 
Local no qual o par de pontes reside fisicamente.
 a| 
A ou B



 a| 
grupo de pilha
 a| 
Número do grupo de pilha ao qual o par de ponte se coneta.

FibreBridge 7600N ou 7500N bridges suportam até quatro stacks no grupo stack.

O grupo de stack não pode conter mais de 10 gavetas de storage.
 a| 
1, 2, etc.



 a| 
localização em par
 a| 
Ponte dentro do par de ponte.Um par de pontes se coneta a um grupo de pilha específico.
 a| 
a ou b

|===
Exemplos de nomes de bridge para um grupo de pilha em cada local:

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b




==== Grupo DR 1 - pilha 1 no local_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 5 | 2 | Controlador_A_1 porta 0a 


| FC_switch_A_1 | A | 5 | 3 | Controlador_A_1 porta 0C 


| FC_switch_A_1 | A | 5 | 6 | Controlador_A_2 porta 0a 


| FC_switch_A_1 | A | 5 | 7 | Controlador_A_2 porta 0C 


| FC_switch_A_1 | A | 5 | 8 | bridge_A_1a FC1 


| FC_switch_B_1 | B | 7 | 2 | Controlador_B_1 porta 0a 


| FC_switch_B_1 | B | 7 | 3 | Controlador_B_1 porta 0C 


| FC_switch_B_1 | B | 7 | 6 | Controlador_B_2 porta 0a 


| FC_switch_B_1 | B | 7 | 7 | Controlador_B_2 porta 0C 
|===
|===


| Zona em tecido_1 | Portos membros 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,8 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 6 | 2 | Controlador_A_1 porta 0b 


| FC_switch_A_1 | A | 6 | 3 | Controlador_A_1 porta 0d 


| FC_switch_A_1 | A | 6 | 6 | Controlador_A_2 porta 0b 


| FC_switch_A_1 | A | 6 | 7 | Controlador_A_2 porta 0d 


| FC_switch_A_1 | A | 6 | 8 | bridge_A_1b FC1 


| FC_switch_B_1 | B | 8 | 2 | Controlador_B_1 porta 0b 


| FC_switch_B_1 | B | 8 | 3 | Controlador_B_1 porta 0d 


| FC_switch_B_1 | B | 8 | 6 | Controlador_B_2 porta 0b 


| FC_switch_B_1 | B | 8 | 7 | Controlador_B_2 porta 0d 
|===
|===


| Zona em tecido_2 | Portos membros 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,8 
|===


==== Grupo DR 1 - pilha 2 no local_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 5 | 2 | Controlador_A_1 porta 0a 


| FC_switch_A_1 | A | 5 | 3 | Controlador_A_1 porta 0C 


| FC_switch_A_1 | A | 5 | 6 | Controlador_A_2 porta 0a 


| FC_switch_A_1 | A | 5 | 7 | Controlador_A_2 porta 0C 


| FC_switch_A_1 | A | 5 | 9 | bridge_A_2a FC1 


| FC_switch_B_1 | B | 7 | 2 | Controlador_B_1 porta 0a 


| FC_switch_B_1 | B | 7 | 3 | Controlador_B_1 porta 0C 


| FC_switch_B_1 | B | 7 | 6 | Controlador_B_2 porta 0a 


| FC_switch_B_1 | B | 7 | 7 | Controlador_B_2 porta 0C 
|===
|===


| Zona em tecido_1 | Portos membros 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,9 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 6 | 2 | Controlador_A_1 porta 0b 


| FC_switch_A_1 | A | 6 | 3 | Controlador_A_1 porta 0d 


| FC_switch_A_1 | A | 6 | 6 | Controlador_A_2 porta 0b 


| FC_switch_A_1 | A | 6 | 7 | Controlador_A_2 porta 0d 


| FC_switch_A_1 | A | 6 | 9 | bridge_A_2b FC1 


| FC_switch_B_1 | B | 8 | 2 | Controlador_B_1 porta 0b 


| FC_switch_B_1 | B | 8 | 3 | Controlador_B_1 porta 0d 


| FC_switch_B_1 | B | 8 | 6 | Controlador_B_2 porta 0b 


| FC_switch_B_1 | B | 8 | 7 | Controlador_B_2 porta 0d 
|===
|===


| Zona em tecido_2 | Portos membros 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,9 
|===


==== Grupo DR 1 - pilha 1 no local_B

*MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Interrutor Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 5 | 2 | Controlador_A_1 porta 0a 


| FC_switch_A_1 | A | 5 | 3 | Controlador_A_1 porta 0C 


| FC_switch_A_1 | A | 5 | 6 | Controlador_A_2 porta 0a 


| FC_switch_A_1 | A | 5 | 7 | Controlador_A_2 porta 0C 


| FC_switch_B_1 | B | 7 | 2 | Controlador_B_1 porta 0a 


| FC_switch_B_1 | B | 7 | 3 | Controlador_B_1 porta 0C 


| FC_switch_B_1 | B | 7 | 6 | Controlador_B_2 porta 0a 


| FC_switch_B_1 | B | 7 | 7 | Controlador_B_2 porta 0C 


| FC_switch_B_1 | B | 7 | 8 | bridge_B_1a FC1 
|===
|===


| Zona em tecido_1 | Portos membros 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,8 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Interrutor Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 6 | 2 | Controlador_A_1 porta 0b 


| FC_switch_A_1 | A | 6 | 3 | Controlador_A_1 porta 0d 


| FC_switch_A_1 | A | 6 | 6 | Controlador_A_2 porta 0b 


| FC_switch_A_1 | A | 6 | 7 | Controlador_A_2 porta 0d 


| FC_switch_B_1 | B | 8 | 2 | Controlador_B_1 porta 0b 


| FC_switch_B_1 | B | 8 | 3 | Controlador_B_1 porta 0d 


| FC_switch_B_1 | B | 8 | 6 | Controlador_B_2 porta 0b 


| FC_switch_B_1 | B | 8 | 7 | Controlador_B_2 porta 0d 


| FC_switch_B_1 | B | 8 | 8 | bridge_B_1b FC1 
|===
|===


| Zona em tecido_2 | Portos membros 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;8,8 
|===


==== Grupo DR 1 - pilha 2 no local_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 5 | 2 | Controlador_A_1 porta 0a 


| FC_switch_A_1 | A | 5 | 3 | Controlador_A_1 porta 0C 


| FC_switch_A_1 | A | 5 | 6 | Controlador_A_2 porta 0a 


| FC_switch_A_1 | A | 5 | 7 | Controlador_A_2 porta 0C 


| FC_switch_B_1 | B | 7 | 2 | Controlador_B_1 porta 0a 


| FC_switch_B_1 | B | 7 | 3 | Controlador_B_1 porta 0C 


| FC_switch_B_1 | B | 7 | 6 | Controlador_B_2 porta 0a 


| FC_switch_B_1 | B | 7 | 7 | Controlador_B_2 porta 0C 


| FC_switch_B_1 | B | 7 | 9 | bridge_b_2a FC1 
|===
|===


| Zona em tecido_1 | Portos membros 


| MC1_INIT_GRP_1_SITE_b_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,9 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1:*

|===
| Switch FC | Local | Mudar de domínio | Porta do switch Brocade 6505, 6510, 6520, G620 ou G610 | Liga a... 


| FC_switch_A_1 | A | 6 | 2 | Controlador_A_1 porta 0b 


| FC_switch_A_1 | A | 6 | 3 | Controlador_A_1 porta 0d 


| FC_switch_A_1 | A | 6 | 6 | Controlador_A_2 porta 0b 


| FC_switch_A_1 | A | 6 | 7 | Controlador_A_2 porta 0d 


| FC_switch_B_1 | B | 8 | 2 | Controlador_B_1 porta 0b 


| FC_switch_B_1 | B | 8 | 3 | Controlador_B_1 porta 0d 


| FC_switch_B_1 | B | 8 | 6 | Controlador_B_2 porta 0b 


| FC_switch_B_1 | B | 8 | 7 | Controlador_B_2 porta 0d 


| FC_switch_B_1 | B | 8 | 9 | bridge_B_1b FC1 
|===
|===


| Zona em tecido_2 | Portos membros 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,9 
|===


==== Resumo das zonas de armazenamento

|===


| Malha | Nome da zona | Portos membros 


.4+| FC_switch_A_1 e FC_switch_B_1 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,9 


.4+| FC_switch_A_2 e FC_switch_B_2 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,9 
|===


=== Zoneamento para pontes FibreBridge 7500N usando ambas as portas FC

Se você estiver usando bridges do FibreBridge 7500N com ambas as portas FC, será necessário criar zonas de armazenamento para as portas de ponte. Você deve entender as zonas e as portas associadas antes de configurar as zonas.



==== Zonas necessárias

É necessário configurar uma zona para cada uma das portas FC de ponte FC para SAS que permita tráfego entre iniciadores em cada módulo de controladora e essa ponte FC para SAS.

Cada zona de armazenamento contém cinco portas:

* Quatro portas do iniciador HBA (uma conexão para cada controlador)
* Uma porta que se conecta a uma porta FC em ponte FC FC de FC para SAS


As zonas de armazenamento usam zoneamento padrão.

Os exemplos mostram dois pares de pontes conetando dois grupos de pilha em cada local. Como cada ponte usa uma porta FC, há um total de oito zonas de storage por malha (dezesseis no total).



==== Nomenclatura da ponte

As bridges usam o seguinte exemplo de nomeação: bridge_site_stack grouplocation em par

|===


| Esta parte do nome... | Identifica o... | Valores possíveis... 


 a| 
local
 a| 
Local no qual o par de pontes reside fisicamente.
 a| 
A ou B



 a| 
grupo de pilha
 a| 
Número do grupo de pilha ao qual o par de ponte se coneta.

FibreBridge 7600N ou 7500N bridges suportam até quatro stacks no grupo stack.

O grupo de stack não pode conter mais de 10 gavetas de storage.
 a| 
1, 2, etc.



 a| 
localização em par
 a| 
Ponte dentro do par de pontes. Um par de bridges se coneta a um grupo de pilha específico.
 a| 
a ou b

|===
Exemplos de nomes de bridge para um grupo de pilha em cada local:

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b




==== Grupo DR 1 - pilha 1 no local_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | 6505 / 6510 / G610 / G620 porta | porta 6520 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0a



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0a



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
8
 a| 
8
 a| 
bridge_A_1a FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0a

|===
|===


| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0C



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0C



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0C

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,9

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1:*

|===


| Switch FC | Local | Mudar de domínio | 6505 / 6510 / G610 | 6520 | G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
8
 a| 
8
 a| 
8
 a| 
bridge_A_1a FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0b

|===
|===


| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | 6505 / 6510 / G610 | 6520 | G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0d

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,9

|===


==== Grupo DR 1 - pilha 2 no local_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0a



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0a



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_A_2a FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0a

|===
|===


| Zona em tecido_1 hh | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0C



| FC_switch_A_1  a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0C



| FC_switch_A_1  a| 
A
 a| 
5
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_A_2b FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0C

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,11

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
0
 a| 
0
 a| 
Controlador_A_1 porta 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
4
 a| 
4
 a| 
Controlador_A_2 porta 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_A_2a FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0b

|===
|===


| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_A_2b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0d

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,11

|===


==== Grupo DR 1 - pilha 1 no local_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0a



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
8
 a| 
Controlador_B_1 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
2
 a| 
Controlador_B_2 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
8
 a| 
8
 a| 
6
 a| 
bridge_B_1a FC1

|===
|===


| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0C



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
9
 a| 
Controlador_B_1 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
3
 a| 
Controlador_B_2 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
9
 a| 
9
 a| 
7
 a| 
bridge_B_1b FC1

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,9

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
bridge_B_1a FC2

|===
|===
| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC2

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,9

|===


==== Grupo DR 1 - pilha 2 no local_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0a



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_B_2a FC1

|===
|===


| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0C



 a| 
FC_switch_A_1
 a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0C



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_B_2b FC1

|===
|===


| Zona em tecido_2 hh | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,11

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_A_1 porta 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_A_2 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controlador_B_1 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controlador_B_2 porta 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_B_2a FC2

|===
|===


| Zona em tecido_1 | Portos membros 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2:*

|===


| Switch FC | Local | Mudar de domínio | Porta 6505 / 6510 / G610 | porta 6520 | Porta G620 | Liga a... 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_A_1 porta 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_A_2 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controlador_B_1 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controlador_B_2 porta 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_B_2b FC2

|===
|===


| Zona em tecido_2 | Portos membros 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,11

|===


==== Resumo das zonas de armazenamento

|===


| Malha | Nome da zona | Portos membros 


 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,8



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,9



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,10



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,11



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,8



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,9



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,10



 a| 
FC_switch_A_1 e FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,11



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,8



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,9



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,10



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,11



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,8



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,9



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,10



 a| 
FC_switch_A_2 e FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,11

|===


=== Configuração de zoneamento em switches Brocade FC

É necessário atribuir as portas do switch a zonas separadas para separar o tráfego de storage e controlador, com zonas para as portas FC-VI e zonas para as portas de storage.

.Sobre esta tarefa
As etapas a seguir usam o zoneamento padrão para a configuração do MetroCluster.

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Zoneamento para portas FC-VI"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Zoneamento para pontes FibreBridge 7500N ou 7600N usando uma porta FC"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Zoneamento para pontes FibreBridge 7500N usando ambas as portas FC"]

.Passos
. Crie as zonas FC-VI em cada switch:
+
`zonecreate "QOSH1_FCVI_1", member;member ...`

+
Neste exemplo, é criada uma zona FCVI DE QOS contendo as portas 5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5:

+
[listing]
----
Switch_A_1:admin> zonecreate "QOSH1_FCVI_1", "5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5"
----
. Configure as zonas de armazenamento em cada switch.
+
Você pode configurar o zoneamento para a malha a partir de um switch na malha. No exemplo a seguir, o zoneamento é configurado no Switch_A_1.

+
.. Crie a zona de armazenamento para cada domínio do switch na malha do switch:
+
`zonecreate name, member;member ...`

+
Neste exemplo, uma zona de armazenamento para um FibreBridge 7500N usando ambas as portas FC está sendo criada. As zonas contêm as portas 5,2;5,6;7,2;7,6;5,16:

+
[listing]
----
Switch_A_1:admin> zonecreate "MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1", "5,2;5,6;7,2;7,6;5,16"
----
.. Crie a configuração na primeira malha de switch:
+
`cfgcreate config_name, zone;zone...`

+
Neste exemplo, é criada uma configuração com o nome CFG_1 e as duas zonas QOSH1_MC1_FAB_1_FCVI e MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1

+
[listing]
----
Switch_A_1:admin> cfgcreate "CFG_1", "QOSH1_MC1_FAB_1_FCVI; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1"
----
.. Adicione zonas à configuração, se desejar:
+
`cfgadd config_namezone;zone...`

.. Ativar a configuração:
+
`cfgenable config_name`

+
[listing]
----
Switch_A_1:admin> cfgenable "CFG_1"
----
.. Guardar a configuração:
+
`cfgsave`

+
[listing]
----
Switch_A_1:admin> cfgsave
----
.. Valide a configuração de zoneamento:
+
`zone --validate`

+
[listing]
----
Switch_A_1:admin> zone --validate
Defined configuration:
cfg: CFG_1 QOSH1_MC1_FAB_1_FCVI ; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
zone: QOSH1_MC1_FAB_1_FCVI
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2;5,6;7,2;7,6;5,16
Effective configuration:
cfg: CFG_1
zone: QOSH1_MC1_FAB_1_FCVI
5,0
5,1
5,4
5,5
7,0
7,1
7,4
7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2
5,6
7,2
7,6
5,16
------------------------------------
~ - Invalid configuration
* - Member does not exist
# - Invalid usage of broadcast zone
----






== Definição da encriptação ISL em comutadores Brocade 6510 ou G620

Nos switches Brocade 6510 ou G620, você pode usar opcionalmente o recurso de criptografia Brocade nas conexões ISL. Se você quiser usar o recurso de criptografia, execute etapas de configuração adicionais em cada switch na configuração do MetroCluster.

.Antes de começar
* Você deve ter switches Brocade 6510 ou G620.
+

NOTE: O suporte para criptografia ISL em switches Brocade G620 só é suportado no ONTAP 9.4 e posterior.

* Você deve ter selecionado dois switches da mesma malha.
* Você deve ter revisado a documentação do Brocade para a versão do sistema operacional de malha e switch para confirmar os limites de largura de banda e porta.


.Sobre esta tarefa
As etapas devem ser executadas em ambos os switches na mesma malha.



=== Desativação da malha virtual

Para definir a criptografia ISL, você deve desativar a malha virtual em todos os quatro switches que estão sendo usados em uma configuração do MetroCluster.

.Passos
. Desative a malha virtual digitando o seguinte comando no console do switch:
+
`fosconfig --disable vf`

. Reinicie o switch.




=== Definir a carga útil

Após desativar a malha virtual, você deve definir a carga útil ou o tamanho do campo de dados em ambos os switches da malha.

.Sobre esta tarefa
O tamanho do campo de dados não deve exceder 2048.

.Passos
. Desativar o interrutor:
+
`switchdisable`

. Configure e defina a carga útil:
+
`configure`

. Defina os seguintes parâmetros do interrutor:
+
.. Defina o parâmetro Fabric da seguinte forma: `y`
.. Defina os outros parâmetros, como domínio, PID persistente baseado em WWN, e assim por diante.
.. Defina o tamanho do campo de dados: `2048`






=== Definir a política de autenticação

Você deve definir a política de autenticação e os parâmetros associados.

.Sobre esta tarefa
Os comandos devem ser executados no console do switch.

.Passos
. Defina o segredo de autenticação:
+
.. Inicie o processo de configuração:
+
`secAuthSecret --set`

+
Este comando inicia uma série de prompts que você responde nas seguintes etapas:

.. Forneça o nome mundial (WWN) do outro switch na malha para o parâmetro "Enter peer WWN, Domain ou switch name".
.. Forneça o segredo do par para o parâmetro "Enter peer secret".
.. Forneça o segredo local para o parâmetro "Enter local secret".
.. Introduza `Y` para o parâmetro "are you done".
+
--
O seguinte é um exemplo de configuração do segredo de autenticação:

[listing]
----
brcd> secAuthSecret --set

This command is used to set up secret keys for the DH-CHAP authentication.
The minimum length of a secret key is 8 characters and maximum 40
characters. Setting up secret keys does not initiate DH-CHAP
authentication. If switch is configured to do DH-CHAP, it is performed
whenever a port or a switch is enabled.

Warning: Please use a secure channel for setting secrets. Using
an insecure channel is not safe and may compromise secrets.

Following inputs should be specified for each entry.

1. WWN for which secret is being set up.
2. Peer secret: The secret of the peer that authenticates to peer.
3. Local secret: The local secret that authenticates peer.

Press enter to start setting up secrets > <cr>

Enter peer WWN, Domain, or switch name (Leave blank when done): 10:00:00:05:33:76:2e:99
Enter peer secret: <hidden>
Re-enter peer secret: <hidden>
Enter local secret: <hidden>
Re-enter local secret: <hidden>

Enter peer WWN, Domain, or switch name (Leave blank when done):
Are you done? (yes, y, no, n): [no] yes
Saving data to key store... Done.
----
--


. Defina o grupo de autenticação como 4:
+
`authUtil --set -g 4`

. Defina o tipo de autenticação como "dhchap":
+
`authUtil --set -a dhchap`

+
O sistema exibe a seguinte saída:

+
[listing]
----
Authentication is set to dhchap.
----
. Defina a política de autenticação no switch como On (ligado):
+
`authUtil --policy -sw on`

+
O sistema exibe a seguinte saída:

+
[listing]
----
Warning: Activating the authentication policy requires either DH-CHAP secrets or PKI certificates depending on the protocol selected. Otherwise, ISLs will be segmented during next E-port bring-up.
ARE YOU SURE  (yes, y, no, n): [no] yes
Auth Policy is set to ON
----




=== Ativar a encriptação ISL em comutadores Brocade

Depois de definir a política de autenticação e o segredo de autenticação, você deve ativar a criptografia ISL nas portas para que ela entre em vigor.

.Sobre esta tarefa
* Essas etapas devem ser executadas em uma malha de switch de cada vez.
* Os comandos devem ser executados no console do switch.


.Passos
. Ativar encriptação em todas as portas ISL:
+
`portCfgEncrypt --enable port_number`

+
No exemplo a seguir, a criptografia é ativada nas portas 8 e 12:

+
`portCfgEncrypt --enable 8`

+
`portCfgEncrypt --enable 12`

. Ativar o interrutor:
+
`switchenable`

. Verifique se o ISL está funcionando e funcionando:
+
`islshow`

. Verifique se a criptografia está ativada:
+
`portenccompshow`

+
O exemplo a seguir mostra que a criptografia está habilitada nas portas 8 e 12:

+
[listing]
----

User Encryption
Port  configured     Active
----   ----------    ------
 8      yes          yes
 9      No           No
 10     No           No
 11     No           No
 12     yes          yes
----


.O que fazer a seguir
Execute todas as etapas nos switches na outra malha em uma configuração do MetroCluster.
