---
permalink: install-fc/task_cable_storage_arrays_to_fc_switches_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, storage, arrays, fc, switches, configuration 
summary: É necessário conectar storage arrays a switches FC para que os sistemas ONTAP na configuração MetroCluster possam acessar um LUN de array específico por pelo menos dois caminhos. 
---
= Cabeamento de storage arrays para switches FC em uma configuração MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É necessário conectar storage arrays a switches FC para que os sistemas ONTAP na configuração MetroCluster possam acessar um LUN de array específico por pelo menos dois caminhos.

.Antes de começar
* Os storage arrays devem ser configurados para apresentar LUNs de array ao ONTAP.
* Os controladores ONTAP devem ser conectados aos switches FC.
* Os ISLs devem ser cabeados entre os switches FC nos locais do MetroCluster.
* Você deve repetir essa tarefa para cada storage array em ambos os sites do MetroCluster.
* É necessário conectar os controladores em uma configuração MetroCluster aos storage arrays por meio de switches FC.


.Passos
. Conecte as portas do storage array às portas do switch FC.
+
Em cada local, conecte os pares de portas redundantes no storage array a switches FC em malhas alternativas. Isso fornece redundância nos caminhos para acessar os LUNs do array.



.Informações relacionadas
* A configuração do zoneamento de switch permite definir quais LUNs de array podem ser visualizados por um sistema ONTAP específico na configuração do MetroCluster.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["Zoneamento de switch em uma configuração MetroCluster com LUNs de array"]

* Em uma configuração MetroCluster com LUNs de array, você precisa conectar as portas de storage array que formam um par de portas redundante a switches FC alternativos.
+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_two_node_mcc_configuration.html["Exemplo de cabeamento de portas de storage array para switches FC em uma configuração de MetroCluster de dois nós"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_mcc_configuration.html["Exemplo de cabeamento de portas de storage array para switches FC em uma configuração de MetroCluster de quatro nós"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_mcc_configuration.html["Exemplo de cabeamento de portas de storage array para switches FC em uma configuração de MetroCluster de oito nós"]


