---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= Novidades nos recursos do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada versão do software de gerenciamento de dados ONTAP 9 oferece recursos novos e aprimorados que melhoram os recursos, a capacidade de gerenciamento e o desempenho das configurações do ONTAP MetroCluster.

Para obter detalhes sobre problemas conhecidos, limitações e precauções de atualização que afetam as configurações do ONTAP MetroCluster, consulte o https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Notas de versão"^]. Você deve entrar com sua conta do NetApp ou criar uma conta para acessar as Notas de versão.

[cols="20,65,15"]
|===
| Recursos suportados na configuração do MetroCluster | Descrição e onde saber mais | Disponível a partir do início 


 a| 
SnapMirror cloud support para MetroCluster FlexGroup volumes
 a| 
SnapMirror cloud oferece suporte a operações de backup e restauração para volumes FlexGroup em configurações MetroCluster.

link:https://docs.netapp.com/us-en/ontap/data-protection/cloud-backup-with-snapmirror-task.html#delete-a-snapmirror-cloud-relationship["Faça backup de dados na nuvem usando ONTAP SnapMirror"^]
 a| 
ONTAP 9.18.1GA



 a| 
Novas combinações de atualização suportadas para MetroCluster atualizações de controladores IP usando  `system controller replace` comandos
 a| 
Adiciona suporte para atualização de um AFF A70 para um AFF A90 ou de um FAS70 para um FAS90 usando  `system controller replace` comandos em uma configuração IP MetroCluster.

link:../upgrade/upgrade-mcc-ip-system-controller-replace.html["Atualizar controladores em IP MetroCluster de quatro nós usando switchover e switchback com comandos "System controller replace" (ONTAP 9.13,1 e posterior)"]
 a| 
ONTAP 9.18.1GA



 a| 
Suporte a Flash Cache para sistemas FAS50 em configurações IP MetroCluster.
 a| 
O Flash Cache é suportado em sistemas FAS50 em configurações IP MetroCluster .

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["Atribuição de disco em sistemas FAS50 com Flash Cache"]
 a| 
ONTAP 9.18.1



 a| 
Suporte IP MetroCluster para criptografia de ponta a ponta
 a| 
A criptografia de ponta a ponta é suportada nos seguintes sistemas para criptografar o tráfego de back-end, como NVlog e dados de replicação de armazenamento, entre os sites em uma configuração de IP do MetroCluster .

* AFF A800, AFF C800
* AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
* AFF A70, AFF A90, AFF A1K, AFF C80
* FAS50, FAS70, FAS90


link:../maintain/task-configure-encryption.html["Configurar criptografia de ponta a ponta em uma configuração IP do MetroCluster"]
 a| 
ONTAP 9.17.1



 a| 
Limite de alterações para configurações de IP do MetroCluster
 a| 
O ONTAP 9.17.1 inclui as seguintes atualizações de limite para configurações de IP do MetroCluster de quatro nós:

* Os sistemas AFF C800, AFF A800, AFF A900, AFF A90 e AFF A1K têm os seguintes limites atualizados:
+
** Limites de FlexVol volume por nó: 1250
** Limites de SVM: 64 SVMs por cluster
** Contagem de LIF: 256 LIFs por cluster


* Os sistemas AFF A400, AFF C400, ASA A400, ASA C400, AFF C80, AFF A70 e AFF A50 têm os seguintes limites atualizados:
+
** Limites de FlexVol volume por agregado (único ou múltiplo): 625
** Limites de FlexVol volume por nó: 1250
** Limites de FlexVol volume por par de alta disponibilidade (HA): 2500
** Limites de FlexVol volume por cluster: 5000
** Limites de SVM: 64 SVMs por cluster
** Contagem de LIF: 256 LIFs por cluster




Consulte o link:https://hwu.netapp.com["Hardware Universe"^] para maiores informações.
 a| 
ONTAP 9.17.1



 a| 
Atualização de firmware FibreBridge usando credenciais
 a| 
Você pode atualizar o firmware em pontes FibreBridge usando credenciais se elas forem exigidas pelo servidor para baixar o pacote de firmware.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["Atualize o firmware em uma ponte FibreBridge"]
 a| 
ONTAP 9.16,1



 a| 
Suporte de mobilidade de dados SVM para migração de configurações do MetroCluster
 a| 
O ONTAP é compatível com as seguintes migrações do MetroCluster SVM:

* Migração de um SVM entre um par de HA que não seja da MetroCluster e uma configuração MetroCluster IP
* Migração de um SVM entre duas configurações de MetroCluster IP
* Migração de um SVM entre uma configuração de MetroCluster FC e uma configuração de MetroCluster IP


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["Mobilidade de dados do SVM"^]
 a| 
ONTAP 9.16,1



 a| 
Suporte de autenticação MD5.1X para grupos de pares BGP
 a| 
O ONTAP suporta autenticação MD5 em grupos de pares BGP para proteger sessões BGP. Quando o MD5 está ativado, as sessões de BGP só podem ser estabelecidas e processadas entre pares autorizados, evitando possíveis interrupções da sessão por um ator não autorizado.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Configurar LIFs de IP virtual (VIP)"^]
 a| 
ONTAP 9.16,1



 a| 
Suporte IP MetroCluster para criptografia de ponta a ponta
 a| 
A criptografia de ponta a ponta é suportada nos sistemas AFF A400, AFF C400, FAS8300 e FAS8700 para criptografar o tráfego de back-end, como NVlog e dados de replicação de armazenamento, entre os sites em uma configuração IP MetroCluster .

link:../maintain/task-configure-encryption.html["Configurar criptografia de ponta a ponta em uma configuração IP do MetroCluster"]
 a| 
ONTAP 9.15,1



 a| 
Aumento do limite de volume para configurações de IP MetroCluster de quatro nós em sistemas AFF A800 e AFF C800
 a| 
Nas configurações IP do MetroCluster de quatro nós, os seguintes limites de volume para sistemas AFF A800 e AFF C800 aumentaram:

* O número máximo de volumes FlexVol por agregado aumentou de 200 para 625.
* O número máximo de volumes FlexVol por nó aumentou de 800 para 1250.
* O número máximo de volumes FlexVol por par de HA aumentou de 1.600 para 2.500.

 a| 
ONTAP 9.15,1



 a| 
Compatibilidade com MetroCluster IP para NVMe
 a| 
O protocolo de host front-end NVMe/TCP é compatível com configurações IP MetroCluster de quatro nós.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurações DE SAN em um ambiente MetroCluster"^]
 a| 
ONTAP 9.15,1



 a| 
Aumento do limite de volume para configurações de IP MetroCluster de quatro nós em sistemas AFF A900
 a| 
Nas configurações IP do MetroCluster de quatro nós, os seguintes limites de volume para sistemas AFF A900 aumentaram:

* O número máximo de volumes FlexVol por agregado aumentou de 200 para 625.
* O número máximo de volumes FlexVol por nó aumentou de 800 para 1250.
* O número máximo de volumes FlexVol por par de HA aumentou de 1.600 para 2.500.

 a| 
ONTAP 9.14,1



 a| 
Suporte a storage de objetos S3 em agregados espelhados e sem espelhamento
 a| 
Você pode habilitar um servidor de storage de objetos S3 em uma SVM em um agregado espelhado ou sem espelhamento em configurações MetroCluster IP e FC.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Suporte S3 com MetroCluster"^]
 a| 
ONTAP 9.14,1



 a| 
Suporte para provisionamento de um bucket do S3 em agregados espelhados e sem espelhamento em um cluster MetroCluster
 a| 
Você pode criar um bucket em um agregado espelhado ou sem espelhamento nas configurações do MetroCluster.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["Crie um bucket do ONTAP S3 em um agregado espelhado ou sem espelhamento em uma configuração do MetroCluster"^]
 a| 
ONTAP 9.14,1



 a| 
Transição do MetroCluster FC para o MetroCluster IP usando um switch compartilhado para storage conetado MetroCluster IP e Ethernet
 a| 
Você pode fazer a transição de uma configuração MetroCluster FC para uma MetroCluster IP sem interrupções usando um switch de storage compartilhado.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Transição sem interrupções de um MetroCluster FC para uma configuração MetroCluster IP (ONTAP 9.8 e posterior)"]
 a| 
ONTAP 9.13,1



 a| 
Transições ininterruptas de uma configuração de FC MetroCluster de oito nós para uma configuração IP MetroCluster
 a| 
Você pode migrar workloads e dados de uma configuração MetroCluster FC de oito nós existente para uma nova configuração MetroCluster IP sem interrupções.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Faça a transição de um MetroCluster FC para uma configuração MetroCluster IP sem interrupções"]
 a| 
ONTAP 9.13,1



 a| 
Upgrades de configuração IP MetroCluster de quatro nós usando switchover e switchback
 a| 
Você pode atualizar controladores em uma configuração IP MetroCluster de quatro nós usando switchover e switchback com `system controller replace` comandos.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["Atualize controladores em uma configuração IP MetroCluster de quatro nós"]
 a| 
ONTAP 9.13,1



 a| 
O switchover não planejado automático assistido por mediador (MAUSO) é acionado para um desligamento ambiental
 a| 
Se um site desligar graciosamente devido a um desligamento ambiental, MAUSO é acionado.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Como o Mediador ONTAP suporta o switchover não planejado automático"]
 a| 
ONTAP 9.13,1



 a| 
Suporte para configurações de IP MetroCluster de oito nós
 a| 
Você pode atualizar os controladores e o storage em uma configuração IP do MetroCluster de oito nós expandindo a configuração para se tornar uma configuração temporária de doze nós e removendo os grupos de DR antigos.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["Atualizar uma configuração de MetroCluster IP de quatro nós"]
 a| 
ONTAP 9.13,1



 a| 
Conversão de configuração IP do MetroCluster para uma configuração de switch MetroCluster de armazenamento compartilhado
 a| 
Você pode converter uma configuração IP MetroCluster para uma configuração de switch MetroCluster de armazenamento compartilhado.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["Substitua um switch IP"]
 a| 
ONTAP 9.13,1



 a| 
Recurso de comutação forçada automática do MetroCluster em uma configuração IP do MetroCluster
 a| 
Você pode habilitar o recurso de switchover forçado automático do MetroCluster em uma configuração IP do MetroCluster. Este recurso é uma extensão do recurso de switchover não planejado assistido por Mediador (MAUSO).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["Limitações de comutação automática"]
 a| 
ONTAP 9.12,1



 a| 
S3 em um SVM em um agregado sem espelhamento em uma configuração MetroCluster IP
 a| 
Você pode habilitar um servidor de storage de objetos do ONTAP Simple Storage Service (S3) em uma SVM em um agregado sem espelhamento em uma configuração IP do MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Suporte S3 com MetroCluster"^]
 a| 
ONTAP 9.12,1



 a| 
Compatibilidade com MetroCluster IP para NVMe
 a| 
O protocolo NVMe/FC é compatível com configurações MetroCluster IP de quatro nós.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configurações DE SAN em um ambiente MetroCluster"^]
 a| 
ONTAP 9.12,1



 a| 
Suporte a IPsec para protocolo de host front-end em configurações de conexão de malha MetroCluster IP e MetroCluster
 a| 
O suporte IPsec para protocolo de host front-end (como NFS e iSCSI) está disponível nas configurações de conexão de malha do MetroCluster IP e MetroCluster.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurar a segurança IP (IPsec) através da criptografia por fio"^]
 a| 
ONTAP 9.12,1



 a| 
Transição de uma configuração MetroCluster FC para uma configuração AFF A250 ou FAS500f MetroCluster IP
 a| 
Você pode fazer a transição de uma configuração MetroCluster FC para uma configuração AFF A250 ou FAS500f MetroCluster IP.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["Mova as conexões do cluster local"]
 a| 
ONTAP 9.11,1



 a| 
Grupos de consistência
 a| 
Os grupos de consistência são compatíveis com as configurações do MetroCluster.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["Grupos de consistência nas configurações do MetroCluster"^]
 a| 
ONTAP 9.11,1



 a| 
Atualização simplificada do controlador de nós em uma configuração de MetroCluster FC
 a| 
O procedimento de atualização para o processo de atualização usando switchover e switchback foi simplificado.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Atualize os controladores em uma configuração MetroCluster FC usando o switchover e o switchback"]
 a| 
ONTAP 9.10,1



 a| 
Suporte IP para link compartilhado na camada 3
 a| 
As configurações IP do MetroCluster podem ser implementadas com conexões back-end roteadas por IP (camada 3).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["Considerações para redes de grande área da camada 3"]
 a| 
ONTAP 9.9,1



 a| 
Suporte para configurações de MetroCluster de oito nós
 a| 
Clusters permanentes de oito nós são compatíveis com configurações IP e MetroCluster conectadas à malha.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Instale e faça o cabo dos componentes do MetroCluster"]
 a| 
ONTAP 9.9,1

|===