---
permalink: maintain/concept_using_fibrebridge_7600n_bridges_in_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, support, fibrebridge, bridges, configurations 
summary: A ponte FibreBridge 7600N é suportada no ONTAP 9.5 e posterior como um substituto para a ponte FibreBridge 7500N ou 6500N ou ao adicionar novo armazenamento à configuração do MetroCluster. Os requisitos de zoneamento e restrições em relação ao uso dos portos FC da ponte são os mesmos que os da ponte FibreBridge 7500N. 
---
= Suporte para bridgeBridge 7600N em configurações MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A ponte FibreBridge 7600N é suportada no ONTAP 9.5 e posterior como um substituto para a ponte FibreBridge 7500N ou 6500N ou ao adicionar novo armazenamento à configuração do MetroCluster. Os requisitos de zoneamento e restrições em relação ao uso dos portos FC da ponte são os mesmos que os da ponte FibreBridge 7500N.

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]


NOTE: As bridges FibreBridge 6500N não são suportadas em configurações que executam o ONTAP 9.8 e posterior.

[cols="27,19,27,27"]
|===


| Caso de uso | Mudanças de zoneamento necessárias? | Restrições | Procedimento 


 a| 
Substituindo uma única ponte FibreBridge 7500N por uma única ponte FibreBridge 7600N
 a| 
Não
 a| 
A ponte FibreBridge 7600N deve ser configurada exatamente da mesma forma que a ponte FibreBridge 7500N.
 a| 
link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-7500n-with-a-7600n-bridge["Troca quente de uma FibreBridge 7500N com uma ponte 7600N"]



 a| 
Substituindo uma única ponte FibreBridge 6500N por uma única ponte FibreBridge 7600N
 a| 
Não
 a| 
A ponte FibreBridge 7600N deve ser configurada exatamente da mesma forma que a ponte FibreBridge 6500N.
 a| 
link:task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["Troca quente de uma ponte FibreBridge 6500N com uma ponte FibreBridge 7600N ou 7500N"]



 a| 
Adicionando um novo armazenamento através da adição de um novo par de pontes FibreBridge 7600N
 a| 
Sim

É necessário adicionar zonas de storage para cada uma das portas FC das novas pontes.
 a| 
Você precisa ter portas disponíveis na malha do switch FC (em uma configuração MetroCluster conectada à malha) ou nos controladores de storage (em uma configuração Stretch MetroCluster). Cada par de pontes do FibreBridge 7500N ou 7600N pode oferecer suporte a até quatro stacks.
 a| 
link:task_fb_hot_add_stack_of_shelves_and_bridges.html["Adição rápida de uma stack de shelves de disco SAS e bridges a um sistema MetroCluster"]

|===