---
permalink: maintain/concept_in_band_management_of_the_fc_to_sas_bridges.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, in, band, management, fc, sas, bridges 
summary: Começando com o ONTAP 9.5 com o FibreBridge 7500N ou 7600N bridges, o gerenciamento em banda das pontes é suportado como uma alternativa ao gerenciamento IP das pontes. A partir do ONTAP 9.8, o gerenciamento fora da banda está obsoleto. 
---
= Gerenciamento na banda das pontes FC para SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Começando com o ONTAP 9.5 com o FibreBridge 7500N ou 7600N bridges, o gerenciamento em banda das pontes é suportado como uma alternativa ao gerenciamento IP das pontes. A partir do ONTAP 9.8, o gerenciamento fora da banda está obsoleto.

.Sobre esta tarefa

NOTE: A partir de ONTAP 9.8, o `storage bridge` comando é substituído por `system bridge`. As etapas a seguir mostram o `storage bridge` comando, mas se você estiver executando o ONTAP 9.8 ou posterior, o `system bridge` comando é preferido.

Ao usar o gerenciamento na banda, as bridges podem ser gerenciadas e monitoradas a partir da CLI do ONTAP por meio da conexão FC à ponte. O acesso físico à ponte através das portas Ethernet da ponte não é necessário, reduzindo a vulnerabilidade de segurança da ponte.

A disponibilidade do gerenciamento em banda das pontes depende da versão do ONTAP:

* A partir do ONTAP 9.8, as bridges são gerenciadas por meio de conexões na banda por padrão e o gerenciamento fora da banda das bridges via SNMP é obsoleto.
* ONTAP 9.5 a 9,7: O gerenciamento na banda ou o gerenciamento SNMP fora da banda é suportado.
* Antes do ONTAP 9.5, somente o gerenciamento SNMP fora da banda é suportado.


Os comandos Bridge CLI podem ser emitidos a partir do comando ONTAP interface `storage bridge run-cli -name _bridge-name_ -command _bridge-command-name_` na interface ONTAP.


NOTE: O uso do gerenciamento na banda com acesso IP desativado é recomendado para melhorar a segurança limitando a conetividade física da ponte.

.Informações relacionadas
link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-bridge-with-a-replacement-bridge-of-the-same-model["Troca a quente de uma ponte com uma ponte de substituição do mesmo modelo"]

link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-7500n-with-a-7600n-bridge["Troca quente de uma FibreBridge 7500N com uma ponte 7600N"]

link:task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["Troca quente de uma ponte FibreBridge 6500N com uma ponte FibreBridge 7600N ou 7500N"]

link:task_fb_hot_add_stack_of_shelves_and_bridges.html#hot-adding-a-stack-of-sas-disk-shelves-and-bridges["Adição rápida de uma stack de compartimentos e bridges de disco SAS"]



== Gerenciamento de uma ponte FibreBridge a partir de ONTAP

A partir do ONTAP 9.5, você pode usar a CLI do ONTAP para passar os comandos do FibreBridge para a bridge e exibir os resultados desses comandos.

.Sobre esta tarefa
--

NOTE: A partir de ONTAP 9.8, o `storage bridge` comando é substituído por `system bridge`. As etapas a seguir mostram o `storage bridge` comando, mas se você estiver executando o ONTAP 9.8 ou posterior, o `system bridge` comando é preferido.

--
.Passos
. Execute o comando FibreBridge aplicável dentro do `storage bridge run-cli` comando:
+
`storage bridge run-cli -name _bridge-name_ -command _"command-text"_`

+
O seguinte comando executa o comando FibreBridge `SASPortDisable` a partir do prompt ONTAP para desativar a porta SAS b na ponte:

+
[listing]
----
cluster_A::> storage bridge run-cli -name "SASPortDisable b"

SAS Port B has been disabled.
Ready
cluster_A::>
----

