---
permalink: maintain/enable-console-logging-before-maintenance.html 
sidebar: sidebar 
keywords: metrocluster, maintain, enable, autosupport, logging, maintenance, service,ip, switch, replacement, rename 
summary: Ative o registo da consola nos seus dispositivos antes de executar tarefas de manutenção. 
---
= Ative o registo da consola antes de executar tarefas de manutenção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ative o registo da consola nos seus dispositivos antes de executar tarefas de manutenção.

A NetApp recomenda fortemente que você ative o log do console nos dispositivos que você está usando e execute as seguintes ações antes de executar os procedimentos de manutenção:

* Deixe o AutoSupport ativado durante a manutenção.
* Acione uma mensagem de manutenção do AutoSupport antes e depois da manutenção para desativar a criação de casos durante a atividade de manutenção.
+
Consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Como suprimir a criação automática de casos durante as janelas de manutenção programada"^].

* Ative o registo de sessão para qualquer sessão CLI. Para obter instruções sobre como ativar o registo de sessão, consulte a secção "saída de sessão de registo" no artigo da base de dados de conhecimento link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para uma conetividade ideal aos sistemas ONTAP"^].

