---
permalink: maintain/reference_fb_replace_a_power_supply.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, replacing, failed, power, supply, module 
summary: Quando há uma alteração no status de um módulo de fonte de alimentação para a ponte, você pode remover e instalar o módulo de fonte de alimentação. 
---
= Substituição a quente de um módulo de fonte de alimentação com falha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando há uma alteração no status de um módulo de fonte de alimentação para a ponte, você pode remover e instalar o módulo de fonte de alimentação.

Pode ver a alteração no estado de um módulo de fonte de alimentação através dos LEDs na ponte. Você também pode visualizar o status dos módulos de fonte de alimentação via ExpressNAV GUI e a ponte CLI, via porta serial ou via Telnet.

* Este procedimento é NDO (sem interrupções) e leva aproximadamente 15 minutos para ser concluído.
* Você precisa da senha de administrador e acesso a um servidor FTP ou SCP.



NOTE: O _ATTO FibreBridge Installation and Operation Manual_ para sua ponte de modelo tem mais informações sobre interfaces de gerenciamento.

Você pode acessar este e outros conteúdos no SITE DA ATTO usando o link fornecido na página Descrição DO ATTO Fibrebridge.
