---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: Atualizando o firmware em switches IP MetroCluster. 
---
= Atualize o firmware nos switches IP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário atualizar o firmware em um switch IP MetroCluster.



== Verifique se o RCF é suportado

Ao alterar a versão do ONTAP ou a versão do firmware do switch, você deve verificar se tem um arquivo de configuração de referência (RCF) compatível com essa versão. Se você usar a link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"^] ferramenta, o RCF correto será gerado para sua configuração.

.Passos
. Use os seguintes comandos dos switches para verificar a versão do RCF:
+
[cols="30,70"]
|===


| A partir deste interrutor... | Emitir este comando... 


 a| 
Interrutor Broadcom
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Interrutor Cisco
 a| 
`IP_switch_A_1# show banner motd`



 a| 
Interrutor NVIDIA SN2100
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
Localize a linha na saída do comando que indica a versão RCF. Por exemplo, a seguinte saída de um switch Cisco indica que a versão RCF é "'v1,80".

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. Para verificar quais arquivos são suportados para uma versão, switch e plataforma específica do ONTAP, use o link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator para MetroCluster IP"^]. Se você pode gerar o RCF para a configuração que você tem ou para a qual deseja atualizar, então ele é suportado.
. Para verificar se o firmware do switch é suportado, consulte o seguinte:
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["Matriz de interoperabilidade do NetApp"^]






== Atualize o firmware do switch

.Sobre esta tarefa
Você deve repetir esta tarefa em cada uma das opções sucessivamente.

link:enable-console-logging-before-maintenance.html["Ativar o registo da consola"] antes de executar esta tarefa.

[[step_1_fw_upgrade]]
.Passos
. Verifique a integridade da configuração.
+
.. Verifique se o MetroCluster está configurado e no modo normal em cada cluster:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Verifique se o espelhamento está ativado em cada nó:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Verifique se os componentes do MetroCluster estão em bom estado:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
A operação é executada em segundo plano.

.. Após `metrocluster check run` a conclusão da operação, execute:
+
`metrocluster check show`

+
Após cerca de cinco minutos, são apresentados os seguintes resultados:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Verifique se não existem alertas de saúde:
+
`system health alert show`



. Instale o software no primeiro interrutor.
+

NOTE: Tem de instalar o software do interrutor nos interrutores pela seguinte ordem: Switch_A_1, switch_B_1, switch_A_2, switch_B_2.

+
Siga as etapas para instalar o software do switch no tópico relevante, dependendo se o tipo de switch é Broadcom, Cisco ou NVIDIA:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Baixe e instale o software Broadcom switch EFOS"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Baixe e instale o software Cisco switch NX-os"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Baixe e instale o software Cumulus switch NVIDIA SN2100"]


. Repita o passo anterior para cada um dos interrutores.
. Repita <<step_1_fw_upgrade,Passo 1>> para verificar a integridade da configuração.

