---
permalink: maintain/task-configure-encryption.html 
sidebar: sidebar 
keywords: metrocluster, ip, encryption, end-to-end, back-end, aff a400, fas8300, fas8700, encrypt, enable, disable, configure, controllers 
summary:  
---
= Configurar criptografia de ponta a ponta em uma configuração IP do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.15.1, você pode configurar a criptografia de ponta a ponta em sistemas suportados para criptografar o tráfego de back-end, como NVlog e dados de replicação de armazenamento, entre os sites em uma configuração de IP do MetroCluster .

.Sobre esta tarefa
* Você deve ser um administrador de cluster para executar esta tarefa.
* Antes de poder configurar a encriptação de ponta a ponta, tem link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-concept.html["Configurar o gerenciamento de chaves externas"^]de .
* Revise os sistemas suportados e a versão mínima do ONTAP necessária para configurar a criptografia de ponta a ponta em uma configuração IP do MetroCluster:
+
[cols="2*"]
|===
| Versão mínima de ONTAP | Sistemas suportados 


 a| 
ONTAP 9.17.1
 a| 
** AFF A800, AFF C800
** AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
** AFF A70, AFF A90, AFF A1K, AFF C80
** FAS50, FAS70, FAS90




 a| 
ONTAP 9.15,1
 a| 
** AFF A400
** FAS8300
** FAS8700


|===




== Ative a criptografia de ponta a ponta

Execute as etapas a seguir para habilitar a criptografia de ponta a ponta.

.Passos
. Verifique a integridade da configuração do MetroCluster.
+
.. Verifique se os componentes do MetroCluster estão em bom estado:
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run
----
+
A operação é executada em segundo plano.

.. Após `metrocluster check run` a conclusão da operação, execute:
+
[source, cli]
----
metrocluster check show
----
+
Após cerca de cinco minutos, são apresentados os seguintes resultados:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Verificar o estado do funcionamento da verificação do MetroCluster em curso:
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. Verifique se não há alertas de saúde:
+
[source, cli]
----
system health alert show
----


. Verifique se o gerenciamento de chaves externas está configurado em ambos os clusters:
+
[source, cli]
----
security key-manager external show-status
----
. Habilite a criptografia de ponta a ponta para cada grupo de DR:
+
[source, cli]
----
metrocluster modify -is-encryption-enabled true -dr-group-id <dr_group_id>
----
+
*Exemplo*

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled true -dr-group-id 1
Warning: Enabling encryption for a DR Group will secure NVLog and Storage
         replication data sent between MetroCluster nodes and have an impact on
         performance. Do you want to continue? {y|n}: y
[Job 244] Job succeeded: Modify is successful.
----
+
Repita esta etapa para cada grupo de DR na configuração.

. Verifique se a criptografia de ponta a ponta está ativada:
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
*Exemplo*

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          true
1           cluster_A  node_A_2  configured          true
1           cluster_B  node_B_1  configured          true
1           cluster_B  node_B_2  configured          true
4 entries were displayed.
----




== Desative a criptografia de ponta a ponta

Execute as etapas a seguir para desativar a criptografia de ponta a ponta.

.Passos
. Verifique a integridade da configuração do MetroCluster.
+
.. Verifique se os componentes do MetroCluster estão em bom estado:
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run

----
+
A operação é executada em segundo plano.

.. Após `metrocluster check run` a conclusão da operação, execute:
+
[source, cli]
----
metrocluster check show
----
+
Após cerca de cinco minutos, são apresentados os seguintes resultados:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Verificar o estado do funcionamento da verificação do MetroCluster em curso:
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. Verifique se não há alertas de saúde:
+
[source, cli]
----
system health alert show
----


. Verifique se o gerenciamento de chaves externas está configurado em ambos os clusters:
+
[source, cli]
----
security key-manager external show-status
----
. Desative a criptografia de ponta a ponta em cada grupo de DR:
+
[source, cli]
----
metrocluster modify -is-encryption-enabled false -dr-group-id <dr_group_id>
----
+
*Exemplo*

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled false -dr-group-id 1
[Job 244] Job succeeded: Modify is successful.
----
+
Repita esta etapa para cada grupo de DR na configuração.

. Verifique se a criptografia de ponta a ponta está desativada:
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
*Exemplo*

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          false
1           cluster_A  node_A_2  configured          false
1           cluster_B  node_B_1  configured          false
1           cluster_B  node_B_2  configured          false
4 entries were displayed.
----

