---
permalink: maintain/task_add_lsls_to_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, isl, cisco, switch 
summary: Talvez seja necessário adicionar ISLs a um switch se você estiver adicionando ou atualizando hardware, como controladores adicionais ou mais rápidos ou switches mais rápidos. 
---
= Adicionando lSLs a um switch Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário adicionar ISLs a um switch se você estiver adicionando ou atualizando hardware, como controladores adicionais ou mais rápidos ou switches mais rápidos.

.Sobre esta tarefa
* Conclua todas as etapas em ambos os switches para garantir a conetividade ISL.
* link:enable-console-logging-before-maintenance.html["Ativar o registo da consola"] antes de executar esta tarefa.


.Passos
. Desative as portas ISL das ISLs a serem adicionadas em ambos os switches na malha:
+
`*FC_switch_A_1#config t*`

+
Introduza os comandos de configuração, um por linha. Termine com CTRL-Z depois de todos os comandos de configuração terem sido introduzidos.

+
[listing]
----

	FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. Insira SFPs nas portas que você está adicionando como portas ISL, e faça o cabo deles de acordo com o _Installation and Configuration Guide_.
+
Verifique se essas portas estão listadas no _Installation and Configuration Guide_ para o switch ao qual você as está adicionando.

. Configure as portas ISL de acordo com o _Installation and Configuration Guide_.
. Ative todas as portas ISL (se não estiver ativado) em ambos os switches na estrutura:
+
`*FC_switch_A_1# config t*`

+
Introduza os comandos de configuração, um por linha. Terminar com CTRL-Z.

+
[listing]
----

 FC_switch_A_1# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. Verifique se as ISLs estão estabelecidas entre ambos os switches:
+
`*show topology isl*`

. Repita o procedimento no segundo tecido:
+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----

