---
permalink: maintain/task_fb_hot_add_a_disk_shelf_install_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, disk, shelf 
summary: É possível adicionar um compartimento de disco a quente quando quiser aumentar o storage sem reduzir a performance. 
---
= Adicionar um compartimento de disco SAS a uma stack de gavetas de disco SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível adicionar um compartimento de disco a quente quando quiser aumentar o storage sem reduzir a performance.



== Etapa 1: Prepare-se para adicionar um compartimento de disco SAS a quente

Para se preparar para adicionar um compartimento de disco SAS a quente, você precisa baixar documentos juntamente com a unidade de disco e o firmware do compartimento de disco.

.Antes de começar
* Verifique se o seu sistema é uma configuração suportada e está a executar uma versão suportada do ONTAP.
* Verifique se todas as unidades de disco e compartimentos de disco no sistema estão executando a versão de firmware mais recente.
+
Talvez você queira atualizar o firmware do disco e do compartimento em toda a configuração do MetroCluster antes de adicionar gavetas.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["Atualize, reverta ou downgrade"]



.Passos
. Faça o download ou veja os seguintes documentos no site de suporte da NetApp:
+
** https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade"]
** O _Installation Guide_ para o modelo do seu compartimento de disco.


. Verifique se o compartimento de disco que você está adicionando a quente é suportado.
+
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade"^]

. Transfira o firmware mais recente do compartimento de disco e disco:
+

NOTE: Nesta etapa, você só conclui a parte de download das instruções. Você precisa seguir as etapas em <<step_2_hot_add_shelf,adicionar um compartimento de disco a quente>> para instalar o compartimento de disco.

+
.. Faça download do firmware do disco e faça uma cópia das instruções de firmware do disco para referência posterior.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]

.. Faça download do firmware do compartimento de disco e faça uma cópia das instruções de firmware do compartimento de disco para referência posteriormente.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Downloads do NetApp: Firmware da gaveta de disco"^]







== Etapa 2: Adicionar um compartimento de disco a quente

Use o procedimento a seguir para adicionar um compartimento de disco a uma pilha.

.Antes de começar
* Verifique se o sistema atende a todos os requisitos do <<prepare_to_hot_add_disk,Prepare-se para gavetas de disco SAS hot-add>>.
* Verifique se o seu ambiente atende a um dos seguintes cenários antes de adicionar um compartimento a quente:
+
** Você tem duas pontes do FibreBridge 7500N conetadas a uma pilha de gavetas de disco SAS.
** Você tem duas pontes do FibreBridge 7600N conetadas a uma pilha de gavetas de disco SAS.
** Você tem uma ponte FibreBridge 7500N e uma ponte FibreBridge 7600N conetada a uma pilha de gavetas de disco SAS.




.Sobre esta tarefa
* Esse procedimento serve para adicionar um compartimento de disco à última gaveta de disco em uma pilha.
+
Este procedimento é escrito com o pressuposto de que o último compartimento de disco em uma stack está conetado da IOM A à ponte A e da IOM B à ponte B.

* Este é um procedimento sem interrupções.
* Você deve adicionar um número igual de compartimentos de disco em cada local.
* Se você estiver adicionando mais de um compartimento de disco, adicione um compartimento de disco de cada vez.
+
Cada par de pontes FibreBridge 7500N ou 7600N pode suportar até quatro pilhas.



[CAUTION]
====
Adicionar um compartimento de disco requer que você atualize o firmware da unidade de disco no compartimento de disco hot-added executando o `storage disk firmware update` comando no modo avançado. A execução deste comando pode causar interrupções se o firmware nas unidades de disco existentes no seu sistema for uma versão mais antiga.

Se você inserir um cabo SAS na porta errada, depois de remover o cabo de uma porta SAS, aguarde pelo menos 120 segundos antes de conetar o cabo a uma porta SAS diferente. Se você não conseguir fazer isso, o sistema não reconhecerá que você moveu o cabo para uma porta diferente.

====
.Passos
. Aterre-se corretamente.
. Verifique a conectividade do compartimento de disco a partir do console do sistema de qualquer controlador:
+
`sysconfig -v`

+
A saída é semelhante ao seguinte:

+
** Cada ponte em uma linha separada e sob cada porta FC à qual ela é visível; por exemplo, adicionar um compartimento de disco a um conjunto de bridgeBridge 7500N resulta na seguinte saída:
+
[listing]
----
FC-to-SAS Bridge:
cisco_A_1-1:9.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100189
cisco_A_1-2:1.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100162
----
** Cada compartimento de disco em uma linha separada sob cada porta FC à qual ele é visível:
+
[listing]
----
Shelf   0: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
Shelf   1: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
----
** Cada unidade de disco em uma linha separada sob cada porta FC para a qual ela é visível:
+
[listing]
----
cisco_A_1-1:9.126L1   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
cisco_A_1-1:9.126L2   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
----


. Verifique se o sistema tem atribuição automática de disco ativada a partir da consola de qualquer controlador:
+
`storage disk option show`

+
A política de atribuição automática é apresentada na coluna atribuição automática.

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. Se o sistema não tiver atribuição automática de disco ativada ou se as unidades de disco na mesma pilha forem de propriedade de ambos os controladores, atribua unidades de disco aos pools apropriados.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gerenciamento de disco e agregado"]

+
[NOTE]
====
** Se você estiver dividindo uma única pilha de compartimentos de disco entre dois controladores, a atribuição automática de disco deve ser desativada antes de atribuir a propriedade de disco; caso contrário, quando você atribuir qualquer unidade de disco única, as unidades de disco restantes podem ser atribuídas automaticamente ao mesmo controlador e pool.
+
 `storage disk option modify -node <node-name> -autoassign off`O comando desativa a atribuição automática do disco.

** Não é possível adicionar unidades a agregados ou volumes até que você tenha atualizado o firmware da unidade de disco e do compartimento de disco.


====
. Atualize o firmware do compartimento de disco para a versão mais atual usando as instruções para o firmware baixado.
+
Você pode executar os comandos no procedimento a partir do console do sistema de qualquer controlador.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Downloads do NetApp: Firmware da gaveta de disco"]

. Instale e faça o cabo da prateleira de discos:
+

NOTE: Não force um conetor para uma porta. Os cabos mini-SAS são chaveados; quando orientados corretamente para uma porta SAS, o cabo SAS clica no lugar e o LED LNK da porta SAS da gaveta de disco acende-se a verde.para as prateleiras de disco, você insere um conetor de cabo SAS com a aba de puxar orientada para cima (na parte superior do conetor).

+
.. Instale o compartimento de disco, ligue-o e defina a ID do compartimento.
+
O _Installation Guide_ do modelo de compartimento de disco fornece informações detalhadas sobre a instalação das gavetas de disco.

+

NOTE: É necessário desligar o compartimento de disco e manter as IDs das gavetas exclusivas para cada compartimento de disco SAS em todo o sistema de storage.

.. Desconete o cabo SAS da porta IOM B da última gaveta da stack e reconete-o à mesma porta da nova gaveta.
+
A outra extremidade deste cabo permanece ligada à ponte B..

.. Encadeie em série a nova gaveta de disco fazendo o cabeamento das novas portas IOM de gaveta (de Iom A e IOM B) até as últimas portas IOM de gaveta (de Iom A e IOM B).


+
O _Installation Guide_ para o modelo do seu compartimento de disco fornece informações detalhadas sobre as prateleiras de disco em encadeamento em série.

. Atualize o firmware da unidade de disco para a versão mais atual a partir da consola do sistema.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"]

+
.. Mude para o nível de privilégio avançado
`set -privilege advanced`
+
Você precisa responder com `*y*` quando solicitado para continuar no modo avançado e ver o prompt do modo avançado (*>).

.. Atualize o firmware da unidade de disco para a versão mais atual a partir da consola do sistema
`storage disk firmware update`
.. Voltar para o nível de privilégio de administrador
`set -privilege admin`
.. Repita as subetapas anteriores no outro controlador.


. Verifique a operação da configuração do MetroCluster no ONTAP:
+
.. Verifique se o sistema é multipathed:
+
`node run -node <node-name> sysconfig -a`

.. Verifique se há alertas de integridade em ambos os clusters
`system health alert show`
.. Confirme a configuração do MetroCluster e se o modo operacional está normal
`metrocluster show`
.. Execute uma verificação MetroCluster
`metrocluster check run`
.. Apresentar os resultados da verificação MetroCluster:
+
`metrocluster check show`

.. Verifique se existem alertas de estado nos interrutores (se presentes):
+
`storage switch show`

.. Execute o Active IQ Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"]

.. Depois de executar o Config Advisor, revise a saída da ferramenta e siga as recomendações na saída para resolver quaisquer problemas descobertos.


. Se você estiver adicionando mais de um compartimento de disco a quente, repita as etapas anteriores para cada compartimento de disco que você está adicionando a quente.

