---
permalink: install-stretch/concept_choosing_the_correct_installation_procedure_for_your_configuration_mcc_install.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, correct, procedure, configuration 
summary: Você deve escolher o procedimento de instalação correto com base em como os controladores de armazenamento se conectam às prateleiras de armazenamento. 
---
= Escolhendo o procedimento de instalação correto para sua configuração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve escolher o procedimento de instalação correto com base em como os controladores de armazenamento se conectam às prateleiras de armazenamento.

|===


| Para este tipo de instalação... | Utilize estes procedimentos... 


 a| 
Configuração elástica de dois nós com pontes FC para SAS
 a| 
. link:task_configure_the_mcc_hardware_components_2_node_stretch_atto.html["Cabeamento de uma configuração Stretch MetroCluster de dois nós conetada em ponte"]
. link:concept_configuring_the_mcc_software_in_ontap.html["Configurando o software MetroCluster no ONTAP"]




 a| 
Configuração elástica de dois nós com cabeamento SAS de conexão direta
 a| 
. link:task_configure_the_mcc_hardware_components_2_node_stretch_sas.html["Cabeamento de uma configuração Stretch MetroCluster com conexão SAS de dois nós"]
. link:concept_configuring_the_mcc_software_in_ontap.html["Configurando o software MetroCluster no ONTAP"]


|===