---
permalink: install-stretch/task_configure_the_fc_to_sas_bridges_fb_new_install_configure.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, configuration, fc, sas, bridges 
summary: Antes de fazer o cabeamento do modelo das pontes FC para SAS, você deve configurar as configurações no software FibreBridge. 
---
= Configuração de pontes FC para SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de fazer o cabeamento do modelo das pontes FC para SAS, você deve configurar as configurações no software FibreBridge.

.Sobre esta tarefa
Você deve decidir se vai usar o gerenciamento em banda das pontes.


NOTE: A partir de ONTAP 9.8, o `storage bridge` comando é substituído por `system bridge`. As etapas a seguir mostram o `storage bridge` comando. No entanto, se você estiver executando o ONTAP 9.8 ou posterior, o `system bridge` comando será preferido.

Se você estiver usando o gerenciamento na banda da ponte em vez do gerenciamento IP, as etapas para configurar a porta Ethernet e as configurações IP podem ser ignoradas.

.Passos
. Se estiver configurando para gerenciamento na banda, conete um cabo da porta serial FibreBridge RS-232 à porta serial (com) em um computador pessoal.
+
A conexão serial será usada para configuração inicial. Em seguida, o gerenciamento na banda via ONTAP e as portas FC podem ser usados para monitorar e gerenciar a ponte.

. Se estiver configurando para gerenciamento IP, conete a porta 1 de gerenciamento Ethernet em cada bridge à rede usando um cabo Ethernet.
+
Em sistemas que executam o ONTAP 9.5 ou posterior, o gerenciamento na banda pode ser usado para acessar a ponte através das portas FC em vez da porta Ethernet. A partir do ONTAP 9.8, somente o gerenciamento na banda é suportado e o gerenciamento SNMP é obsoleto.

+
A porta 1 de gerenciamento Ethernet permite que você baixe rapidamente o firmware da ponte (usando interfaces de gerenciamento ATTO ExpressNAV ou FTP) e recupere arquivos principais e extraia logs.

. Se estiver configurando para gerenciamento IP, configure a porta 1 de gerenciamento Ethernet para cada bridge seguindo o procedimento na seção 2,0 do _ATTO FibreBridge Installation and Operation Manual_ para o modelo de bridge.
+
Em sistemas que executam o ONTAP 9.5 ou posterior, o gerenciamento na banda pode ser usado para acessar a ponte através das portas FC em vez da porta Ethernet. A partir do ONTAP 9.8, somente o gerenciamento na banda é suportado e o gerenciamento SNMP é obsoleto.

+
Ao executar o Quicknav para configurar uma porta de gerenciamento Ethernet, apenas a porta de gerenciamento Ethernet conetada pelo cabo Ethernet é configurada. Por exemplo, se você também quiser configurar a porta 2 de gerenciamento Ethernet, será necessário conetar o cabo Ethernet à porta 2 e executar o Quicknav.

. Configure a ponte.
+
Você deve anotar o nome de usuário e a senha que você designar.

+

NOTE: Não configure a sincronização de tempo no ATTO FibreBridge 7600N ou 7500N. A sincronização de tempo para O ATTO FibreBridge 7600N ou 7500N é definida para a hora do cluster depois que a ponte é descoberta pelo ONTAP. Também é sincronizado periodicamente uma vez por dia. O fuso horário utilizado é GMT e não é variável.

+
.. Se estiver configurando para gerenciamento de IP, configure as configurações IP da ponte.
+
Em sistemas que executam o ONTAP 9.5 ou posterior, o gerenciamento na banda pode ser usado para acessar a ponte através das portas FC em vez da porta Ethernet. A partir do ONTAP 9.8, somente o gerenciamento na banda é suportado e o gerenciamento SNMP é obsoleto.

+
Para definir o endereço IP sem o utilitário Quicknav, você precisa ter uma conexão serial com o FibreBridge.

+
Se estiver usando a CLI, você deve executar os seguintes comandos:

+
`set ipaddress mp1 _ip-address_`

+
`set ipsubnetmask mp1 _subnet-mask_`

+
`set ipgateway mp1 x.x.x.x`

+
`set ipdhcp mp1 disabled`

+
`set ethernetspeed mp1 1000`

.. Configure o nome da ponte.
+
As pontes devem ter um nome exclusivo dentro da configuração do MetroCluster.

+
Exemplos de nomes de bridge para um grupo de pilha em cada local:

+
*** bridge_A_1a
*** bridge_A_1b
*** bridge_B_1a
*** bridge_B_1b
+
Se estiver usando a CLI, você deve executar o seguinte comando:

+
`set bridgename _bridgename_`



.. Se estiver executando o ONTAP 9.4 ou anterior, ative o SNMP na ponte
`set SNMP enabled`
+
Em sistemas que executam o ONTAP 9.5 ou posterior, o gerenciamento na banda pode ser usado para acessar a ponte através das portas FC em vez da porta Ethernet. A partir do ONTAP 9.8, somente o gerenciamento na banda é suportado e o gerenciamento SNMP é obsoleto.



. Configurar as portas FC de ponte.
+
.. Configure a taxa/velocidade de dados das portas FC em ponte.
+
A taxa de dados FC suportada depende da ponte do modelo.

+
*** A ponte FibreBridge 7600N suporta até 32, 16 ou 8 Gbps.
*** A ponte FibreBridge 7500N suporta até 16, 8 ou 4 Gbps.
+

NOTE: A velocidade FCDataRate selecionada é limitada à velocidade máxima suportada pela ponte e pela porta FC do módulo do controlador à qual a porta de ponte se coneta. As distâncias de cabeamento não devem exceder as limitações dos SFPs e de outro hardware.

+
--
Se estiver usando a CLI, você deve executar o seguinte comando:

`set FCDataRate _port-numberport-speed_`

--


.. Se você estiver configurando uma ponte FibreBridge 7500N, configure o modo de conexão que a porta usa para "ptp".
+

NOTE: A configuração FCConnMode não é necessária ao configurar uma ponte FibreBridge 7600N.

+
--
Se estiver usando a CLI, você deve executar o seguinte comando:

`set FCConnMode _port-number_ ptp`

--
.. Se você estiver configurando uma ponte FibreBridge 7600N ou 7500N, você deve configurar ou desativar a porta FC2.
+
*** Se estiver usando a segunda porta, repita as subetapas anteriores para a porta FC2.
*** Se você não estiver usando a segunda porta, então você deve desativar a porta
`FCPortDisable port-number`
+
O exemplo a seguir mostra a desativação da porta FC 2:

+
[listing]
----
FCPortDisable 2

Fibre Channel Port 2 has been disabled.
----


.. Se você estiver configurando uma ponte FibreBridge 7600N ou 7500N, desative as portas SAS não utilizadas
`SASPortDisable _sas-port_`
+

NOTE: As portas SAS De A a D estão ativadas por predefinição. Você deve desativar as portas SAS que não estão sendo usadas.

+
Se apenas a porta SAS A for usada, as portas SAS B, C e D devem ser desativadas. O exemplo a seguir mostra a desativação da porta SAS B. você deve desabilitar as portas SAS C e D da mesma forma:

+
....
SASPortDisable b

SAS Port B has been disabled.
....


. Proteja o acesso à ponte e salve a configuração da ponte. Escolha uma opção abaixo, dependendo da versão do ONTAP que seu sistema está sendo executado.
+
|===


| Versão de ONTAP | Passos 


 a| 
*ONTAP 9 1.5 ou posterior*
 a| 
.. Veja o status das pontes: `storage bridge show`
+
A saída mostra qual ponte não está protegida.

.. Fixe a ponte
`securebridge`




 a| 
*ONTAP 9 1.4 ou anterior*
 a| 
.. Veja o status das pontes: `storage bridge show`
+
A saída mostra qual ponte não está protegida.

.. Verifique o estado das portas da ponte não protegida:
+
`info`

+
A saída mostra o status das portas Ethernet MP1 e MP2.

.. Se a porta Ethernet MP1 estiver ativada, execute:
+
`set EthernetPort mp1 disabled`

+
Se a porta Ethernet MP2 também estiver ativada, repita a subetapa anterior para a porta MP2.

.. Salve a configuração da ponte.
+
Você deve executar os seguintes comandos:

+
`SaveConfiguration`

+
`FirmwareRestart`

+
Você é solicitado a reiniciar a ponte.



|===
. Depois de concluir a configuração do MetroCluster, use o `flashimages` comando para verificar sua versão do firmware do FibreBridge e, se as bridges não estiverem usando a versão mais recente suportada, atualize o firmware em todas as bridges na configuração.
+
link:../maintain/index.html["Mantenha os componentes do MetroCluster"]



.Informações relacionadas
link:concept_in_band_management_of_the_fc_to_sas_bridges.html["Gerenciamento na banda das pontes FC para SAS"]
